### ISSUE TITLE
Plugin won't load contact groups

### ISSUE THREAD

**Issue by skeepy** [blind-coder/rcmcarddav#100]
Hello,

I've got a little problem. The CardDav file loads fine from OwnCloud. But I cannot get the groups. All contacts are here. 

The tables "contactgroups" and "contactgroupmembers" seem empty.

I could find any info about the import of contacts in roundcube logs...

Where could I find more info ? Thank you !

**Comment by jcharaoui** [comment]
This is a known issue. See pull request #6

**Comment by mstilkerich** [comment]
CATEGORIES type groups have been added in the meantime, so this issue can be closed.
