### ISSUE TITLE
Cannot talk to  mod_gnutls protocol 

### ISSUE THREAD

**Issue by ragee-ra** [blind-coder/rcmcarddav#101]
Hi guys! 

I'm trying to access a davical server with the plugin and keep receiving this error logs:

[..]
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
PHP Fatal error:  Uncaught exception 'Httpful\Exception\ConnectionErrorException' with message 'Unable to connect to "https://calendar.mydomain.tld:443/caldav.php/ra/temp/": 35 error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol' in /var/www/vhosts/webmail/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php:208
[..]

Obviously the plugin cannot talk to the server. I'm pretty sure this has to do with 'mod_gnutls' I am using on the apache server (instead of the 'usual' ssl_module). Accessing the server without encryption (port 80) works fine!

I searched the internet for quite a few days now and found some similar error logs in owncloud environments. They figured out that it was a 'curl problem' and solved it by setting somewhere CURLOPT_SSL_VERIFYHOST = 0. But this is just a wild guess...

Does anybody know this issue?
Any hints for solutions?

Thanx!

**Comment by blind-coder** [comment]
Are you absolutely sure that you enabled tls on port 443?
Try connecting to "http://calendar.mydomain.tld:443/" (note the http:// and the port :443).

Also, is the correct domain name entered in the SSL certificate?

**Comment by ragee-ra** [comment]
Thank you for replying, Yes, I just checked that again:

Apache is listening on port 443. Accessing the site via https://calendar.mydomain.tld is working as-well. This points to my davical webinterface. 

nmp portscan from another machine gives:

443/tcp open     http         Apache httpd 2.4.7
| ssl-cert: Subject: commonName=calendar.mydomain.tld/organizationName=privat/stateOrProvinceName=Bremen/countryName=DE
| Not valid before: 2015-04-26T18:32:44+00:00
|_Not valid after:  2018-04-25T18:32:44+00:00

So the CN in the SSL certificate is 'calendar.mydomain.tld'. Although it is a self-signed certificate this should do the job. At least I hope so... 

The missing 's' in https://... from the error log was just because I tried all sorts of variations in the URL in carddav plugin. Sorry for the confusion. But the error message remains the same...

**Comment by blind-coder** [comment]
Is it possible to get a user account on that installation so I can verify the problem here?

**Comment by ragee-ra** [comment]
Yes, of course! Send you all necessary data via personal mail. Thank you for taking a closer look.

**Comment by blind-coder** [comment]
Resolved off-tracker.
Issue was incompatibility of php-curl with mod_gnutls.
