### ISSUE TITLE
Fatal error: Call to undefined method

### ISSUE THREAD

**Issue by radekfischer** [blind-coder/rcmcarddav#102]
Hi all,
After I've installed the rcmcarddav extension I get the following error:
"Fatal error: Call to undefined method rcube_db_mysql::set_option() in C:\wwwroot\roundcube\plugins\carddav\carddav.php on line 60"
I run WAMP (although separately installed). The RC is 0.9.0 and runs w/o issues.
What could cause this?
Thanks in advance, Radek

**Comment by blind-coder** [comment]
Roundcube 0.9 is - relatively - old, It didn't have the set_option function.
Please update Roundcube to 1.0 or use an older version of the carddav plugin.

You _might_ just try to comment that line in carddav.php, but it might cause issues.

**Comment by blind-coder** [comment]
But thanks for the notice, I should update composer.json to indicate the minimum roundcube version.
