### ISSUE TITLE
DB tables not being created

### ISSUE THREAD

**Issue by jahabrewer** [blind-coder/rcmcarddav#106]
Hi Benjamin,

I'm excited to use the plugin, but I'm running into a little trouble getting it set up. I'm using 591fa474 and the directions in INSTALL. I complete the INSTALL instructions through #7, but when I try to open roundcube in my web browser, I get errors. The web page shows a database connection error and roundcube's log shows this:

```
[18-Jun-2015 21:21:58 +0000]: <dkau5lt4> DB Error: [1146] Table 'roundcubemail.carddav_addressbooks' doesn't exist (SQL Query: SELECT id FROM carddav_addressbooks WHERE user_id='1' AND active=1) in /var/www/roundcube/program/lib/Roundcube/rcube_db.php on line 543 (GET /)
[18-Jun-2015 21:21:58 +0000]: <dkau5lt4> DB Error: [1146] Table 'roundcubemail.carddav_addressbooks' doesn't exist (GET /)
```

I found the dbinit folder and was tempted to manually import mysql.sql, but some brief grepping led me to believe that this is intended to be handled by migrations automatically. Do you have any guidance for me?

I'm using:
* roundcube 1.1.2
* apache2 2.4.10-10
* php5 5.6.9+dfsg-0+deb8u1
* sabre/vobject 3.4.5
* nategood/httpful 0.2.19

Thanks!

**Comment by blind-coder** [comment]
Hi.

Did you logout and back in after enabling the plugin? That's when the tables are created. It's no longer using the dbinit/ directory (I should get rid of that...) but the dbmigrations/*/<database>.sql files for initialisation.
Can you check if there are messages in roundcube/logs/carddav related to dbmigrations?

**Comment by jahabrewer** [comment]
That got it. I'm not sure how I messed it up. Thanks for your help!
