### ISSUE TITLE
Setting : Keep the previous values in case of failure

### ISSUE THREAD

**Issue by pcouderc12** [blind-coder/rcmcarddav#108]
In Settings, CardDAB, in "Add new addressbook", if there is a failure, users values are automatically cleared. This is not easy, it is better to keep user values whatever the error.

**Comment by mstilkerich** [comment]
This is fixed with commit b68938ce9d33c7110bc8fb611c3ef063f3551123 in the v4 development branch. I'm closing this issue as I believe you are probably no longer around after that long time (sorry for that). Just in case this doesn't solve the issue for you, please comment / reopen on this issue.

**Comment by pcouderc12** [comment]
I am around, and still very satisfied of CardDAV... ;) And I am sure it fixes the issue. Even if these days, I do not add new address book !
