### ISSUE TITLE
Unable to read contacts from OS X Server

### ISSUE THREAD

**Issue by ygini** [blind-coder/rcmcarddav#110]
Hello

I'm trying to setup the carddav plugin on OS X Server 4 (Yoesmite).

Everything is set and the plugin is able to write into the CardDAV server and other CardDAV clients are able to read the new content.

However, when other client add new contacts or update existing one, the roundcube plugin never show the new infos.

Even with refresh_time set at 00:01:00 and waiting more than a minute, I never get the updated content.

If I try to modify a contact updated by an other client (and not properly displayed by the plugin) it fail with this message in log file:
BACKEND: (update) Updating card on server failed

Tell me what kind of info you need.

**Comment by blind-coder** [comment]
Please set the two DEBUG flags in carddav_common.php to true and check in roundcube/logs/carddav for the output.
If you upload that file, please make sure to remove all personal information as well as the contents of the WWW-Authenticate headers.

**Comment by mstilkerich** [comment]
No reply, closing.
