### ISSUE TITLE
OAuth 2.0 for Google Contacts?

### ISSUE THREAD

**Issue by brianjmurrell** [blind-coder/rcmcarddav#111]
In order to use this with Google Contacts, it [needs to support OAuth 2.0](https://developers.google.com/google-apps/carddav/?hl=en#googles_carddav_requires_oauth_20).  Is there any chance of getting that added soon?

**Comment by blind-coder** [comment]
Probably not as I have no idea how to put that into an interface for it.
You can disable the need for OAuth 2.0 though, or use the google contacts plugin.

**Comment by brianjmurrell** [comment]
So, as far as an interface, I think what typically happens is that your application registers with googles oauth 2.0 system and then when a user wants to enable your application to read google contacts, google opens a (i.e. HTML) window (which of course is easy for you given that you are in a browser already) to prompt the user for their google credentials as well as a confirm that they should allow your application access to the contacts data.  Probably some kind of unique API key is generated which is then used for future authentication.

This is all just speculation based on having authenticated google access to applications before with, for example, GNOME Online Accounts.

I don't think there is any lack of documentation on how to interface with starting at the [previous link](https://developers.google.com/google-apps/carddav/?hl=en#googles_carddav_requires_oauth_20) I posted.

**Comment by blind-coder** [comment]
You might think it's easy since we're "in a browseer already", but we're actually not.
All the CardDAV stuff happens in the backend on the server, not in the browser. If you know how to get back and forth between the server and the browser from within a roundcube backend plugin, I'm all ears, but I just don't know how to do it.

Also, as there's the google contacts plugin, I'm not sure it's even necessary.

**Comment by brianjmurrell** [comment]
I thought the google contacts plugin was a one-way "periodic sync" plugin, not an active plugin like rcmcarddav.  I'm not interested in roundcube seeing my google contacts as of up to an hour ago (or whatever the re-sync period is).  I want roundcube to see a contact added by my phone as soon as I add it on my phone.  Anything less than instantaneous is just a constant stream of complaints about "how come contacts are in my phone but no in my e-mail".

As for implementation in PHP, perhaps this will help: https://github.com/google/google-api-php-client

**Comment by blind-coder** [comment]
rcmcarddav also has a cache period, albeit it can be configured to 0.

That being said, if there's a PR for google contacts with OAuth 2.0, I'll be happy to include it, but for now the way to go is to disable OAuth 2.0 for contacts if you want to use it with rcmcarddav.
Personally, I have no intention of programming that myself at the moment.

**Comment by JamesTheAwesomeDude** [comment]
…would App Passwords not be suitable for this?

**Comment by blind-coder** [comment]
> …would App Passwords not be suitable for this?

No idea, what is that?

**Comment by JamesTheAwesomeDude** [comment]
@blind-coder App Passwords are revocable passwords that can be used for devices that don't support 2-step authentication. You create an app password (random 16 character string) and use it to sign in to your Google account on e.g., your phone or your IMAP client that just supports normal user+password login.

https://support.google.com/accounts/answer/185833?hl=en

**Comment by blind-coder** [comment]
Sounds like a good solution, though not within RCMCardDAVs responsibility to create.
Might be viable to think about displaying a helptext somehow, though.

**Comment by JamesTheAwesomeDude** [comment]
Yeah, I was suggesting the App Passwords as something for users to use until (or instead of) OAuth2 being integrated.

A help text, some message reminding the users of the existence of app passwords would indeed be a good idea.

**Comment by brianjmurrell** [comment]
On Tue, 2015-10-27 at 08:13 -0700, James wrote:

> A help text, some message reminding the users of the existence of app
> passwords would indeed be a good idea.

Yeah, telling them how to create/set them, etc.

**Comment by texxasrulez** [comment]
I have my google contacts working with rcmcarddav. Use the url https://www.googleapis.com:443/carddav/v1/principals/your_username@gmail.com/lists/default/
user your Google login creds and it works perfectly read/write.

**Comment by texxasrulez** [comment]
In settings/CardDAV use URL https://www.googleapis.com:443/carddav/v1/principals/YOUR_EMAIL@gmail.com/lists/default/ add your GMail creds and it works perfectly read and write. (for me at least) Great work ...

**Comment by brianjmurrell** [comment]
@texxasrulez Is your suggestion known to be still working?  I seem to be getting failures to update/remove contacts from google.

**Comment by texxasrulez** [comment]
Sorry for delay. Unfortunately, where I moved to recently, the only internet I can get is satellite service, which no self hosting allowed, and my server is not up right now for me to test ....

**Comment by mstilkerich** [comment]
It currently is not necessary to have OAuth to use Google Contacts. Although Basic Auth has been announced as deprecated by Google, they have not yet disabled support for it and postponed the data indefinitely because of COVID-19.
https://gsuiteupdates.googleblog.com/2020/03/less-secure-app-turn-off-suspended.html

The current v4 branch works with Google Contacts and has workarounds for its quirks concerning CardDAV protocol compliance.

**Comment by mstilkerich** [comment]
Closing this as it duplicates #319 and they are essentially the same.
