### ISSUE TITLE
Causing HTTPD to crash

### ISSUE THREAD

**Issue by lantrix** [blind-coder/rcmcarddav#113]
Getting a total bizarre error causing HTTPD to crash on Mac 10.7 server, Roundcube `v1.1.2`.
Totally repeatable - the moment I enable the plugin; crash on trying to login. Disable plugin, works again.

Crashes: `$config['plugins'] = array('markasjunk', 'managesieve', 'disable_advanced_ui', 'carddav');`
Works: `$config['plugins'] = array('markasjunk', 'managesieve', 'disable_advanced_ui');`

System.log shows:

```
Sep  7 16:04:11 server ReportCrash[6858]: Saved crash report for httpd[6785] version ??? (???) to /Library/Logs/DiagnosticReports/httpd_2015-09-07-160411_localhost.crash
Sep  7 16:04:12 server ReportCrash[6858]: Saved crash report for httpd[6793] version ??? (???) to /Library/Logs/DiagnosticReports/httpd_2015-09-07-160412_localhost.crash
```

 A composer update shows:

```
server:carddav root# pwd
/usr/share/webmail/plugins/carddav
server:carddav root# php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)                
Nothing to install or update
Generating autoload files
```

Crash log shows:

```
Process:         httpd [6785]
Path:            /usr/sbin/httpd
Identifier:      httpd
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  httpd [217]

Date/Time:       2015-09-07 16:04:10.851 +0800
OS Version:      Mac OS X Server 10.7.5 (11G63)
Report Version:  9

Crashed Thread:  1  Dispatch queue: com.apple.libdispatch-manager
```

It's stumping me...

**Comment by blind-coder** [comment]
This may be a stupid question, but what's that got to do with RCMCardDAV?

**Comment by lantrix** [comment]
Valid query. I'm trying to install RCMCardDAV; and either it; or a dependency is crashing the web server when I enable it in round cube config. Just wondering if anyone has seen this before.

**Comment by blind-coder** [comment]
Ooof... no, I never saw that one before. But it'd be pretty strange if a simple php script - and RCMCardDAV is nothing but PHP scripts - would crash the webserver.

Unless anyone else looking in here - which is pretty few people - has any idea how to actually trace the error, I'm afraid I can't help you there.

You _could_ try setting the DEBUG and DEBUG_HTTP variables in carddav_common.php to true and check the output in roundcube/logs/carddav to see how far in the process RCMCardDAV actually came.

**Comment by lantrix** [comment]
Thanks. I already enabled DEBUG and DEBUG_HTTP variables but hadn't seen where the output went. I'll check that out first.

**Comment by websafe** [comment]
@lantrix enable error logging in RoundCube (via `.htaccess`) and check if Your problem is related to issue #116 fixed with PR #117

**Comment by lantrix** [comment]
I'll try this out and see how it goes.

**Comment by mstilkerich** [comment]
No update in a long time, closing.
