### ISSUE TITLE
How to get autocomplete_addressbooks working?

### ISSUE THREAD

**Issue by Popyllol** [blind-coder/rcmcarddav#114]
Hi Benjamin,
first of all: Thank you for your great plugin!
It is working just for for my needs.

But... I dropped accidently my configuration a few weeks ago and now I cannot get all features back to work. One of them is autocomplete_addressbooks.

When I look at you source it looks like you add yourself with all addressbooks to the list of autocomplete addressbooks, right? (https://github.com/blind-coder/rcmcarddav/blob/master/carddav.php, Line 142-159)

My config in roundcube is:
```php
$config['address_book_type'] = '';
$config['autocomplete_addressbooks'] = array('');
$config['autocomplete_min_length'] = 3;
$config['addressbook_search_mode'] = 0;
```
In carddav I have a predefined Addressbook for my Owncloud like this:
```php
$prefs['Personal'] = array(
        'carddav_name_only' => true,
        // will be substituted for the roundcube username
        'username'     =>  '%u', 
        // will be substituted for the roundcube password
        'password'     =>  '%p',
        // %u will be substituted for the CardDAV username
        'url'          =>  'https://cloudserver.domain.tld/remote.php/carddav/addressbooks/%u/',
        'active'       =>  true,
        'use_categories' => true,
        'readonly'     =>  true,
        'refresh_time' => '02:00:00',

        'fixed'        =>  array( 'username' ),
        'hide'         =>  false,
);
```
It works fine when I go to the Addressbook in Rouncube I can see all my discovered addressbooks and even the groups! Great!
But the autocompletion fails :-(.

What am I doing wrong?

Greetings from Hamburg,
   Lars

**Comment by Popyllol** [comment]
Forgot some things:
- OS: Ubuntu Ubuntu 14.04.3 LTS
- PHP 5.5.9
- Roundcube Webmail 1.1.1 (from https://launchpad.net/ubuntu/+source/roundcube/1.1.1+dfsg.1-2/)
- carddav 1.1.0 (fresh from git a few minutes ago)

Do you need anything else?

**Comment by blind-coder** [comment]
Hi Lars.

Sorry for the late reply.
Is there anything in the logfiles of roundcube or the webservers error log?
If not, try to enable DEBUG and DEBUG_FALSE in carddav_common.php and check roundcube/logs/carddav for any messages.

**Comment by Popyllol** [comment]
Hi Benjamin,
after tunring on debugging I can see a lot of updating staff after I log into Roundcube but at the moment where the address auto completion should start (after three or more characters) there is nothing in the log.
Any further debugging switches to switch on?
Thank you,
   Lars

**Comment by blind-coder** [comment]
Not in my scripts, no.
You can try to enable your browser javascript console, see if there's any activity going on and/or any errors in there.
Never seen this behaviour before, tbh, but I also never disabled the integrated addressbook, either.

**Comment by Popyllol** [comment]
Thank you Benjamin!
I haven't fixed the problem but now it seems that is has nothing to do with your carddav :-).

The error in the console shows:
Uncaught TypeError: tinymce.util.XHR.on is not a functionrcube_text_editor @ editor.min.js?s=1442309462:32editor_init @ app.min.js?s=1442309456:271init @ app.min.js?s=1442309456:46(anonymous function) @ ?_task=mail&_action=compose&_id=15921001455f7da677def7:350jQuery.Callbacks.fire @ jquery.min.js:1075jQuery.Callbacks.self.fireWith @ jquery.min.js:1193jQuery.extend.ready @ jquery.min.js:435DOMContentLoaded @ jquery.min.js:949

So the error is a way before your code is called.
You can close this issue.
Thank you,
   Lars

**Comment by Popyllol** [comment]
Maybe I hit this bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785333

**Comment by blind-coder** [comment]
Ah, great. Well, not great, but happy it's not my code :-)

**Comment by Popyllol** [comment]
Upgraded to Roundcube 1.1.3 from  https://downloads.sourceforge.net/project/roundcubemail/roundcubemail/1.1.3/roundcubemail-1.1.3-complete.tar.gz
and my problem is gone... your code is fine :-).
