### ISSUE TITLE
/vendor/autoload.php missing

### ISSUE THREAD

**Issue by freaknils** [blind-coder/rcmcarddav#115]
The file an the directory
```require_once __DIR__ . '/vendor/autoload.php';```
in carddav_common.php:22 is missing.
Is there an issue with the merging?

**Comment by blind-coder** [comment]
Did you read and follow the INSTALL?
https://github.com/blind-coder/rcmcarddav/blob/master/INSTALL#L9

**Comment by freaknils** [comment]
Yes I dit, but where is #L9 you are linking to?

**Comment by blind-coder** [comment]
That is Line 9 where it says to run php composer.phar install in the RCMCardDAV directory. It creates the vendor/autoload.php file.

**Comment by freaknils** [comment]
Ohh sorry, everythink is working well now. Thanks!
