### ISSUE TITLE
Function array dereferencing - PHP Parse error:  syntax error, unexpected '[' in .../plugins/carddav/carddav_backend.php on line 1783

### ISSUE THREAD

**Issue by websafe** [blind-coder/rcmcarddav#116]
Hello @blind-coder,

enabling `carddav` on a server running `PHP 5.3.27` will make RC unusable:

~~~~
PHP Parse error:  syntax error,
unexpected '[' in .../plugins/carddav/carddav_backend.php on line 1783
~~~~

The problematic line:

~~~~ php
$save_data = $this->create_save_data_from_vcard("$vcfstr")['save_data'];
~~~~

because `Function array dereferencing has been added, e.g. foo()[0]`
was added in PHP **5.4.x** http://php.net/manual/en/migration54.new-features.php

I'll post a quick fix in a few minutes.

**Comment by emtiu** [comment]
I can confirm the issue, and confirm that #117 fixes it.
