### ISSUE TITLE
When listing a contacts group, the list box header <h2> is empty (and displays wrong)

### ISSUE THREAD

**Issue by emtiu** [blind-coder/rcmcarddav#120]
I have a carddav address book with a group in it. I can list the members of the group by clicking on it, and they will be listed in the contacts box on the "Address Book" page of Roundcube.

But in that listing, the h2 element #aria-label-contactslist (child of #addresslist) is empty. This breaks the box header display.

For groups within the built-in address book, this does not happen. Instead, #aria-label-contactslist then contains the name of that group.

I think this has to do with roundcube's way of displaying groups, as controlled in the list_contacts function at line 4842 of program/js/app.js in Roundcube 1.1.3. Unfortunately, I'm not able to pursue the root of the problem further.

**Comment by blind-coder** [comment]
This should now be fixed in latest master commit. Can you please check it?

**Comment by emtiu** [comment]
I can confirm that this is fixed in the latest master. Thank you!
