### ISSUE TITLE
Enabling carddav plugin results in non-functioning roundcube

### ISSUE THREAD

**Issue by DigiAngel** [blind-coder/rcmcarddav#122]
Topic says it...I've created config.inc.php in the plugins dir and enabled it.  After enabling I get a blank screen when going to roundcube.  Disabling the plugin restores functionality.  I get this with both the composer install and with the latest git.  Is there a log setting I can check to troubleshoot?  Thank you.

**Comment by glagolster** [comment]
This is the same behaviour as I also reported in my roundcube freshup. I tried several procedures to setup but a working round cube, I only have, when I turn of carddav.

With manual import, I got the following error message: " PHP Fatal error:  Class 'Httpful\Bootstrap' not found in /usr/share/roundcube/plugins/carddav/carddav_common.php on line 24"

I updated the carddav_common.php with the githup update but I had no success.

I tried to instal via the composer and the result was, that the plugin was working bit when I tried to access mail, I can only see the header. When I try to open a mail, I ran into a loop.

**Comment by DigiAngel** [comment]
And I'm seeing:
~~~
PHP Warning:  require_once(/var/www/html/roundcubemail/plugins/carddav/vendor/autoload.php):
~~~
That directory doesn't exist...I don't see it in the master here either...thoughts on this?

**Comment by DigiAngel** [comment]
And after symlinking /var/www/html/roundcubemail/vendor in the carddav plugin dir now I get:
~~~
07-Nov-2015 06:43:47 -0700]: <ikkeb618> DB Error: [1] no such table: carddav_addressbooks (SQL Query: SELECT id FROM carddav_addressbooks WHERE user_id='1' AND active=1) in /var/www/html/roundcubemail/program/lib/Roundcube/rcube_db.php on line 543 (GET /roundcubemail/?_task=mail&_mbox=INBOX)
[07-Nov-2015 06:43:47 -0700]: <ikkeb618> DB Error: [1] no such table: carddav_addressbooks (GET /roundcubemail/?_task=mail&_mbox=INBOX)
~~~

Not sure what to do next here...I'm not using mysql I'm using sqllite.

**Comment by DigiAngel** [comment]
And after reading the README in the dir:

~~~
The configuration is done in the Settings Dialogue in the webfrontend, thanks to Dirk who submitted a patch to FS#3
	http://bugs.crash-override.net/index.php?do=details&task_id=3
~~~

and removing my config.dist.php, I get:
~~~
07-Nov-2015 07:02:26 -0700]: <15ttt8nv> PHP Error: Failed to load plugin file /var/www/html/roundcubemail/plugins/cardav/cardav.php in /var/www/html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php on line 198 (GET /roundcubemail/?_task=logout&_token=f181ff867b0690068c38888e985d46e1)
[07-Nov-2015 07:02:31 -0700]: <15ttt8nv> PHP Error: Failed to load plugin file /var/www/html/roundcubemail/plugins/cardav/cardav.php in /var/www/html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php on line 198 (POST /roundcubemail/?_task=login?_task=login&_action=login)
[07-Nov-2015 07:02:31 -0700]: <k8htp4hk> PHP Error: Failed to load plugin file /var/www/html/roundcubemail/plugins/cardav/cardav.php in /var/www/html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php on line 198 (GET /roundcubemail/?_task=mail)
[07-Nov-2015 07:02:32 -0700]: <k8htp4hk> PHP Error: Failed to load plugin file /var/www/html/roundcubemail/plugins/cardav/cardav.php in /var/www/html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php on line 198 (GET /roundcubemail/?_task=mail&_refresh=1&_mbox=INBOX&_remote=1&_unlock=loading1446904952195&_action=list&_=1446904952009)
[07-Nov-2015 07:02:32 -0700]: <k8htp4hk> PHP Error: Failed to load plugin file /var/www/html/roundcubemail/plugins/cardav/cardav.php in /var/www/html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php on line 198 (GET /roundcubemail/?_task=mail&_remote=1&_unlock=0&_action=getunread&_=1446904952010)
~~~

I would submit that this plugin is broken in it's current state when working with 1.1.3.

**Comment by DigiAngel** [comment]
And lastly..I got this to work by moving my config.inc.php back, and by merging the 000-dbinit/sqlite3.sql into my current sqlite.db.  So in summary this is what it took to get this to work:

~~~~
1.  symlink roundcubemail/vendor into the plugins/carddav dir
2.  manually create the config.inc.php
3.  merge sqlite3.sql into sqlite3.db (cat plugins/carddav/dbmigrations/0000-dbinit/sqlite3.sql | sqlite3 sqlite.db
~~~

I now though have a ton of:
~~~
[07-Nov-2015 07:15:48 America/Boise] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/html/roundcubemail/plugins/carddav/carddav_backend.php on line 1438
~~~
 
in the error log, so going to look into that now.

**Comment by blind-coder** [comment]
Sorry for not replying sooner.

So this happens for you when using sqlite backend on 1.1.3? I will try to replicate this.

**Comment by DigiAngel** [comment]
Thank you.  So...just enabling carddav in Roundcube's config.in.php gives errors with:
~~~
[07-Nov-2015 07:02:32 -0700]: <k8htp4hk> PHP Error: Failed to load plugin file /var/www/html/roundcubemail/plugins/cardav/cardav.php in /var/www/html/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php on line 198 (GET /roundcubemail/?_task=mail&_remote=1&_unlock=0&_action=getunread&_=1446904952010)
~~~

So I had to configure manually as above shown in the three step process.  I imagine that maybe if the above error was fixed a person would be able to configure it.  I hope that makes sense.

**Comment by tweippert** [comment]
On an fresh installation with composer install,i had the same issues with an mysql backend. Linking vendor to the carddav plugin seems to fix this.

Maybe an quick fix for the array issue, i think $type isn't set correctly, maybe just test if $type is not null like these:

diff --git a/carddav_backend.php b/carddav_backend.php
index 339bc2e..7f2fba1 100644
--- a/carddav_backend.php
+++ b/carddav_backend.php
@@ -1435,13 +1435,15 @@ EOF
                        foreach($pvalue['TYPE'] as $type)
                        {
                                $type = strtolower($type);
-                               if( in_array($type, $this->coltypes[$attrname]['subtypes']) )
-                               {
-                                       $fallback = $type;
-                                       if(!(is_array($this->fallbacktypes[$attrname])
-                                               && in_array($type, $this->fallbacktypes[$attrname])))
+                               if ( $type ) {
+                                       if( in_array($type, $this->coltypes[$attrname]['subtypes']) )
                                        {
-                                               return $type;
+                                               $fallback = $type;
+                                               if(!(is_array($this->fallbacktypes[$attrname])
+                                               && in_array($type, $this->fallbacktypes[$attrname])))
+                                               {
+                                                       return $type;
+                                               }
                                        }
                                }
                        }

**Comment by blind-coder** [comment]
Edited your comment with syntax highlighting there.

Also, can you try latest master? I merged a PR yesterday that addresses an issue with composer installs.

**Comment by tweippert** [comment]
I have used dev-master from roundcube plugins, think it uses latest master,or?
With this i needed the alias and additional the patch .....

**Comment by glagolster** [comment]
In my matter, maby the same reason, I made some further tests. The result first, I have to decide what I want. Running mail or running contacts.

First I installed cardav via composer the I had the following error message.

PHP Fatal error:  Call to undefined method libcalendaring::parse_alaram_value() in /usr/share/roundcube/plugins/calendar/calendar.php on line 698

Then I updated the libcalendaring again, via composer and the new error message is

 PHP Fatal error:  Class vobject_location_property contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Sabre\VObject\Property::getValueType, Sabre\VObject\Property::setRawMimeDirValue, Sabre\VObject\Property::getRawMimeDirValue) in /usr/share/roundcube/plugins/libcalendaring/libvcalendar.php on line 1340

**Comment by Musashi69** [comment]
Got that error message about vobject_location_property from my install here, too,
I'm using a Kolab 3.4 installation here, but with updated versions of libcalendaring and stuff. Upon installing carddav-plugin from this repo today I got this error, leaving the installation useless.
After removing '"roundcube/carddav": "dev-master"' from composer.json and running composer.phar again everything went back to normal.

**Comment by rutkas** [comment]
I also have in the logs:
PHP Warning:  in_array() expects parameter 2 to be array, null given in /../htdocs/plugins/
carddav/carddav_backend.php on line 1438
but the plugin seems to be working

**Comment by rutkas** [comment]
and... In the case when I login with the user that does not have carddav account in baikal (some users do not need them) I have two new error lines:

PHP Warning:  dns_get_record(): An unexpected server failure occurred. in /../htdocs/plugins/carddav/carddav_discovery.php on line 252
PHP Warning:  Invalid argument supplied for foreach() in /../htdocs/plugins/carddav/carddav_discovery.php on line 253

**Comment by blind-coder** [comment]
@glagolster @Musashi69 RCMCardDAV doesn't work with kolabs calendar plugin as both use incompatible versions of VObject.

@rutkas Thanks for the notice. Those are warning messages that can be ignored, but I'll see if I can catch them correctly.

All of you: please do not hijack issues.

**Comment by glagolster** [comment]
I habe the Kolab calendar plug-in with Caldav support in use and it looks pretty much. Not so good as with old myroundcube plug-in I had but it is good enough for me. 

Therefore I have to thank you. ☺

**Comment by mstilkerich** [comment]
Closing this issue as it has not been updated in a long time and appears to be resolved. If you are still affected, please leave a comment / reopen the issue.
