### ISSUE TITLE
Importing/Copying vCard with Notes and Birthday not working

### ISSUE THREAD

**Issue by cweilguny** [blind-coder/rcmcarddav#124]
The notes and birthday field seem to be lost when importing a contact from a CSV file or a vCard 3.0 file, or when a contact is moved from the default personal roundcube addressbook over to a CardDAV addressbook.

Easiest way to reproduce the bug: Create a contact in the default personal addressbook, with notes or birthday field set. Save the contact. Move it over to a CardDAV addressbook by dragging with the mouse. The contact will be moved, but the notes and birthday field is gone.

Tested in: Roundcube 1.1.3, CardDAV Plugin (1.1.0, commit 54d3aaa).

**Comment by lx-s** [comment]
This problem still persists with current master and RC 1.3.0.

**Comment by lx-s** [comment]
I noticed PHP warning messages in the logs of the "string expected - array given"-type in carddav_backend, Line 1327 https://github.com/blind-coder/rcmcarddav/blob/ad01ef9464b0b3aad52d9e51895a49475a12a76a/carddav_backend.php#L1327 und Line 1354 https://github.com/blind-coder/rcmcarddav/blob/ad01ef9464b0b3aad52d9e51895a49475a12a76a/carddav_backend.php#L1354

I've tested to patch these lines like this (note the `[0]`):

```
1327-1328:
		if (array_key_exists($key, $save_data) && strlen($save_data[$key][0])>0) {
			$val = rcube_utils::strtotime($save_data[$key][0]);
1354:
  		if (strlen($save_data[$rckey][0]) > 0) {
```

After making these changes, importing contacts also imported their birthday- spouse, etc. -fields and also notes.

**Comment by blind-coder** [comment]
@lx-s Unfortunately that breaks editing an object. With that fix I can't manually edit the birthday anymore. Probably needs a check for both with `[0]` and without.

**Comment by lx-s** [comment]
Maybe?
```
if (array_key_exists($key, $save_data) {
  $keyData = (is_array($save_data[$key])) ?  $save_data[$key][0] : $save_data[$key];
  if (strlen($keyData) > 0) {

  }
```

**Comment by lx-s** [comment]
Created a PR. Guess it's a better place to discuss whether this change actually makes sense or not ;)

**Comment by mstilkerich** [comment]
Issue fixed
