### ISSUE TITLE
Enabling carddav plugin gives empty Webpage

### ISSUE THREAD

**Issue by sut12** [blind-coder/rcmcarddav#126]
Hello,

I am on the latest rc (1.1.3) with php (PHP Version 5.4.45-0+deb7u2) when i enable carddav plugin the roundcube webpage is empty. The Log File shows the following entry:

Class 'Httpful\Bootstrap' not found in /var/wwwssl/mail/plugins/carddav/carddav_common.php on line 20
(Line maybe wrong -  i tried some stuff)

Can anybody help me? I really need to get carddav to work.

**Comment by blind-coder** [comment]
Did you install the dependencies with composer?

**Comment by sut12** [comment]
Thank you for the reply. I am sorry. I read the Install notes but it was not clear for me to do this step. After installing the dependencies i get an database error. (Table 'roundcubemail.carddav_addressbooks' doesn't exist)

Of course i need to run the SQL Update for initialising the needed tables. Which SQL Script should i run?

0000-dbinit/mysql.sql has TABLE_PREFIX in the create statement. I think i dont have any table prefix. Should i just remove it?

**Comment by blind-coder** [comment]
The database is initialised when you log in to roundcube, so if you have been logged in already, please log out and back in.

**Comment by sut12** [comment]
THANK YOU!

I had some old tables from another old carddav plugin. Deleted them and did a fresh logon. 
Works like a charm now! Sorry for my ignorance.

**Comment by blind-coder** [comment]
It's cool. Great that it works now :-)
