### ISSUE TITLE
Class 'Httpful\Bootstrap' not found

### ISSUE THREAD

**Issue by texxasrulez** [blind-coder/rcmcarddav#130]
I enable ;this plugin and get the following error .. 

PHP Fatal error:  Class 'Httpful\Bootstrap' not found in /path_to_roundcube/plugins/carddav/carddav_common.php on line 25

I have a fresh install of RC 1.1.4. I only enabled carddav plugin for testing. 

Thank you.

**Comment by blind-coder** [comment]
Did you follow the INSTALL file and installed the dependencies via composer?

**Comment by texxasrulez** [comment]
Yes. I installed per the INSTALL file along with dependencies

**Comment by texxasrulez** [comment]
I found the issue. I had a typo, sorry to waste anyone's time ..

**Comment by blind-coder** [comment]
Glad to hear it works :-)
