### ISSUE TITLE
escaped commas in categories

### ISSUE THREAD

**Issue by c-schwamborn** [blind-coder/rcmcarddav#133]
rcmcarddav escapes the commas in categories when it stores the vcard to the Server like this:
CATEGORIES:cata\,catb\,catc\r
This doesn't matter if nothing else touches those contacts, but if other clients modifies these, some curious things happen - a new category 'cata,catb,catc' appeared. No other client I tried does that (except one - tb plugin cardbook - which behaved the same way) and I couldn't find anything about escaping commas (\,) in the rfc.
This phenomenon and the results might also depend on the used cal/carddav server.
Some servers seem to validate/autocorrect the vcards ahead of storing them, others just take the vcard as the client delivers it.

Cheers, Christian

**Comment by blind-coder** [comment]
I'll look into this.

**Comment by mstilkerich** [comment]
Hello,

  first excuse the very late reply. This issue is fixed in the meantime, I just tried with the v4 development branch.

I'm closing the issue, however, if you still encounter problems with the current (v4 branch) plugin, please comment/reopen.
