### ISSUE TITLE
group/category compatibility with apple products

### ISSUE THREAD

**Issue by c-schwamborn** [blind-coder/rcmcarddav#134]
This is not a bug, more something for the whishlist.
The apple users around me bugged me why they don't see their groups in the roundcube address book. The answer is quite simple:
Apple uses some special vcard to store it's group information on an carddav server. They look like normal vcards with N and FN containing the group name and two special properties :

X-ADDRESSBOOKSERVER-KIND:group
X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:d4c1baf6-f603-4fb5-8f19-d45eb1e7fb23

The second prop can be used multiple times containing a reference to the contacts belonging to that group.
There is a good intro to this topic in the first answer on this site:
http://stackoverflow.com/questions/24202551/manipulate-groups-in-icloud-with-carddav-protocol
If this is part of vcard 4 standard, more clients might follow this approach. To be compatible with various clients, it might be useful to store both, those group collections and categories within the vcards

Cheers, Christian

**Comment by mstilkerich** [comment]
Hi Christian,

  this is exactly what the option "Use modern group mechanism (you will lose old RCMCardDAV groups!)" does, i.e. the "old RCMCardDAV groups" is the X-ADDRESSBOOKSERVER-KIND extension.

**Comment by c-schwamborn** [comment]
Thank you for the info,

I suspected that much, but I started my tests with a current version 
with an old config including a pre configured address book. It looks 
like in pre configured address books this doesn't work, creating an 
address book with "'use_categories' => true;" in it's config leads in 
fact to an address book where in the settings front end "Use modern 
group mechanism" is set to active, but it still creates old group entry's.
Is it possible, that the setting does the opposite?
I created two new addressbooks, one with old groups, one with new ones. 
The entrys in the one with old groups ends up with the new schema and 
the one which is supposed to have the new schema has in fact old categories.
Also something seems wrong with the group vcard. Within the rc address 
book both contacts are shown in the group 'a1', but in the servers db 
only the last added contact is referenced:

BEGIN:VCARD\r
VERSION:3.0\r
PRODID:-//Sabre//Sabre VObject 3.4.2//EN\r
UID:63BA4833-5CE5-4888-839D-21B2A5E2B570\r
N:gruppe;alt1;;;\r
FN:alt1 gruppe\r EMAIL;TYPE=home:alte1@gruppe.priv\r
REV:20160120T131533Z\r
END:VCARD\r

BEGIN:VCARD\r VERSION:3.0\r
PRODID:-//Sabre//Sabre VObject 3.4.2//EN\r
UID:52A079D5-5884-4AF9-9367-6BF82251838B\r
N:gruppe;alt2;;;\r
FN:alt2 gruppe\r
EMAIL;TYPE=home:alte2@gruppe.priv\r
REV:20160120T131201Z\r END:VCARD\r

BEGIN:VCARD\r
VERSION:3.0\r
PRODID:-//Sabre//Sabre VObject 3.4.2//EN\r
UID:986D6D27-B37D-425F-8A7C-DE10E04155C2\r
N:a1;;;;\r
FN:a1\r
X-ADDRESSBOOKSERVER-KIND:group\r
X-ADDRESSBOOKSERVER-MEMBER:urn:uuid:52A079D5-5884-4AF9-9367-6BF82251838B\r
REV:20160120T131542Z\r
END:VCARD\r


Supplemental:
would it be possible to support both, categories in the contacts and the 
new group vcards at the same time to be compatible with new and old clients?

**Comment by mstilkerich** [comment]
Hello,

  in the current development branch v4, the two types of groups are transparently supported to the possible extent.

That means, that both CATEGORIES and VCard based groups retrieved from the server will be displayed as groups in roundcube, any changes to those groups will be done based on the groups type. The only difficulty that remains is what kind of group is created when a new group is created in roundcube. This is the only meaning left for the config switch of the group type. Furthermore, this setting can now be changed anytime without having to delete/recreate an addressbook.
