### ISSUE TITLE
infinite loop in retrieve_addressbooks

### ISSUE THREAD

**Issue by Fneufneu** [blind-coder/rcmcarddav#143]
Hi,

There is an infinite loop in retrieve_addressbooks() if $additional_urls contain itself.
It happend on my CardDAV server if the account does not have any Contacts folder.

i  made an uggly patch to fix the issue, with (string) because $other is a SimpleXMLElement

```
diff --git a/carddav_discovery.php b/carddav_discovery.php
index 3641fa0..8d0cd11 100644
--- a/carddav_discovery.php
+++ b/carddav_discovery.php
@@ -26,6 +26,7 @@ require_once("carddav_common.php");
 class carddav_discovery
 {
        private static $helper;
+       private $tried_url = array();

        /**
         * Determines the location of the addressbook for the current user on the
@@ -100,6 +101,9 @@ class carddav_discovery

        private function retrieve_addressbooks($path, $cdfopen_cfg, $recurse=false)
        {{{
+       if (in_array((string)$path, $this->tried_url))
+               return false;
+       $this->tried_url[] = (string)$path;
        $baseurl = $cdfopen_cfg['url'];
        $url = carddav_common::concaturl($baseurl, $path);
        $depth = ($recurse ? 1 : 0);
@@ -167,6 +171,8 @@ EOF
                }

                foreach($additional_urls as $other_url) {
+                       if (in_array((string)$other_url, $this->tried_url))
+                               continue;
                        self::$helper->debug("Searching additional URL: $other_url");
                        if(strlen($other_url) <= 0) continue;

```

**Comment by gizmo15** [comment]
I have the same thing.

the plugin try to get the contacts and never stop.

The only way to stop that: desactivate the plugin :/

**Comment by ohmer1** [comment]
I had the same problem when an user tried to login to roundcube while the user didn't had an initialized carddav address book in Nextcloud 15.

The patch proposed by @Fneufneu was very useful. I did modify it a bit to improve it. The original patch made the plugin to make 20 http requests to the carddav server while my edit reduces it to 12 (this improve login time). I'm sure there is still place to improvements because there is still duplicated requests as you can see with this log coming from my carddav server:

> 10.1.1.1 - - [11/Apr/2019:13:34:09 -0400] "PROPFIND /remote.php/dav/addressbooks/users/myuser/contacts/ HTTP/1.1" 401 5566 "-" "RCM CardDAV plugin/3.0.3" t:32046
> 10.1.1.1 - myuser [11/Apr/2019:13:34:10 -0400] "PROPFIND /remote.php/dav/addressbooks/users/myuser/contacts/ HTTP/1.1" 404 5543 "-" "RCM CardDAV plugin/3.0.3" t:313436
> 10.1.1.1 - - [11/Apr/2019:13:34:10 -0400] "PROPFIND /.well-known/carddav HTTP/1.1" 301 4436 "-" "RCM CardDAV plugin/3.0.3" t:506
> 10.1.1.1 - - [11/Apr/2019:13:34:10 -0400] "PROPFIND /.well-known/carddav HTTP/1.1" 301 4436 "-" "RCM CardDAV plugin/3.0.3" t:335
> 10.1.1.1 - - [11/Apr/2019:13:34:10 -0400] "PROPFIND /remote.php/dav/ HTTP/1.1" 401 5568 "-" "RCM CardDAV plugin/3.0.3" t:25037
> 10.1.1.1 - myuser [11/Apr/2019:13:34:10 -0400] "PROPFIND /remote.php/dav/ HTTP/1.1" 207 5900 "-" "RCM CardDAV plugin/3.0.3" t:307543
> 10.1.1.1 - - [11/Apr/2019:13:34:11 -0400] "PROPFIND /remote.php/dav/principals/users/myuser/ HTTP/1.1" 401 5574 "-" "RCM CardDAV plugin/3.0.3" t:30912
> 10.1.1.1 - myuser [11/Apr/2019:13:34:11 -0400] "PROPFIND /remote.php/dav/principals/users/myuser/ HTTP/1.1" 207 6293 "-" "RCM CardDAV plugin/3.0.3" t:306227
> 10.1.1.1 - - [11/Apr/2019:13:34:12 -0400] "PROPFIND /remote.php/dav/addressbooks/users/myuser/ HTTP/1.1" 401 5568 "-" "RCM CardDAV plugin/3.0.3" t:30518
> 10.1.1.1 - myuser [11/Apr/2019:13:34:12 -0400] "PROPFIND /remote.php/dav/addressbooks/users/myuser/ HTTP/1.1" 207 5980 "-" "RCM CardDAV plugin/3.0.3" t:311867
> 10.1.1.1 - - [11/Apr/2019:13:34:12 -0400] "PROPFIND / HTTP/1.1" 405 5235 "-" "RCM CardDAV plugin/3.0.3" t:40310
> 10.1.1.1 - - [11/Apr/2019:13:34:12 -0400] "PROPFIND / HTTP/1.1" 405 5235 "-" "RCM CardDAV plugin/3.0.3" t:37513

This is my edited patch:

```patch
--- plugins/carddav/carddav_discovery.php.orig	2019-04-11 13:04:13.805452883 -0400
+++ plugins/carddav/carddav_discovery.php	2019-04-11 13:33:39.749677168 -0400
@@ -26,6 +26,7 @@
 class carddav_discovery
 {
 	private static $helper;
+	private $tried_url = array();
 
 	/**
 	 * Determines the location of the addressbook for the current user on the
@@ -101,7 +102,11 @@
 	private function retrieve_addressbooks($path, $cdfopen_cfg, $recurse=false)
 	{{{
 	$baseurl = $cdfopen_cfg['url'];
-	$url = carddav_common::concaturl($baseurl, $path);
+	$url = str_replace(':443', '', carddav_common::concaturl($baseurl, $path));
+	if (in_array($url, $this->tried_url)) {
+		return false;
+	}
+	$this->tried_url[] = str_replace(':443', '', $url);
 	$depth = ($recurse ? 1 : 0);
 	self::$helper->debug("SEARCHING $url (Depth: ".$depth.")");
 
@@ -167,6 +172,10 @@
 		}
 
 		foreach($additional_urls as $other_url) {
+			$other_url = str_replace(':443', '', (string)$other_url);
+			if (in_array($other_url, $this->tried_url)) {
+				continue;
+			}
 			self::$helper->debug("Searching additional URL: $other_url");
 			if(strlen($other_url) <= 0) continue;

```

**Comment by mstilkerich** [comment]
This issue is fixed in the v4 branch, which uses a less iterative discovery implementation:
https://github.com/blind-coder/rcmcarddav/tree/v4

If this does not fix the issue for you, please comment / reopen on the issue.
