### ISSUE TITLE
Changing default DB ?

### ISSUE THREAD

**Issue by sapiens-sapide** [blind-coder/rcmcarddav#145]
Hi, 
how could I config the plugin not to use the default rc DB, but the addressbooks DB ?
I've set up my roundcube so each user has a personal DB for his/her addressbooks, not the default rc DB. I'd like that rcmcarddav use the personal DB also.

Thanks,
Stan.

**Comment by blind-coder** [comment]
I'm not sure what you want to achieve.
Since rcmcarddav runs in the Roundcube context, it's also using its database, but seperate tables. Can you post an example of your desired setup?

**Comment by sapiens-sapide** [comment]
I've disabled `$config['address_book_type']` in rouncube's config.inc.php and I wrote a custom plugin to create a different addressbook for each user. `rcube_contacts` object is created from my plugin.
rcmcarddav plugin calls `rcmail::get_instance()->db` to store its tables. 
I'd like rcmcarddav to use `rcube_contacts` address book object to stores its tables.

**Comment by blind-coder** [comment]
Short of rewriting all instances calling rcmail::get_instance()->db to use rcube_contacts instead, I don't see a way to achieve that.

**Comment by sapiens-sapide** [comment]
:-(

**Comment by mstilkerich** [comment]
The use case for this request is not clear to me. Closing as this issue is quite old.
