### ISSUE TITLE
unhandled Error when importing vcards from Google

### ISSUE THREAD

**Issue by sapiens-sapide** [blind-coder/rcmcarddav#146]
Hello,
I've setup rcmcarddav to my roundcube testing environment. I'm trying to import an addressbook that has been previously exported from google. I'm using the roundcube interface to select my contacts.vcf file.
The import failed due to a carddav_backend error : 
`PHP Warning:  strlen() expects parameter 1 to be string, array given in /…………/plugins/carddav/carddav_backend.php on line 1319`

Any clue to handle this error ?
Thanks,
Stan.

**Comment by blind-coder** [comment]
Which version are you on? Line 1319 in that file is a } and that's very surely not the cause of a strlen error.

**Comment by sapiens-sapide** [comment]
Excuse me, I'm on last version (1.1.0). Here is the faulty code : (strlen in 4th line)

    // process all simple attributes
	foreach ($this->vcf2rc['simple'] as $vkey => $rckey){
		if (array_key_exists($rckey, $save_data)) {
			if (strlen($save_data[$rckey]) > 0) {
				$vcf->{$vkey} = $save_data[$rckey];
			} else { // delete the field
				unset($vcf->{$vkey});
			}
		}
	}

**Comment by blind-coder** [comment]
Can you please try the latest master branch from git? There's been leaps and bounds of dev in there and that might already be fixed.

**Comment by sapiens-sapide** [comment]
That's it. Lines shifted because of I added `rcube::console`.

**Comment by mstilkerich** [comment]
Issue was resolved.
