### ISSUE TITLE
Carddav - RoundcubeHome path changed?

### ISSUE THREAD

**Issue by jedufa** [blind-coder/rcmcarddav#147]
Hey Benjamin,

Great work for the synology plugin for carddav, can't live without it!!

 

It seems that in the last update of the Syn, they have changed the following paths:

from: RoundcubeHome=/var/packages/MailStation/target/roundcubemail

to: RoundcubeHome=/var/packages/MailStation/target/mail

 
 

which results in a installation/running failure.

 

I have tried to change the path in the SPK file directly, but then the synology sees the package as invalid after the change and won't load it. Probably because of the checksum?

Do you have a way for me to fix this? Do you think I can just recalculate a checksum?

Thanks in advance,

Jeff

**Comment by blind-coder** [comment]
Hi Jeff.

I don't maintain the Synology package (and I don't have a Synology, either). 
You should report that here: https://sourceforge.net/projects/carddavforsynologymailstation/

**Comment by jedufa** [comment]
Sorry mate, I thought you did that package.
Thanks,
Jf

On 10 April 2016 10:26:13 CEST, Benjamin Schieder <notifications@github.com> wrote:
>Hi Jeff.
>
>I don't maintain the Synology package (and I don't have a Synology,
>either). 
>You should report that here:
>https://sourceforge.net/projects/carddavforsynologymailstation/
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/147#issuecomment-207942992

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
