### ISSUE TITLE
Carrdav and calendar issue

### ISSUE THREAD

**Issue by kuzevanoff** [blind-coder/rcmcarddav#148]
is it way to have no conflict ?
I have this error:

Class vobject_location_property contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Sabre\VObject\Property::getValueType, Sabre\VObject\Property::setRawMimeDirValue, Sabre\VObject\Property::getRawMimeDirValue) in /usr/share/roundcubemail/plugins/libcalendaring/libvcalendar.php on line 1340

**Comment by blind-coder** [comment]
Currently, rcmcarddav and the kolab celandar plugin are not compatible.
You can try this: https://twitter.com/Faster_IT/status/706888278243467264
