### ISSUE TITLE
Httpful\Bootstrap not found

### ISSUE THREAD

**Issue by githare** [blind-coder/rcmcarddav#149]
PHP 5.6.20
MySQL 5.5.44
Roundcube 1.1.5

I've installed httpful and sabre dependencies via composer, but I always get this message whenever I activate this carddav plugin:
`PHP Fatal error:  Class 'Httpful\Bootstrap' not found in /var/www/webmail/plugins/carddav/carddav_common.php on line 25`
I've searched a few hours on the net but can't find a solution.
Is this plugin working for someone with roundcube 1.1.5?

**Comment by blind-coder** [comment]
Did you install rcmcarddav via composer, too?

**Comment by arno-github** [comment]
Not sure. I've made so many tries I don't remember, and it's the first time I install roundcube, so many things are new for me...
Is there a way to check if it was installed via composer?
If not, what are the steps to undo and redo correctly, please?

**Comment by blind-coder** [comment]
If you downloaded and ran composer.phar from the command line, then you'd have used composer, otherwise it's a manual process.
See Step 2 here for composer, that's the recommended way for git clones:
https://github.com/blind-coder/rcmcarddav/blob/master/INSTALL

**Comment by mrjoel** [comment]
I'm having the same issue with upgrade to 1.2.0, I do not user composer, but manual git clone into the plugin directory, is additional setup required?

**Comment by blind-coder** [comment]
Yes, you need the proper versions of httpful and sabredavs vobject classes. See this file https://github.com/blind-coder/rcmcarddav/blob/master/composer.json for the respective version numbers.

**Comment by arno-github** [comment]
`php composer.phar update`
Key require is a duplicate in ./composer.json at line 35
Loading composer repositories with package information
Updating dependencies (including require-dev)                
Nothing to install or update
Generating autoload files

**Comment by mstilkerich** [comment]
I'm closing this issue because of its age. If you are still interested, please try installing the v4 branch following the instructions on: https://github.com/blind-coder/rcmcarddav/tree/v4

If you still have issues with that, please comment / reopen and I will help.
