### ISSUE TITLE
blank page after setup

### ISSUE THREAD

**Issue by Happyfeet01** [blind-coder/rcmcarddav#150]
the installation of this Plugin works. But when i enter my Account details for the cardav adressbook and press enter i get an Black page from the carddav page. 

adressbook on owncloud: https://domain.tld/remote.php/dav/addressbooks/users/Lars/Telefon/

with debugging i get following at the server:

Chromebrowser Log:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Server Log:

DISCOVERY: (cdfopen) retrieve_addressbooks requesting https://domaint.tld:443/remote.php/dav/addressbooks/users/Lars/Telefon/ [RL 5]

can you help me?

![roundcube_carddav](https://cloud.githubusercontent.com/assets/3295104/15025640/82aa8636-123a-11e6-9c73-b8cf79d75d69.png)

**Comment by blind-coder** [comment]
How did you install rcmcarddav? Via composer or manually?

**Comment by dbielz** [comment]
Same issue here. A look into the errorlog in roundcube/logs/ shows these entries for each tried submit:
`[24-May-2016 09:57:30 Europe/Berlin] PHP Warning:  dns_get_record(): An unexpected server failure occurred. in /var/www/roundcubemail-1.2.0/plugins/carddav/carddav_discovery.php on line 252
[24-May-2016 09:57:30 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcubemail-1.2.0/plugins/carddav/carddav_discovery.php on line 253
[24-May-2016 09:57:30 Europe/Berlin] PHP Fatal error:  Call to undefined function Httpful\curl_init() in /var/www/roundcubemail-1.2.0/vendor/nategood/httpful/src/Httpful/Request.php on line 843
`

**Comment by dbielz** [comment]
My installation via composer, had some difficulties ("could not access database") because I was logged in in roundcube during first installation of carddav, deactivated and reactivated it several times in config.inc.php until installation finally succeeded.

**Comment by blind-coder** [comment]
You need to log out and back in for the databases to be created.

**Comment by dbielz** [comment]
yes, I meanwhile found the 'INSTALL' in the plugin folder ...
And I found the reason for the blank page: [http://www.electrictoolbox.com/fix-undefined-function-curl-init-php-debian/](url) I just installed php5-curl a few minutes before and did not restart apache afterwords. 
Still having problem, but now no blank page any more:

> [24-May-2016 10:28:25 Europe/Berlin] PHP Warning:  dns_get_record(): An unexpected server failure occurred. in /var/www/roundcubemail-1.2.0/plugins/carddav/carddav_discovery.php on line 252
> [24-May-2016 10:28:25 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcubemail-1.2.0/plugins/carddav/carddav_discovery.php on line 253

even when using direct URL to address book. Although auto-discover should work anyway.

**Comment by dbielz** [comment]
Maybe that's another issue, this issue probably could be closed.

**Comment by dbielz** [comment]
yeah, wow. :-/ I repeated `php composer.phar update` and `php composer.phar install`, saw no hints about any changes, now everything works as expected. Wow! finally having my contacts in roundcube!

Thanks a lot,
Detlev

**Comment by Happyfeet01** [comment]
I have install it manually. Sorry for late response.

**Comment by blind-coder** [comment]
@Happyfeet01 
Please also install the relevant httpful and sabre/vobject classes then. Check the INSTALL file step 2.

**Comment by Happyfeet01** [comment]
Sorry, the answer was wrong from me :-( sorry. I did an install with the composer https://github.com/blind-coder/rcmcarddav/blob/master/INSTALL

i try it again and the Browserconsole say this:

> Mixed Content: The page at 'https://webmail.cloud-surfer.eu/?_task=settings' was loaded over HTTPS, but requested an insecure font 'http://fontawesome.io/assets/font-awesome/fonts/fontawesome-webfont.woff?v=4.5.0'. This request has been blocked; the content must be served over HTTPS.
> webmail.cloud-surfer.eu/:1 Mixed Content: The page at 'https://webmail.cloud-surfer.eu/?_task=settings' was loaded over HTTPS, but requested an insecure font 'http://fontawesome.io/assets/font-awesome/fonts/fontawesome-webfont.ttf?v=4.5.0'. This request has been blocked; the content must be served over HTTPS.

**Comment by blind-coder** [comment]
that's certainly not from RCMCardDAV but something else. Your browser blocks mixed content correctly there.

**Comment by mstilkerich** [comment]
Closing this issue as there has been no update in a long time and it is not clear if the issue still persists. If you are still affected by the issue, please leave a comment / reopen or create a new issue.
