### ISSUE TITLE
Cannot use 'Float' as class name as it is reserved

### ISSUE THREAD

**Issue by dvzrv** [blind-coder/rcmcarddav#152]
I'm on Arch Linux with php7 and roundcubemail 1.2.0.
Your plugin is made available through the following PKGBUILD (which also explains, how it is installed):
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=roundcube-rcmcarddav

I'm getting the following error, upon activation of the carddav plugin, rendering roundcubemail unusable:
`Cannot use 'Float' as class name as it is reserved in /usr/share/webapps/roundcubemail/plugins/carddav/inc/sabre-vobject/lib/Sabre/VObject/Property/Float.php on line 18`

Is this php7 related?

**Comment by blind-coder** [comment]
This looks very much php7 related. I will need to update Sabre-VObject to a php7-compatible version.

**Comment by fritteli** [comment]
I hit the same problem, albeit with an old version (0.7.0). After an upgrade to latest master (commit c3a7de36a98e6f1937b7530bb5d676f2f5fc653f), everything works. Seems we have to wait for the next release, then!

**Comment by stefangweichinger** [comment]
still hit this with PHP7, roundcube 1.3.0 ... any workaround available after all this time?

**Comment by blind-coder** [comment]
@stefangweichinger Please contact the package maintainer for ArchLinux.

**Comment by dvzrv** [comment]
I just adopted it and will have a look at the PKGBUILD

**Comment by dvzrv** [comment]
@blind-coder I just updated the PKGBUILD.
This got quite messy, as there have apparently been changes in how this software is shipped as a tar ball.
Please keep the naming of files concise and consistent in the future and if not having the vendor folder in the source tar ball is what you want, probably add this to the INSTALL file alongside the notes on how to install the git version of this plugin.
Saves packagers a lot of time.

In any case: I think this bug can be closed, as it was referring to 1.0.0.

Now only #178 is a major blocker (for me).

**Comment by blind-coder** [comment]
@dvzrv Thanks! It should be consistent in the future. The INSTALL doesn't explicitly spell out that the git repo is missing the vendor directory, but the release tarball does. Maybe I should add this. I thought it was implied by having to run composer manually if downloading the source.
