### ISSUE TITLE
Column preemptive_auth not existing in dbinit

### ISSUE THREAD

**Issue by hcderaad** [blind-coder/rcmcarddav#153]
The table "carddav_addressbooks" should have a column "preemptive_auth", but this is not created during dbinit.
Therefor new addressbooks are not saved (SQL error, although RC doesn't show an error, actually it shows a message telling the addressbook to be added correctly).

Executing the following (MySQL/ MariaDB) query fixes the issue:

```
ALTER TABLE `carddav_addressbooks` ADD `preemptive_auth` TINYINT(3) NOT NULL AFTER `use_categories`;
```

I've used a tinyint(3) because of the "active" field also using that data type.

(Please be careful if you actually use a table prefix to add this to the table name).

Please add this to the dbinit scripts.

**Comment by blind-coder** [comment]
The preemptive_auth field is not used anymore at all. There is no reason that field should exist in the database.

**Comment by hcderaad** [comment]
Thamks for your response. It is still used in the 1.0 release. And as since then no new releases have been made that's why I ran into this. Perhaps the INSTALL doc should clarify that this release is no longer current and installation should be done from the github repo through Composer directly?

Benjamin Schieder <notifications@github.com> schreef op 26 mei 2016 09:16:33 CEST:
>The preemptive_auth field is not used anymore at all. There is no
>reason that field should exist in the database.
>
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/153#issuecomment-221795490

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mstilkerich** [comment]
No issue in current releases.
