### ISSUE TITLE
Function get_table_name deprecated in Roundcube 1.2.0

### ISSUE THREAD

**Issue by kosli** [blind-coder/rcmcarddav#154]
Since upgrading Roundcube to version 1.2.0 i get a lot of warning messages:
Warning: Call to deprecated function get_table_name(); See bc.inc for replacement

The issue seems to be that rcmcarddav uses an deprecated function.

**Comment by blind-coder** [comment]
Please upgrade to latest master branch. It is fixed there.
Beware that there is sadly no upgrade path from 1.0 to current master.

**Comment by kosli** [comment]
thanks, i just realized it shortly after creating the issue. sorry for that.
what do you mean by no upgrade path? the users configurations and cached addressbooks?

**Comment by blind-coder** [comment]
Yes, that's what I mean. The 1.0 branch had no mechanism for proper updates. That's something the current master branch fixed, among a better HTTP client class.
There will soon be a 2.0 release, I hope.
