### ISSUE TITLE
Unknown column 'authentication_scheme' in 'field list'

### ISSUE THREAD

**Issue by greg0r** [blind-coder/rcmcarddav#156]
PHP 5.5.36
MySQL 5.5.49
Roundcube 1.2
rcmcarddav from github master 2016-06-19

I've installed httpful and sabre dependencies via composer, but I always get this message whenever I activate this carddav plugin:

    Jun 19 16:50:29 myserver roundcube: <ovptt9sd> DB Error: [1054] Unknown column 'authentication_scheme' in 'field list' (SQL Query: UPDATE carddav_addressbooks SET authentication_scheme='basic' WHERE id=NULL) in /var/www/roundcube/program/lib/Roundcube/rcube_db.php on line 539 (POST /?_task=settings&_action=save-prefs)
    Jun 19 16:50:29 myserver roundcube: <ovptt9sd> BACKEND: (update_addressbook) [1054] Unknown column 'authentication_scheme' in 'field list'
    Jun 19 16:50:29 myserver roundcube: PHP Fatal error:  Using $this when not in object context in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 2296

**Comment by blind-coder** [comment]
Did you log out and back in after activating the plugin?

**Comment by greg0r** [comment]
Yes I did, and btw I used this plugin as version 0.8.0 before with roundcube 1.0.8. So it was kind of an update. But I completely replaced the plugin directory. Is it possible that there is some kind of database issue due to this "update"? Thanks for your help.

**Comment by blind-coder** [comment]
Yes, that may well be the case. There is no update path from the older releases to the current git master, so you need to drop the carddav tables from the database, activate the plugin and then log in. During login, the new tables will be created in the database.

**Comment by greg0r** [comment]
Do I have to remove all of these tables?
    carddav_addressbooks
    carddav_contacts
    carddav_group_user
    carddav_groups
    carddav_migrations
    carddav_xsubtypes

**Comment by blind-coder** [comment]
Yes, everything that starts with carddav_

**Comment by greg0r** [comment]
OK, thank you very much. That did the job. Now I have some Warning in my log, but that is probably no carddav plugin problem.

    Jun 20 11:05:38 myserver roundcube: <l6qft3ou> BACKEND: (get_record_from_carddav) Request for VCF '2B731574-1989-4B79-AC4E-28C13B572185.vcf' which doesn't exist on the server.
    Jun 20 11:05:38 myserver roundcube: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1336
    Jun 20 11:05:38 myserver roundcube: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1354
    Jun 20 11:05:39 myserver roundcube: <l6qft3ou> BACKEND: (get_record_from_carddav) Request for VCF '7D56B81C-97EB-4D68-A9BA-AB4CCF3BFFF1.vcf' which doesn't exist on the server.
    Jun 20 11:05:39 myserver roundcube: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1336
    Jun 20 11:05:39 myserver roundcube: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1354
    Jun 20 11:05:39 myserver roundcube: PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1479
    Jun 20 11:05:40 myserver roundcube: <l6qft3ou> BACKEND: (get_record_from_carddav) Request for VCF 'C3348A9B-7988-42C4-8C26-52D9EF30279F.vcf' which doesn't exist on the server.
    Jun 20 11:05:40 myserver roundcube: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1336
    Jun 20 11:05:40 myserver roundcube: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1336
    Jun 20 11:05:40 myserver roundcube: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1354
    Jun 20 11:05:41 myserver roundcube: <l6qft3ou> BACKEND: (get_record_from_carddav) Request for VCF '1E44E7C1-68F0-4EC6-A482-6FC175642738.vcf' which doesn't exist on the server.
    Jun 20 11:05:41 myserver roundcube: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1336
    Jun 20 11:05:41 myserver roundcube: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1336
    Jun 20 11:05:41 myserver roundcube: PHP Warning:  Invalid argument supplied for foreach() in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1354
    Jun 20 11:05:42 myserver roundcube: PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1479
    Jun 20 11:05:42 myserver roundcube: PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/roundcube/plugins/RCMcarddav_master_2016-06-19/carddav_backend.php on line 1479

**Comment by blind-coder** [comment]
Yeah, that is a weird error that I still haven't been able to properly track down, but it can be ignored.
