### ISSUE TITLE
mysql.sql: init db failed with "Foreign key constraint is incorrectly formed"

### ISSUE THREAD

**Issue by AlexanderPohl** [blind-coder/rcmcarddav#158]
I have problems initialising the carddav plugin database. I used the following command:

$ mysql -u root -pmariadb -D roundcube_db < mysql.sql 
ERROR 1005 (HY000) at line 2: Can't create table `roundcube_db`.`TABLE_PREFIXcarddav_addressbooks` (errno: 150 "Foreign key constraint is incorrectly formed")

Plugin version: c3a7de3-git
Roundcube Webmail version: 1.2.0
MariaDB version: 10.1.14-1

I tried Google to search for the foreign key constraint error but could not find a solution to fix the table creation code.

**Comment by AlexanderPohl** [comment]
Sorry for the noise. I didn't realise the tables are automatically created after first login. Now it works.

**Comment by blind-coder** [comment]
Great :)
