### ISSUE TITLE
Infinite loop with username = '%l'

### ISSUE THREAD

**Issue by ghost** [blind-coder/rcmcarddav#160]
Using a preset with username '%l' (for expansion to e-mail address) caused the infinite loop described in https://github.com/blind-coder/rcmcarddav/issues/38 for me.

That is because %l was being expanded to $rcmail->user->get_username('local') -- of which I do not know the specifics, but that variable contained only my username.

I solved the issue by editing carddav_common.php as such (quickly drafted diff)

```
if($username == '%l')
-    $username = $local;
+    $username = $_SESSION['username'] . "@" . $domain;
```

Take care because the $local variable is also used for $base_url and $url expansion.

**Comment by oppa1** [comment]
It's the same loop as #143 too.

**Comment by mstilkerich** [comment]
%l takes the local part of the E-Mail address. %u takes the entire username, which is what you seem to need.
