### ISSUE TITLE
No sync from desktop to Web ?

### ISSUE THREAD

**Issue by PaSavICT** [blind-coder/rcmcarddav#161]
We try to use the card plug in that came with the install op topicdesk.

We set up a company address account. This is working from :
    - web login adding contact, we see the contacts then when we login on the same account from the computer.

But all address cards we put from the desktop, are not showing in the web interface. We tested the account on a iPad and all the address are sync. 

Also the address that is filled in from the iPad is not showing up on the Web, but is in the desktop.

We are running : OS X 10.11.5 / 10.11.6 with server 5.1.5

**Comment by blind-coder** [comment]
Which version of RCMCardDAV are you running?
Also, what do you mean "from the desktop"? Which client are you using on the desktop?

I know nothing about topicdesk, to be honst, so maybe you should ask them?

**Comment by PaSavICT** [comment]
Topicdesk has a made a install of round cube for OS X, the just made the install easy.

Changloge says 0.8.0 ?
Desktop we use OS X El Capitain. And iPad is using iOS 9.3.x

The pointed out to talk to the developer of the plugin.

**Comment by blind-coder** [comment]
*cough* Yeah, the ChangeLog... *ahem*

Have you checked the refresh timeout? There's a caching mechanism in the plugin which defaults to 1 hour. So any changes OUTSIDE the plugin will only show up after that.
You can set the timeout to 00:00:00, though.

**Comment by PaSavICT** [comment]
I set up the account. And set the preference to 15 minutes. But no luck.

Where can i check the version the right way ?

**Comment by PaSavICT** [comment]
Still not working. What to do ?

**Comment by blind-coder** [comment]
There's sadly not a good way to check the version as I've been really slacking on the versioning. I also have no first-hand experience with OSX.

You can set the DEBUG and DEBUG_HTTP variables in carddav_common.php to true and then check in roundcube/logs/carddav and carddav_warn if you see anything in there.

**Comment by mstilkerich** [comment]
No reply, closing.
