### ISSUE TITLE
Connection to Owncloud; doesn't sync existing Owncloud contacts, does add to (and remove from) Owncloud

### ISSUE THREAD

**Issue by yavuzaydin** [blind-coder/rcmcarddav#162]
I have installed with composer and I have the following problem:

When I add a new addressbook from a Owncloud 9.1 it does add the addressbook but doesn't sync existing contacts. When I add a new contact to that addressbook it also gets added on Owncloud and when I remove the newly added contact it is also removed from Owncloud.

Is this intended or is something wrong?

**Comment by yavuzaydin** [comment]
Nevermind, they appeared after a while.

**Comment by blind-coder** [comment]
Check the synchronisation timeout. It's defaulting to 1 hour, but can be changed in the settings.

**Comment by yavuzaydin** [comment]
I saw that but I was expecting it to sync when the addressbook was added new.

**Comment by blind-coder** [comment]
The sync happens when the addressbook gets accessed (either by autocompletion when writing a mail or when accessing the addressbook through the "addressbook" page of owncloud).
If that does not happen properly, you can try setting DEBUG and DEBUG_HTTP to true in carddav_common.php and check in roundcube/logs/carddav for errors.

**Comment by yavuzaydin** [comment]
You mean the addressbook page of Roundcube right?

Is it supposed to sync right away after adding a new addressbook (with the default sync timeout of 1 hour) and then visiting the addressbook in Roundcube?

If that is the case I might have to debug again because if I remember correctly it didn't on my install. I even added and removed a contact in Roundcube and checked in Owncloud if it exists there and gets removed and that all worked flawlessly and the sync wasn't started. It was after a while that when I accessed the addressbook it was very busy and started to sync.

**Comment by blind-coder** [comment]
It should start syncing when you select it in the addressbook page.
