### ISSUE TITLE
PHP Fatal error:  Class 'Httpful\Bootstrap' not found in plugins/carddav/carddav_common.php on line 25

### ISSUE THREAD

**Issue by localguru** [blind-coder/rcmcarddav#163]
Hi,

installing from tarball from github I get the following error:

PHP Fatal error:  Class 'Httpful\Bootstrap' not found in plugins/carddav/carddav_common.php on line 25

Roundcube Webmail 1.2.1

Ciao!

**Comment by blind-coder** [comment]
Did you install Bootstrap as per the INSTALL file?

**Comment by CRCinAU** [comment]
I just hit this as well.... I can't see where the INSTALL file mentions bootstrap at all.....

ie:
$ grep -i bootstrap INSTALL README.md
$

Is this on a different branch maybe?

**Comment by CRCinAU** [comment]
For what its worth, the composer installation put them here:
$ find . | grep bootstrap.php
./vendor/nategood/httpful/bootstrap.php
./vendor/sabre/vobject/tests/bootstrap.php

This is relative to your plugin directory (ie from the git clone).

**Comment by blind-coder** [comment]
@CRCinAU That is point 2. in the INSTALL file. The dependencies are installed via composer. After that, RCMCardDAV finds them there.

**Comment by CRCinAU** [comment]
Maybe there's some other issue then? I complete the install, nothing in apache error_log or roundcube logs, yet when I save the details of an owncloud carddav server, I get a reply that says it was added successfully, but no entries are created in the user account or in the database.

**Comment by blind-coder** [comment]
Which backend are you using? Also, what URL to the backend?

**Comment by CRCinAU** [comment]
db is mysql - using the standard owncloud carddav URL (which won't work unless you have a login).

Its usually in the format:
https://domain/remote.php/carddav/<username>/<address book name>/

**Comment by blind-coder** [comment]
You are missing a "addressbooks" in there:
`https://domain/remote.php/carddav/addressbooks/<username>/<addressbook>`

You can enable the DEBUG and DEBUG_HTTP parameters in `carddav_common.php` to get more information in roundcube/logs/carddav

**Comment by blind-coder** [comment]
Ugh, that's what I hate owncloud for, constantly changing their paths m(
Does it work with that path?

**Comment by CRCinAU** [comment]
hrrrm - even with both debug options on, if I set up the address book, I still get a "Successfully Saved" - but nothing in the debug, nor the logs. I also don't get an address book created in roundcube :\

**Comment by blind-coder** [comment]
err... that's veeeeery weird. There's something deeper broken if there's nothing in roundcube/logs/carddav with those options enabled.

**Comment by e-d-i-t** [comment]
Any chance to get this working on a Windows IIS environment? I downloaded the sabre vobject and nategood httpful and placed them in the vendor folder, but got the same error

**Comment by mstilkerich** [comment]
I'm closing this issue because of its age. If you are still interested, please try installing the v4 branch following the instructions on: https://github.com/blind-coder/rcmcarddav/tree/v4

If you still have issues with that, please comment / reopen and I will help.
