### ISSUE TITLE
database tables are not created

### ISSUE THREAD

**Issue by nlagaros** [blind-coder/rcmcarddav#164]
For some reason, the carddav tables are not created when I log in as a user for the first time in round cube with the plugin enabled.  I see several errors that say various tables do not exist.

I just did try to create the tables manually, by running the init script (0000-dbini/mysql.sql), but got the following error:  ERROR 1215 (HY000) at line 2: Cannot add foreign key constraint.

Any ideas?

**Comment by blind-coder** [comment]
That is very weird. Do you have a "users" table in the roundcube database?

**Comment by nlagaros** [comment]
Yes.  The users table is there and populated when I logged on for a couple of users.

**Comment by blind-coder** [comment]
That's weird... It's literally the one table that gets referenced, so it should certainly work.
What's your db_prefix set to in the roundcube configuration?

**Comment by nlagaros** [comment]
it’s not set to anything — black.

**Comment by blind-coder** [comment]
Very weird...
Can you try the following mysql.sql

[mysql_noprefix.zip](https://github.com/blind-coder/rcmcarddav/files/505096/mysql_noprefix.zip)

**Comment by nlagaros** [comment]
Tables are now created, but think I have larger problems.  I go to the carddav settings page in roundcube and get this: Your version of PHP is too old! Please update to at least 5.3.0! You got the following version installed:	5.6.24

**Comment by blind-coder** [comment]
Oh, that's apparently a bug. I have updated the required version to 7.0.0 but apparently the error message still points to 5.3.0. Oops...

**Comment by nlagaros** [comment]
So I need PHP 7?  I’m running on a Mac / OS X 10.12 — I’d like to not have to update it, but let me know.  Thanks.

**Comment by blind-coder** [comment]
You might not **need** PHP7, but it's the version I'm running and I don't have the capacities to test against earlier version.

**Comment by nlagaros** [comment]
I'm happy to test with the version I have.

**Comment by blind-coder** [comment]
That would be great!

**Comment by nlagaros** [comment]
I just need to know where to disable the version check.

**Comment by blind-coder** [comment]
@nlagaros You can do it in the config.inc.php file.

**Comment by vrelk** [comment]
I had the same issues listed above. Your modified sql file worked, and disabling the version check also worked. My next problem is that the preset address book is not being added, and when I try to add it manually, I get a white page in settings after clicking save. If I go back, all the values are empty again and nothing was added to the DB.

PHP 5.5.9

**Comment by marcvs** [comment]
For me the modified sql file managed to create the tables, however, I fail to see Carddav in settings. No logs found. What can I do?

**Comment by mstilkerich** [comment]
PHP 7.1 is required with v4. The version check has been removed, as the current code uses PHP 7.1 specific syntax that older versions won't be able to parse (and thus not be able to execute a runtime version check). PHP version is checked by composer though.
