### ISSUE TITLE
Reporting not new enough PHP Version

### ISSUE THREAD

**Issue by texxasrulez** [blind-coder/rcmcarddav#165]
Within settings I get the following "Your version of PHP is too old! Please update to at least 5.3.0! You got the following version installed: 5.6.24-0+deb8u1". As can be seen, I have 5.6 installed.

**Comment by e-dschungel** [comment]
The requirement was increased to PHP 7 in https://github.com/blind-coder/rcmcarddav/commit/eb51b63e5bf47361840a6a50bd3dbacfe0bf93e0 , but the error message was not changed, see https://github.com/blind-coder/rcmcarddav/issues/164#issuecomment-250982887

@blind-coder: Is there a real reason for the increase to PHP7? "Why not" is not a good one as 7 is still not as widespread as versions >5.3: https://seld.be/notes/php-versions-stats-2016-1-edition and https://entwickler.de/online/php/php-7-verbreitung-248908.html
In the code I don't see PHP7 only features. Is https://github.com/blind-coder/rcmcarddav/issues/155 resolved?  If you really like to go with PHP7 than it should be documented better.

**Comment by blind-coder** [comment]
I only have one machine and it is running PHP7. So I can't say for sure that everything works with earlier versions.

**Comment by blind-coder** [comment]
I have added an option to disable the version check. That should cover this issue.

**Comment by antares2001** [comment]
I have the same issue. It would be nice if you could fix this in the upstream version, as it makes rcmcarddav incompatible with the latest stable Debian 8.6.

**Comment by blind-coder** [comment]
As I said, Ihave no way to confirm PHP5 works. If you can check the issue_165 branch and get back to me, I can merge it into master and draft version 2.0.1.

**Comment by texxasrulez** [comment]
Works beautifully. Thanks for your work.

**Comment by blind-coder** [comment]
Thanks,  I have merged this into master.
