### ISSUE TITLE
DNS Query failed

### ISSUE THREAD

**Issue by oljask** [blind-coder/rcmcarddav#167]
`[06-Oct-2016 18:49:19 UTC] PHP Warning:  dns_get_record(): DNS Query failed in /usr/local/www/roundcube/plugins/carddav/carddav_discovery.php on line 207`

```
Roundcube Webmail 1.2.0
acl 	1.6
archive 	2.3
attachment_reminder 	1.1
carddav 	2.0.1
emoticons 	2.0
filesystem_attachments 	1.0
help 	1.4
hide_blockquote 	1.0
jqueryui 	1.10.4
managesieve 	8.6
subscriptions_option 	1.3
userinfo 	1.0
vcard_attachments 	3.2	
zipdownload 	3.1

php 7
```

I get DNS Query failed using config.inc.php for preset or adding Address book in gui. Is my php badly configured?

**Comment by blind-coder** [comment]
That's just a warning that usually goes out if the queried domain does not have a _carddav._tcp or _carddavs._tcp TXT record defined.
What domain are you trying to add?

**Comment by oljask** [comment]
Im trying to add my owncloud server.

**Comment by oljask** [comment]
If that is unrelated. Hereis the full log:

```
[06-Oct-2016 20:59:10 UTC] PHP Warning:  dns_get_record(): DNS Query failed in /usr/local/www/roundcube/plugins/carddav/carddav_discovery.php on line 252
[06-Oct-2016 20:59:10 UTC] PHP Warning:  Invalid argument supplied for foreach() in /usr/local/www/roundcube/plugins/carddav/carddav_discovery.php on line 253
[06-Oct-2016 20:59:10 +0000]: <gb7ldfls> DB Error: [1054] Unknown column 'authentication_scheme' in 'field list' (SQL Query: UPDATE carddav_addressbooks SET authentication_scheme='basic' WHERE id=NULL) in /usr/local/www/roundcube/program/lib/Roundcube/rcube_db.php on line 539 (POST /mail/?_task=login&_action=login)
[06-Oct-2016 20:59:10 UTC] PHP Fatal error:  Uncaught Error: Using $this when not in object context in /usr/local/www/roundcube/plugins/carddav/carddav_backend.php:2296
Stack trace:
#0 /usr/local/www/roundcube/plugins/carddav/carddav_common.php(198): carddav_backend::update_addressbook(NULL, Array, Array)
#1 /usr/local/www/roundcube/plugins/carddav/carddav_discovery.php(123): carddav_common->cdfopen('https://totan.s...', Array, Array)
#2 /usr/local/www/roundcube/plugins/carddav/carddav_discovery.php(93): carddav_discovery->retrieve_addressbooks('/remote.php/dav...', Array)
#3 /usr/local/www/roundcube/plugins/carddav/carddav.php(239): carddav_discovery->find_addressbooks('https://totan.s...', 'admin', '{BASE64}UHZOekR...')
#4 /usr/local/www/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439): carddav->init_presets(Array)
#5 /usr/local/www/roundcube/index.php(139): rcube_plugin_api->exec_hook('login_after', Array)
#6 {main}
  thrown in /usr/local/www/roundcube/plugins/carddav/carddav_backend.php on line 2296

```

**Comment by oljask** [comment]
my config:

```
<?php

$prefs['_GLOBAL']['suppress_version_warning'] = false;

$prefs['TOTAN'] = array(
        'name'         =>  'totan.su-Shared',
        'username'     =>  'admin',
        'password'     =>  'PASSWORD',
        'url'          =>  'https://totan.su/remote.php/dav/addressbooks/users/admin/shared/',
        'active'       =>  true,
        'readonly'     =>  false,
        'fixed'        =>  array( 'name', 'username', 'password' ),
        'hide' => false,
);

```

**Comment by blind-coder** [comment]
Am 6. Oktober 2016 23:01:21 MESZ, schrieb oljask <notifications@github.com>:
>If that is unrelated. Hereis the full log:
>
>```
>[06-Oct-2016 20:59:10 UTC] PHP Warning:  dns_get_record(): DNS Query
>failed in
>/usr/local/www/roundcube/plugins/carddav/carddav_discovery.php on line
>252
>[06-Oct-2016 20:59:10 UTC] PHP Warning:  Invalid argument supplied for
>foreach() in
>/usr/local/www/roundcube/plugins/carddav/carddav_discovery.php on line
>253
>[06-Oct-2016 20:59:10 +0000]: <gb7ldfls> DB Error: [1054] Unknown
>column 'authentication_scheme' in 'field list' (SQL Query: UPDATE
>carddav_addressbooks SET authentication_scheme='basic' WHERE id=NULL)
>in /usr/local/www/roundcube/program/lib/Roundcube/rcube_db.php on line
>539 (POST /mail/?_task=login&_action=login)
>[06-Oct-2016 20:59:10 UTC] PHP Fatal error:  Uncaught Error: Using
>$this when not in object context in
>/usr/local/www/roundcube/plugins/carddav/carddav_backend.php:2296
>Stack trace:
>#0 /usr/local/www/roundcube/plugins/carddav/carddav_common.php(198):
>carddav_backend::update_addressbook(NULL, Array, Array)
>#1 /usr/local/www/roundcube/plugins/carddav/carddav_discovery.php(123):
>carddav_common->cdfopen('https://totan.s...', Array, Array)
>#2 /usr/local/www/roundcube/plugins/carddav/carddav_discovery.php(93):
>carddav_discovery->retrieve_addressbooks('/remote.php/dav...', Array)
>#3 /usr/local/www/roundcube/plugins/carddav/carddav.php(239):
>carddav_discovery->find_addressbooks('https://totan.s...', 'admin',
>'{BASE64}UHZOekR...')
>#4
>/usr/local/www/roundcube/program/lib/Roundcube/rcube_plugin_api.php(439):
>carddav->init_presets(Array)
>#5 /usr/local/www/roundcube/index.php(139):
>rcube_plugin_api->exec_hook('login_after', Array)
>#6 {main}
>thrown in /usr/local/www/roundcube/plugins/carddav/carddav_backend.php
>on line 2296
>
>```
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/167#issuecomment-252087406

There's an error there, the database is not created correctly. Did you properly log out and back in to roundcube after activating the plugin? Did you drop any existing carddav tables if you upgraded from a version before 2.0.0?

**Comment by oljask** [comment]
No I have not dropped any tables. Now everything works flawlessly. Thank you!
