### ISSUE TITLE
Warnings only with php7

### ISSUE THREAD

**Issue by Thom1b** [blind-coder/rcmcarddav#168]
Hi, I have these warnings when using php-7.0.x using rcmcarddav-2.0.1. No warning with php-5.6.x
I report this issue here because rcmcarddav should be php7 ready. It wasn't when issue #155 was post.

```
Warning: Declaration of carddav_backend::delete($ids) should be compatible with rcube_addressbook::delete($ids, $force = true) in (…)/roundcubemail-1.2.2/plugins/carddav/carddav_backend.php on line 26

Warning: Declaration of carddav_backend::list_groups($search = NULL) should be compatible with rcube_addressbook::list_groups($search = NULL, $mode = 0) in (…)/roundcubemail-1.2.2/plugins/carddav/carddav_backend.php on line 26

Warning: Declaration of carddav_backend::rename_group($group_id, $newname) should be compatible with rcube_addressbook::rename_group($gid, $newname, &$newid) in (…)/roundcubemail-1.2.2/plugins/carddav/carddav_backend.php on line 26
```

I don't know if it's really an issue or if I do something wrong.

**Comment by blind-coder** [comment]
Right now, these are only warnings and can be ignored.

**Comment by Thom1b** [comment]
Right, these are only warnings but they are displayed on the top of the webmail. Because of these warnings, I can't click on addresskbooks or settings buttons. So I had to switch back to php5.

![screenshot](https://cloud.githubusercontent.com/assets/22797303/19342584/aae21f8e-9132-11e6-8efd-ada875394f28.jpg)

**Comment by blind-coder** [comment]
Oh. That's... not good then. It worked fine here, so I guess it's a PHP setting somewhere. I will look into fixing these.

**Comment by brilnius** [comment]
I had the very same problem. It seems to be the same reason as for #155.
The warning does not appear any more with the current master version.

**Comment by Thom1b** [comment]
Hi,

I confirm warnings are gone with current master version (20161210)

Thank you very much.

**Comment by blind-coder** [comment]
Great, thanks for the feedback!
