### ISSUE TITLE
Bug when adding multiple contacts to a group ("old style")

### ISSUE THREAD

**Issue by kalaleq** [blind-coder/rcmcarddav#170]
I just installed rcmcarddav 2.0.1, but i also checked master and found the same issue.

When adding a contact to a group in an addressbook with "modern group mechanism" unchecked (i.e. using the old style, which is what my server uses), i encountered a bug where only the last contact added would be in the group after save.

I tracked down the issue to a sabreDAV call that was setting the X-ADDRESSBOOKSERVER-MEMBER field like this:

$vcf->{'X-ADDRESSBOOKSERVER-MEMBER'} = "urn:uuid:" . $contact['cuid'];

This apparently overwrites the first matching entry, so each time i added a contact, the old one was overwritten.  If i manually added multiple X-ADDRESSBOOKSERVER-MEMBER lines at the server and imported the addressbook, it worked, but every time i add a member to the group it would overwrite the first member in the group.

To fix this, i changed the line to:

$vcf->add('X-ADDRESSBOOKSERVER-MEMBER', "urn:uuid:" . $contact['cuid']);

This causes a new line to be added, so nothing is overwritten.  With this fix everything appears to work!

Hope this helps someone else.  CardDAV contact groups appear to be a nightmare, but with this fix i seem to personally have it working the way i want... fingers crossed.

**Comment by adobo** [comment]
This is still an issue on latest version and on master branch.

@blind-coder, would you mind having a look at this fix? Thanks!

**Comment by adobo** [comment]
@blind-coder groups are stored properly on the CalDAV server after merging the PR. Thanks!

**Comment by mstilkerich** [comment]
Issue resolved by PR, closing.
