### ISSUE TITLE
Creating initial tables fails on mysql 5.7.16

### ISSUE THREAD

**Issue by maniacgit** [blind-coder/rcmcarddav#171]
The inital creation of the the tables fail on mysql 5.7.16 since 0 is no longer allowed to be a default value for TIMESTAMP.
I've fixed this by replacing the default 0 with a date in the past in dbmigrations/0000-dbinit/mysql.sql line 10:
last_updated TIMESTAMP NOT NULL DEFAULT '2016-11-01 00:00:00', -- time stamp of the last update of the local database

**Comment by ilpssun** [comment]
Same here: Installation didn't work, so I found the problem in the logs and changed the default to `2000-01-01 00:00:00`. After that, it worked like a charm.

**Comment by blind-coder** [comment]
Thanks for this! I have fixed this and tagged a new release!

**Comment by e-dschungel** [comment]
I think the new default should not only be applied on a new install but existing installations should be migrated, too. At least on my test install there is no automatic migration.

**Comment by blind-coder** [comment]
Am 19. November 2016 00:45:51 MEZ, schrieb e-dschungel <notifications@github.com>:
>I think the new default should not only be applied on a new install but
>existing installations should be migrated, too. At least on my test
>install there is no automatic migration.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/171#issuecomment-261671503

Is that really an issue? Updating mysql should update the default to its new possible range.

Nevertheless, I will add a proper migration later today.

**Comment by e-dschungel** [comment]
To be honest I'm not sure. Whether default NULL is allowed or not is a little more complex than just the mysql version: http://stackoverflow.com/a/36374690/6823904 Anyway it might be a good idea to use the same db scheme on all migrations paths (new + upgrade)

**Comment by e-dschungel** [comment]
Thanks for doing that so quickly. Unfortunately, it does not work for me. I look a little deeper in this. My MySQL is running on UTC +1. The range for TIMESTAMP is starting from 1970-01-01 00:00:00 (UTC) so the current default value cause a failure as MySQL expects it in local time:  ``DB Error: [1067] Invalid default value for 'last_updated' (SQL Query: ALTER TABLE carddav_addressbooks MODIFY COLUMN `last_updated` TIMESTAMP NOT NULL DEFAULT '1970-01-01 00:00:01')`` This can be cured by using ''1970-01-02 00:00:01'' or something like that but I think a cleaner default is CURRENT_TIMESTAMP if this does not interfere with the very first update after an address book was added.

**Comment by maniacgit** [comment]
CURRENT_TIMESTAMP won't work. This was the first thing I've tried before setting a date in the past. If you set CURRENT_TIMESTAMP as default nothing is imported after adding an addressbook.

**Comment by e-dschungel** [comment]
The fix in b2921cfa6 works for me.
