### ISSUE TITLE
Clashes with the latest Calendar plugin

### ISSUE THREAD

**Issue by shieldfire** [blind-coder/rcmcarddav#173]
Having both the latest Kolab/Calendar release and Carddav produces a blank email body (nothing displayed when clicking the message) and turning on logging I get:

Fatal error: Class vobject_location_property contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Sabre\VObject\Property::getValueType, Sabre\VObject\Property::setRawMimeDirValue, Sabre\VObject\Property::getRawMimeDirValue) in /var/lib/roundcube/plugins/libcalendaring/libvcalendar.php on line 1339

Error. Deactivating Carddav and removing the requirements for installation, resolves the problem.

**Comment by blind-coder** [comment]
Yes, that is a known issue, see https://github.com/blind-coder/rcmcarddav/blob/master/README.md#installation
