### ISSUE TITLE
Deleted entries not refreshed in shared addressbooks

### ISSUE THREAD

**Issue by orlitzky** [blind-coder/rcmcarddav#179]
Hello, we have one user who administers a shared address book for her domain. She can write to it, but everyone else can only read it. New entries are working, but deletions are not. When the admin deletes someone, that person remains in all of the read-only copies of the address books on the other accounts.

I've waited past the refresh period (1hr) and the entries still remain. I have confirmed that the deleted people are actually removed on the server.

**Comment by orlitzky** [comment]
Possibly related, I see entries like the following in my `carddav.warn` log:

```
[17-Jan-2017 11:13:28 -0500]: <21129spf> BACKEND: (get_record_from_carddav) Req\
uest for VCF '35031BA8-03BD-41F4-A0FD-3394BA0946C0.vcf' which doesn't exist on \
the server.
```
```
[17-Jan-2017 11:13:37 -0500]: <21129spf> BACKEND: (get_record_from_carddav) Req\
uest for VCF '8B5C380C-D814-48F6-8EE6-D53B1DF30686.vcf' which doesn't exist on \
the server.
```

**Comment by orlitzky** [comment]
I edited the code to log the XML response in `list_records_sync_collection`, and this is what I'm getting when I load an address book that has had one of its contacts deleted:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<multistatus xmlns="DAV:">
 <sync-token>data:,3172</sync-token>
</multistatus>
```

I don't know what I'm doing, but that doesn't look  right to me. I modified the following line of code in `refreshdb_from_server` to disable the sync-collection approach and use propfind instead:

```php
$records = -1;
...
// mjo: always use PROPFIND
//$records = $this->list_records_sync_collection();
...
// sync-collection not supported or returned error                                      
if ($records < 0) {
  $records = $this->list_records_propfind();
}
```

That looks like it fixed the problem. This may be server-specific, so I'm using davical-1.1.4 if that helps.

**Comment by orlitzky** [comment]
aaaaaaannd now I find this: https://gitlab.com/davical-project/davical/issues/100

**Comment by blind-coder** [comment]
Sorry for replying so late.

Great that you found the rootcause! Btw, you can just set DEBUG and DEBUG_HTTP to true in carddav_common.php and the requests get logged to roundcube/logs/carddav

**Comment by pbiering** [comment]
Just in case one uses Radicale as Cal/CardDAV server can run into similar issue, because without a patch on Radicale, it offers "sync-collection" while missing internal support for that feature, see also https://github.com/pbiering/Radicale/commit/2bd1b4f71a9264e01600a70b15e8e79d57d52493

**Comment by orlitzky** [comment]
I could make this into a config option to prefer PROPFIND, or we could just close this since the bug isn't in rcmcarddav?

**Comment by blind-coder** [comment]
An option sounds good. A way to check if sync-collection is broken would be perfect, but I'll take the option if you can do that!

**Comment by orlitzky** [comment]
I made an attempt in #180 that works, unless you'd prefer a cleaner way of getting preferences into the backend class. In that case you'll have to tell me what to do though =)

**Comment by bronson** [comment]
I'm getting this error on NextCloud 10.

I imported 1300 contacts, they were all flawed, so I deleted them in NextCloud.  NextCloud and Apple Contacts show that they're deleted, but rcmcarddav still thinks that they exist.

Is this the same error?

```
[11-Apr-2017 23:56:31 -0700]: <kuq5d840> BACKEND: (get_record_from_carddav) Request for VCF '34AFA017-3F19-4915-853C-C3D216AA79AF.vcf' which doesn't exist on the server.
[11-Apr-2017 23:56:31 -0700]: <kuq5d840> BACKEND: (get_record_from_carddav) Request for VCF '0400B328-7AC6-486A-BC29-D4BB4D4A76B4.vcf' which doesn't exist on the server.
[11-Apr-2017 23:56:32 -0700]: <kuq5d840> BACKEND: (get_record_from_carddav) Request for VCF '3CA3E28C-0365-4B16-94AC-75081E7F51DB.vcf' which doesn't exist on the server.
```

**Comment by blind-coder** [comment]
Did you wait for the synchronisation timeout? By default, RCMCardDAV only syncs once per hour.

**Comment by bronson** [comment]
Yes, that was the problem.  My apologies!

**Comment by blind-coder** [comment]
Great to hear that it works now!
