### ISSUE TITLE
Field "Display Name" does not update on editing

### ISSUE THREAD

**Issue by conspacer** [blind-coder/rcmcarddav#183]
- Create a contact (in the RC interface)
- Assign a field in the 'Display Name' (i.e. "blah"). Save
- Edit this new contact (after 1 minute or 100 hours, makes no difference), replace "blah" with "foo". Save

Contact still shows "blah" in the 'Display Name' field. It will not update it. 
Workaround is to move the contact to a local RC addressbook, do the edits and then move it back to the remotely loaded CardDAV addressbook.

**Comment by conspacer** [comment]
Update 1.
Seams to be just for contacts created in the RC interface. Synced contacts from the CardDAV server can be edited as expected.

**Comment by mstilkerich** [comment]
Tried this with the current master, it works as expected (i.e. card shows up as Foo after changing in). I guess this issue was fixed in the time since your report (sorry that you did not get a reply).
