### ISSUE TITLE
Are there any Debug Options?

### ISSUE THREAD

**Issue by Offerel** [blind-coder/rcmcarddav#184]
In the last days, i have upgraded my CardDAV Server from SabreDAV 3.2.0 to 3.2.2. Before that, i could successfully sync. After the Upgrade, it seems not to sync anymore. I dont whre the Problem is, since there is nothing in the error logs for Roundcube. However last_updated and sync_token fields in the DB Backend are changed to the correct values. Any Idea, what i could do?

**Comment by Offerel** [comment]
I think, I have found the Problem. It seems Not to be the SabreDAV Version. Additionally to SabreDAV, I have switched also from http 1.1 to http2 in the Nginx Config for better Performance. 

If I remove the http2 setting from nginx config, I could successfully update from the CardDAV Server.

So I would like to ask, if you could please support also http2 requests?

**Comment by blind-coder** [comment]
Am 20. Februar 2017 22:31:32 MEZ schrieb Offerel <notifications@github.com>:
>I think, I have found the Problem. It seems Not to be the SabreDAV
>Version. Additionally to SabreDAV, I have switched also from http 1.1
>to http2 in the Nginx Config for better Performance. 
>
>If I remove the http2 setting from nginx config, I could successfully
>update from the CardDAV Server.
>
>So I would like to ask, if you could please support also http2
>requests?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/184#issuecomment-281185731

In that case, please make sure that curl, libcurl and php-curl on the server roundcube runs on supports http2. There's not much I can do about it.

**Comment by Offerel** [comment]
You are right, after testing, my curl does not support http2. Im on Raspbian with Debian Jessie, but also jessie-backports does not have a newer Version as 7.38 of libcurl3. The only way, i could found, is, to compile from source. I could found some Information @ https://serversforhackers.com/video/curl-with-http2-support but that's not a so simple way. So i will stick with http 1.1 or maybe spdy. But thx for pointing me in the right direction.

**Comment by Offerel** [comment]
A small Hint for other Users. I have solved this with a small workaround. Since its not possible to use one subdomain with http2 and another without with nginx (if http2 is definded for one subdomain, its defined for ALL subdomains), i use a localhost exception. This special URL is only available in the internal Network via Port 80. From outside the local Net (Internet), SabreDAV is only available via, SSL. Now i could point the CardDAV Plugin to the localhost variant, since http2 does only ´work with SSL enabled.
