### ISSUE TITLE
Update for RC 1.3?

### ISSUE THREAD

**Issue by Offerel** [blind-coder/rcmcarddav#186]
Is there a Update planned for Roundcube 1.3? I have tried the latest release here with 1.3 Beta, but i can't add a CardDAV Server via Settings.

**Comment by Offerel** [comment]
I have entered all fields and clicked on the Save-Button. I get a Message, that this should be successfull, but after this, the Fields are empty. If i look in to the Database, nothing was saved. If i copy a existing dataset from a parallel installed Roundcube 1.2.3 Database directly to the Beta Database, i see the Adressbook in Roundcube. If i change now something like the Password, this seems to delete the fields (or truncates them) for this dataset.

I try to enable your DEBUG Options and will report.

**Comment by Offerel** [comment]
After setting the DEBUG Options to true, nothing is written to the RC Logfiles. I see only the entry's for Database Initialization. In the Logdirectory i have only 2 files: carddav and errors, both with the last timestamp from DB Initialization :-(

**Comment by blind-coder** [comment]
That is really weird. This behaviour should only apply when the name field is left blank...
I'll have a look at that.

**Comment by Offerel** [comment]
I have tried the Plugin today with the actual Release Candidate of RC 1.3. Same behavior as with the Beta. I get a Message that by adding a new Connection was saved successfully, but if i look in the Database, nothing was saved.

Do you had the time to look at this issue?

**Comment by blind-coder** [comment]
I have pushe a branch issue_186 that should fix this issue while also remaining compatibility with RC 1.2.3.

Can you please check if it works for you?

**Comment by Offerel** [comment]
The Database connection is now saved with this branch and displayed afterwards in the settings panel. ALso the "name" is changed, at least in my case from "CardDAV" to "CardDAV (Kontakte)" which is OK. What i miss in database is the SyncToken. The field is empty, but should have the value from the last Sync like "http://sabre.io/ns/sync/200", The timestamp of the last sync however is updated to time some seconds before. If i manually change the timestamp to 1 day earlier, there seems to be a sync ongoing, since shortly later, the timestamp is changed to this date. But the SyncToken isnt updated.

Additionally, no Contacts are found "carddav_contacts" table.

If i use the master branch and manipulate the database manually to enter the correct values (since i cant use the GUI), it syncs, and carddav_contacts are filled with the data. However, if i try to view the Contacts in Roundcube GUI, no Contacts are displayed.

**Comment by blind-coder** [comment]
What backend are you using? Right now, vanilla SabreDAV does not work and I don't really know why.
I tested the branch with OwnCloud and it worked fine.

The sync-token is only populated if the server actually sends one.

**Comment by Offerel** [comment]
On the same Server, i have also Roundcube 1.2.4, your Plugin from the Master Branch and SabreDAV 3.2.2. This works without any Problem. There was a Bug in SabreDAV 3.2.1 and CardDAV Sync, which was fixed with 3.2.2. I will send you a Mail in German, maybe, you can use my Server as a testing Server for SabreDAV.

**Comment by pgollor** [comment]
I had the same problem with rc 1.3 and the current git branch at commit e33a435965264fe3d09753bdb75c8846f1227f91 does not work for me. I got only a white screen.
But the release `v2.0.4` with the `carddav.php` from e33a435965264fe3d09753bdb75c8846f1227f91 works fine.

**Comment by blind-coder** [comment]
@pgollor Only a white screen indicates a vastly different error. Please open a new issue and post your roundcube logs and relevant parts of apaches error log.

**Comment by TheOneValen** [comment]
> I had the same problem with rc 1.3 and the current git branch at commit e33a435 does not work for me. I got only a white screen.
>But the release v2.0.4 with the carddav.php from e33a435 works fine.

Same here. I can add an addressbook again. But it does not get populated with data.

**Comment by Offerel** [comment]
Do you use SabreDAV > 3.20? There is a CardDAV Bug which prevents some clients not getting the vCards with the correct format. This was introduced with SabreDAV 3.21 but only partly solved with 3.22

My only solution was it to downgrade to SabreDAV 3.20

**Comment by TheOneValen** [comment]
I use Nextcloud 12

**Comment by Offerel** [comment]
I think NextCloud has updated it's Sources also to SabreDAV 3.22

The Problem is that SabreDAV Development is on hold since April of this year. If no one picks up the Development, also NextCloud will stay on the last Bugs of SabreDAV.  I have never understand why NextCloud has updated from 3.20 to the buggy 3.22.

**Comment by sub0ne** [comment]
I got the same problem. I'm using Baikal (0.4.6) as server but this again uses SabreDAV. If I enter all the data and click save it tells me everything went fine, all the fields are cleared. When I switch to the address book there are no addresses. Even the database tables are still empty. Setting the debug variables to true doesn't write anything to the logfile. 

Oddly enough I can sync my iPhone, Macbook and Thunderbird without problems. So there must be something else I guess.

**Comment by j-ed** [comment]
I can confirm this issue. After updating to RC 1.3.0 the address book is still accessible but the details aren't shown in the settings dialog anymore:
![2017-07-01 11_54_28-eisfair-roundcube einstellungen](https://user-images.githubusercontent.com/2572764/27760998-5da27594-5e54-11e7-85d4-e8a81aa343a3.png)
I've also tried to use a current Git snapshot (30.06.2017) but this caused a much bigger problem because the RC login page wasn't even shown at all. Only a blank page was displayed.

**Comment by ras07** [comment]
> I had the same problem with rc 1.3 and the current git branch at commit e33a435 does not work for me. I got only a white screen.
> But the release v2.0.4 with the carddav.php from e33a435 works fine.

So far it looks like e33a435 is working for me.  I'm running Apache 2.4.18 and PHP 7.0.22 on Ubuntu 16.04.3. I got it working on Roundcube 1.2.5 and then upgraded that to 1.3. I'm connecting it to Google's carddav service.

**Comment by Offerel** [comment]
I have some news to this issue, but no real solution. Today i had problems syncing a calendar via Outlook and CalDAVSynchronizer. The problem was in this case a small bug in vObject from SabreDAV. This is solved in SabreDAV 3.2.2, so installed again this version. All other clients could now successfully sync with SabreDAV 3.2.2. Only rcmcarddav have problems again. I get this annoying message "(refreshdb_from_server) Errors occurred during the refresh of addressbook" in /var/log/roundcube/carddav.warn.

I have now patched SabreDAV 3.2.0 with vObject 4.1.3 which solves the problem with the broken calendar sync and also the error with rcmcarddav .

Since i see this only as a small workaround, i hope you can fix the problem with SabreDAV 3.2.2. If you need more information, please don't hesitate and ask. Maybe i can find some useful in some logfiles, but currently i have no glue where i can get more information.

**Comment by pousterlus** [comment]
Hi,
I'm experiencing the same problem here, on Roundcube 1.3.4 / Baikal 0.4.6 and up-to-date RCMCardDAV 2.0.4.

Error 500 in carddav logfile and refreshdb problem in carddav.warn.

Everything's fine in the other MUA I use.
Has someone found a solution yet ?

Thanks :)

-- 
Léo.

**Comment by blind-coder** [comment]
@pousterlus You clone the repository, use the master branch and follow the instructions in the README.md file.
Quick:
```
cd roundcube/plugins && git clone https://github.com/blind-coder/rcmcarddav.git carddav
# Install composer as per https://getcomposer.org/download/
cd coundcube/plugins/carddav && php composer.phar install
# Enable carddav in roundcube/config/config.inc.php by adding 'carddav' to $config['plugins']
```
