### ISSUE TITLE
Unknown column 'use_categories' in 'field list'

### ISSUE THREAD

**Issue by mddvul22** [blind-coder/rcmcarddav#194]
Today, I installed the latest carddav plugin (using git clone) into my Roundcube instance (running on Debian 8.7).  Followed the instructions and configured carddav for use with Owncloud address book (ownclound 7.0.4 from Debian).  Carddav seems to be connecting to owncloud address book but is failing to import contacts.  I see the following error in the roundcube logs.  NOTE: I have replaced my hostname with xxx's in the error log below.

`[18-Apr-2017 08:27:41 -0500]: <0lr1tqjb> DB Error: [1054] Unknown column 'use_categories' in 'field list' (SQL Query: INSERT INTO carddav_addressbooks(name,username,password,url,user_id,use_categories,refresh_time) VALUES ('owncloud (Contacts)','joe','{BASE64}RzdFT19vQHgta1QyJVNQKmpabVZIJQ12YnclJEx4dzFFKmNiR2QkfnVbaV90RFN2X1M5VlY2UzAydmM1UDBr','https://XXX.XXX.XXX:443/owncloud/remote.php/carddav/addressbooks/joe/contacts/','1','0','01:00:00')) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 544 (POST /roundcube/?_task=settings&_action=save-prefs)`

Looking at carddav/dbmigrations/0000-dbinit/mysql.sql, I don't see a "use_categories" field in the carddav_addressbooks table.  Is this the problem?

Thanks!

**Comment by blind-coder** [comment]
use_categories has been added in 0001-categories/mysql.sql. Check roundcube/logs/carddav if that migration was run during login.

**Comment by mddvul22** [comment]
Thanks! That was the problem.  I've had some issues with the database tables not getting creating (maybe because it sits on a different server).  I should have seen that 0001-categories directory.  Regardless, I just now manually ran that sql file and things are working now. thanks!
