### ISSUE TITLE
BACKEND: (update_addressbook) Unknown column 'authentication_scheme' in 'field list'

### ISSUE THREAD

**Issue by vasyugan** [blind-coder/rcmcarddav#198]
each new addressbook I add does not get saved. The log says:

BACKEND: (update_addressbook) [1054] Unknown column 'authentication_scheme' in 'field list'

**Comment by blind-coder** [comment]
Please follow the https://github.com/blind-coder/rcmcarddav/blob/master/INSTALL file, specifically the part about logging out, activating the plugin and logging in again. That will properly initialise the databases.

**Comment by vasyugan** [comment]
Thanks, restoring the default config file and deleting the old tables from the data base did the trick. Actually, it did work for a long time for me, but some update (of roundube or owncloud) must have destroyed it, after which I tried updating the carddav plugin, which didn't fix things either, and I thought just deleting the carddav tables in the roundcube database would do the trick, but it didn't.
