### ISSUE TITLE
Failed to load plugin file

### ISSUE THREAD

**Issue by yamlfd** [blind-coder/rcmcarddav#201]
I've installed all as documented, but the plugin does not load with roundcube 1.2.3

`[23-Jul-2017 16:06:21 +0200]: PHP Error: Failed to load plugin file /var/lib/roundcube/plugins/carddav/carddav.php in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 173 (POST /roundcube/?_task=settings&_action=refresh)
`

I used the plugin 2.0.4... ist this version not compatible with the roundcube version? What can be the root cause and how can this solved?

**Comment by blind-coder** [comment]
Hey @yamlfd how did you fix it?

**Comment by yamlfd** [comment]
My fault. Missed to create a directory symlink from /var/lib/roundcube/plugins/carddav/ to /usr/share/roundcube/plugins/carddav/. Debian 9 roundcube packages are a bit complicated...
