### ISSUE TITLE
Incorrect installation documentation

### ISSUE THREAD

**Issue by yamlfd** [blind-coder/rcmcarddav#202]
> Via release tarball:
> Download and extract the release tarball into roundcube/plugins directory and rename the extracted directory to carddav. The tarball contains all necessary dependencies and does not need composer.
> 
That is completly incorrect. Dependencies are missing in the ZIP release on github.

> Via composer:
> Add "roundcube/carddav": "dev-master" to your composer.json file and install with php composer.phar install.

Please describe in more detail what composer file need to be edited.

> Via git:
> Clone the repository: cd roundcube/plugins && git clone git@github.com:blind-coder/rcmcarddav.git carddav

This cloning does not work. This is not an anonymous url to github. Anonymous github links are different, see https://stackoverflow.com/questions/16187849/permission-denied-when-trying-to-anonymously-clone-a-github-repository. Also with the changed url it has not worked for me. Please try to repro with an anonymous github clone link and fix documentation.

> Install dependencies:
> Install composer as per the documentation: https://getcomposer.org/download/
> Run php composer.phar install

For me I cd to the carddav folder and issues just "composer install" what downloaded the missing dependencies.

**Comment by blind-coder** [comment]
> That is completly incorrect. Dependencies are missing in the ZIP release on github.
Which file did you test? I checked the 2.0.4 release zip and all deps were in there.

> Please describe in more detail what composer file need to be edited.
If you installed roundcube, you have a composer.json in your roundcube directory. That one.

> This cloning does not work. This is not an anonymous url to github.
I fixed the link, thanks!

> For me I cd to the carddav folder and issues just "composer install" what downloaded the missing dependencies.
That's the part you need to do with a git clone, correct.

**Comment by yamlfd** [comment]
I used the only download button on the project, see https://github.com/blind-coder/rcmcarddav. It is the green button on top left of the project home and named "clone or download" > zip.

https://github.com/blind-coder/rcmcarddav/archive/v2.0.4.zip

**Comment by blind-coder** [comment]
Ah, there's the issue. That's just downloading the content of the git tag "v2.0.4" as a ".zip" file. 
If you check the https://github.com/blind-coder/rcmcarddav/releases/tag/v2.0.4 page you can see two download option above the "Source code" options. Those contain all the dependencies you need. The "Source code" options just download the git tag whereas the other two options are the release archives that I uploaded manually and contain the dependencies you need.
