### ISSUE TITLE
Class Httpful/Bootstrap not found

### ISSUE THREAD

**Issue by cbrace** [blind-coder/rcmcarddav#204]
Hi,

I recently upgrade my roundcubemail installation to v1.3.0. This broke a few plugins, including carddav.

I downloaded a zipfile of the most current version here and installed it under plugins/

I'm now seeing the following fatal error (sorry for the JPEG screen cap, I'm at work and don't have access to a proper terminal):
![carddav-error](https://user-images.githubusercontent.com/449948/29510205-43508f8a-865b-11e7-8c96-07bb945a0388.JPG)

Any ideas on what is going wrong here?

Thanks

**Comment by blind-coder** [comment]
Am 21. August 2017 10:28:38 MESZ schrieb Colin Brace <notifications@github.com>:
>Hi,
>
>I recently upgrade my roundcubemail installation to v1.3.0. This broke
>a few plugins, including carddav.
>
>I downloaded a zipfile of the most current version here and installed
>it under plugins/
>
>I'm now seeing the following fatal error (sorry for the screen cap, I'm
>at work and don't have access to a proper terminal):
>![carddav-error](https://user-images.githubusercontent.com/449948/29510205-43508f8a-865b-11e7-8c96-07bb945a0388.JPG)
>
>Any ideas on what is going wrong here?
>
>Thanks
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/204

Hi. Please check the INSTALL.md file for how to install dependencies or download a release file (not source file) which includes the dependencies.

**Comment by cbrace** [comment]
Thanks for pointing me in the right direction. Installed with "composer" and I was good to go.
