### ISSUE TITLE
Modifying contacts fails with 2.0.4, Roundcube 1.2.5, and Radicale 1.1.1

### ISSUE THREAD

**Issue by NameDevRandom** [blind-coder/rcmcarddav#205]
Hi,

Modifying contacts fails. Creating contacts is working. Modifying contacts actually deletes(!) them.

I recently updated my system and did not have this problem before. 

Please find the debug logs from rcmcarddav and radicale attached.
[logs.txt](https://github.com/blind-coder/rcmcarddav/files/1289002/logs.txt)

I recorded a sequence of creating a contact (which works) and modifying it (which fails).

Radicale works properly with other clients like Thunderbird/SOGO connector and Android DAVdroid.

Best regards, and thanks in advance for resolving this.

**Comment by c3rebro** [comment]
Hello,

i think i have the exact same issue.
I have Whitelistet localhost connects on nginx reverseproxy. So there is no nessesary auth procedure.

However, trying to modify a successfully created contact leads to:

127.0.0.1 - - [26/Feb/2020:08:59:41 +0100] "DELETE /radicale/shared/contacts.vcf/4234f69d-730b-4b2c-a323-01bb6065d8c5.vcf HTTP/1.1" 412 0 "-" "RCM CardDAV plugin/3.0.3"

Not sure where to look at, else. There is no valuable logging in /roundcube/logs/*

**Comment by mstilkerich** [comment]
Is anyone still active here willing to test with Radicale?

**Comment by mgeisselreiter** [comment]
Hi,

I use RC 1.4.5, CardDav 3.0.3 and Radicale 1.1.2. Do you want me to try 
something specific?

Miroslav Geisselreiter

Dne 28.6.2020 v 21:09 Michael Stilkerich napsal(a):

**Comment by mstilkerich** [comment]
Hi,

  if you experience the above issues with Radicale, I would appreciate if you could give the current development branch (v4) a try to see if it's fixed. Thanks!

See installation instructions here: https://github.com/blind-coder/rcmcarddav/tree/v4

**Comment by mgeisselreiter** [comment]
Hi,
I do not experience the above issue. Just now I tried to add new contact, saved, then edited this contact, changed address and added Comment, saved and no errors at all. I use RC 1.4.5, CardDav 3.0.3 and Radicale 1.1.2.

**Comment by mstilkerich** [comment]
Ok that's good to hear, thanks :-) Then I'll see if anyone else pops up who can reproduce the issue.

**Comment by mstilkerich** [comment]
Closing this as the issue cannot be reproduced. Current versions of radicale work fine with the current master.
