### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by stan3** [blind-coder/rcmcarddav#210]
It would be helpful to have a new release with fixes like #186 for latest roundcube compatibility.

**Comment by dvzrv** [comment]
@blind-coder will this still happen? I'm otherwise about to delete this package from the Arch Linux User Repository.

**Comment by blind-coder** [comment]
It will happen, but this project is very low priority for me right now (mostly because "works for me"). Don't expect a proper release before Q4. I suggest you use a recent git commit for a version. If that doesn't work for you, idc about it being removed from distributions.

**Comment by blind-coder** [comment]
I just released the current master branch as v3.0.0.
