### ISSUE TITLE
CardDAV setting was not saved on clicking "Save"

### ISSUE THREAD

**Issue by ferdisn** [blind-coder/rcmcarddav#211]
Hi, i am installing a brand new roundcube and also this plugin. When I try to save a cardDAV server setting in Roundcube Setting page, it was not saved.

Nothing else appear on php logs and carddav logs, however, roundcube logs produce this:

[03-Jan-2018 21:12:30 Asia/Jakarta] PHP Warning:  Declaration of carddav_backend::rename_group($group_id, $newname) should be compatible with rcube_addressbook::rename_group($group_id, $newname, &$newid) in /var/webapp/user/files/roundcube/plugins/carddav/carddav_backend.php on line 26

Roundcube 1.3.3, RCMCardDAV 2.0.4 from github.

**Comment by blind-coder** [comment]
Am 3. Januar 2018 15:16:11 MEZ schrieb ferdisn <notifications@github.com>:
>Hi, i am installing a brand new roundcube and also this plugin. When I
>try to save a cardDAV server setting in Roundcube Setting page, it was
>not saved.
>
>Nothing else appear on php logs and carddav logs, however, roundcube
>logs produce this:
>
>[03-Jan-2018 21:12:30 Asia/Jakarta] PHP Warning:  Declaration of
>carddav_backend::rename_group($group_id, $newname) should be compatible
>with rcube_addressbook::rename_group($group_id, $newname, &$newid) in
>/var/webapp/user/files/roundcube/plugins/carddav/carddav_backend.php on
>line 26
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/blind-coder/rcmcarddav/issues/211

Please use a got clone of the latest master branch instead of a release tar ball.

**Comment by ferdisn** [comment]
Installed from master, now the saving works but a new error emerges.

<pre>[04-Jan-2018 22:30:18 Asia/Jakarta] PHP Fatal error:  Uncaught Error: Class 'Sabre\VObject\Reader' not found in /var/webapp/ferdi/files/roundcube/plugins/carddav/carddav_backend.php:1566
Stack trace:
#0 /var/webapp/ferdi/files/roundcube/plugins/carddav/carddav_backend.php(753): carddav_backend->create_save_data_from_vcard('BEGIN:VCARD\r\nVE...')
#1 /var/webapp/ferdi/files/roundcube/plugins/carddav/carddav_backend.php(895): carddav_backend->query_addressbook_multiget(Array)
#2 /var/webapp/ferdi/files/roundcube/plugins/carddav/carddav_backend.php(596): carddav_backend->addvcards(Object(SimpleXMLElement))
#3 /var/webapp/ferdi/files/roundcube/plugins/carddav/carddav_backend.php(465): carddav_backend->list_records_sync_collection()
#4 /var/webapp/ferdi/files/roundcube/plugins/carddav/carddav_backend.php(111): carddav_backend->refreshdb_from_server()
#5 /var/webapp/ferdi/files/roundcube/plugins/carddav/carddav.php(294): carddav_backend->__construct('1')
#6 /var/webapp/ferdi/files/roundcube/program/lib/Roundcube/rcube_plugin_api.php(440): carddav->get_address_book(Arra in /var/webapp/ferdi/files/roundcube/plugins/carddav/carddav_backend.php on line 1566</pre>

I did run the `php composer.phar install` bit, and here is the content:
<pre>
[ferdi@bellatrix vobject]$ ls
bin  ChangeLog.md  composer.json  lib  LICENSE  README.md  tests
[ferdi@bellatrix vobject]$ pwd
/var/webapp/ferdi/files/roundcube/plugins/carddav/vendor/sabre/vobject
[ferdi@bellatrix vobject]$ 
</pre>

Is there something wrong with my execution?

**Comment by blind-coder** [comment]
Can you show the content of sabre/vobject/lib? There should be a Reader.php in there.

**Comment by ferdisn** [comment]
Hi, i'm repeating the install and now it works. Closing this. Sorry for  burdening you @blind-coder and thank you.
