### ISSUE TITLE
Dispay name replaced by Organization

### ISSUE THREAD

**Issue by RabbitDuck** [blind-coder/rcmcarddav#213]
Hi,

When sync from Nextcloud 12.0.4, the dispay name (FN) will be replaced by the organization (ORG) field if the organization field of the vcard is not empty.

I don't know is it a bug in sabre/vobject (may be it return the vobject type as org) or a bug in the carddav plugin.

I just remove the line 247 of carddav_backend.php
$save_data['name']     = $save_data['organization'];
and everything is ok after that.

Any idea?

**Comment by blind-coder** [comment]
That should only happen when you have neither first nor last name of a contact set. Can you confirm that neither of that is present in the respective vcard?

**Comment by RabbitDuck** [comment]
Yes, can confirm that if first and last name field are both empty, the FN will be replaced by the ORG.
As the web interface of Nextcloud use the FN as default, I need to add the First name and last name field by hand.

Is there a way (may be by mean of the config file) we can control this behavior?
Thanks

**Comment by blind-coder** [comment]
There's no way to hdo that in the config right now. The clients (and NextCloud's webinterface counts as a client here) I tested with all populated First Name and Last Name from the Full Name so far. I'll check this behaviour in NextCloud and if it deviates from that, I'll file it as a bug there.

**Comment by RabbitDuck** [comment]
Thank you!

**Comment by blind-coder** [comment]
@RabbitDuck I have opened https://github.com/nextcloud/contacts/issues/458 for tracking, this is definately a unique behaviour with NextCloud. I have tested with OwnCloud and CardDAV-Sync for Android by dmfs.org and both populate First Name and Last Name when only a Full Name is specified.

**Comment by RabbitDuck** [comment]
For Nextcloud 12, the default interface for a new contact is:
The "ABC Man", the name, will save to FN field
![image](https://user-images.githubusercontent.com/31124140/35091862-c80de13a-fc78-11e7-8a0b-62b8c4edc119.png)

You need to add "Detailed Name" fields by hand and type in the first and last name
![image](https://user-images.githubusercontent.com/31124140/35092023-1c036f6c-fc79-11e7-94d6-42ad2b5c5ba4.png)

So, I don't know it is a Nextcloud bug or it is working as designed.
Anyway, thank you!

**Comment by blind-coder** [comment]
Yeah, I noticed that. I'm pretty sure that neither one violates an RFC, but NextCloud's behaviour is very different from all other clients.

Just a side note: `FN` stands for `Formatted Name` and MUST be present in a vCard. `N` stands for `Name` and is separated into `Family Names (also known as surnames), Given Names, Additional Names, Honorific Prefixes, and Honorific Suffixes` and SHOULD be present in a vCard.

Source: https://tools.ietf.org/html/rfc6350#section-6.2.1 and https://tools.ietf.org/html/rfc6350#section-6.2.2

**Comment by blind-coder** [comment]
Well, NextCloud won't fix their end, so I guess this'll remain an issue. Just one more reason not to use NextCloud.

**Comment by mstilkerich** [comment]
The referenced RFC6350 is vCard v4, however, vCard v3 is still the most widely used and the only version each CardDav server MUST support.

VCard 3 is specified in RFC 2426, and N is required in vCard 3. Nextcloud serves Version 3 vCards with the N property missing -> not compliant with RFC 2426.

> Profile special notes: The vCard object MUST contain the FN, N and VERSION types.

**Comment by mstilkerich** [comment]
Hello,

 this behavior does not occur with v4.0.2 anymore so it must have been fixed somewhere along the way. v4.1.0 will be changed in behavior to never override an explicitly set formatted name (FN) in a received VCard, or a displayname entered in roundcube.
