### ISSUE TITLE
RC addressbook - cannot create new group ?

### ISSUE THREAD

**Issue by olivy70** [blind-coder/rcmcarddav#214]
Hi,
My english is very poor but...

If i create a new group in an addressbook, it is not synchronized in owncloud.
In db carddav_groups, i can see "etag=dummygroup" and "group=dummygroup".

So, is it possible to create new group in a shared addressbook ?

Thanks

**Comment by mstilkerich** [comment]
Hello, sorry for the very late reply. Is the issue still relevant to you?

**Comment by mstilkerich** [comment]
Closing because no reply in >14 days. Feel free to reopen if you are still affected an interested in resolution of the issue.
