### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by ebiel** [blind-coder/rcmcarddav#215]
I am running Roundcube 1.3.4 on PHP 7.1 and downloaded the master branch of the rcmcarddav plugin here on github.

When I activate the plugin by adding it to the array of plugins in the Roundcube config.inc.php I only get a totally blank screen after login. The following appears in my log file:

[11-Feb-2018 23:32:53 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Httpful\Bootstrap' not found in /X/X/html/roundcube/plugins/carddav/carddav_common.php:25
Stack trace:
#0 /X/X/html/roundcube/plugins/carddav/carddav_backend.php(22): require_once()
#1 /X/X/html/roundcube/plugins/carddav/carddav.php(122): require_once('/X/X...')
#2 /X/X/html/roundcube/program/lib/Roundcube/rcube_plugin_api.php(99): carddav->init()
#3 /X/X/html/roundcube/program/include/rcmail.php(135): rcube_plugin_api->init(Object(rcmail), 'login')
#4 /X/X/html/roundcube/program/include/rcmail.php(79): rcmail->startup()
#5 /X/X/html/roundcube/index.php(43): rcmail::get_instance(0, NULL)
#6 {main}
  thrown in /X/X/html/roundcube/plugins/carddav/carddav_common.php on line 25

Let me know if you require any additional information to track this down.

Any help is much appreciated.

**Comment by ebiel** [comment]
Okay, got it.
The whole folder _vendor_ is missing when downloading the master branch. I just took the _vendor_ folder from the release 2.0.4 and everything seems to work just fine now.
Last release is 15 months old. If you got the time it seems to make sense to release a new version so that people can get a more up-to-date version of the whole package including the _vendor_ folder.

**Comment by blind-coder** [comment]
This is documented in the README under Installation. If you clone from git, you must use composed to install dependencies which will create the vendor/ directory.
