### ISSUE TITLE
Automatic creation of contacts

### ISSUE THREAD

**Issue by suamikim** [blind-coder/rcmcarddav#216]
Hi,

does the plugin automatically create contacts when writing and/or replying to an recipient which is not already listed in the address book?

I often find entries in my CardDAV address book which were not created by me and only contain E-Mail-Addresses.

My guess is that they're either created by K9Mail on my phone or by your plugin in my private Roundcube installation but I can't figure out which one it is.

Can I somehow disable this if they are created by your plugin?

Thanks & best regards

**Comment by blind-coder** [comment]
The plugin only provides an addressbook, it does not populate it unless something asks it to. To the applications, it looks like any other addressbook. My guess is it's either K9, Thunderbird or Roundcube with a plugin like https://plugins.roundcube.net/packages/sblaisot/automatic_addressbook

**Comment by CombeeMike** [comment]
Ok, thanks for the information. There's definitely no other plugin in Roundcube installed which would do this so I'm going to dig a little deeper into K9.
