### ISSUE TITLE
automatic addressbook?

### ISSUE THREAD

**Issue by fauno** [blind-coder/rcmcarddav#218]
Hi, thanks for the plugin!

Do you have plans to integrate automatic addressbook functionality to this plugin?  I know it's out of scope, but the two plugins I found seem to interact directly with RC's database, so they wouldn't sync with CardDAV, AFAICT

https://plugins.roundcube.net/packages/teon/automatic_addressbook_ng

https://plugins.roundcube.net/packages/sblaisot/automatic_addressbook

**Comment by fauno** [comment]
ping @blind-coder? :)

**Comment by fauno** [comment]
Great! I'll test it then :)

**Comment by mstilkerich** [comment]
No issue here
