### ISSUE TITLE
Had to disable set_option lines

### ISSUE THREAD

**Issue by avv-github** [blind-coder/rcmcarddav#219]
Hello,
Nice job on providing possible integration with owncloud :)

1° I installed RC a couple of months ago, never had a chance to had it run, ut with version 3.0.0 I reached up to a solution.
BUT I had to disable both set_option lines:
76:             ////$dbh->set_option('ignore_key_errors', true);
88:             ////$dbh->set_option('ignore_key_errors', null);
Reason: missing method found...
Dunno what  impact it might have on you plugin? Or fix needed, or else?

2° Would it be possible some day to send vCard ? Could be a nice addon

May thanks already.

Cheers,

Alain

**Comment by blind-coder** [comment]
Which version of roundcube are you running?

An option to send vCards would be great, but this plugin is not the correct place for it. It should be a general option for ANY addressbook, no matter which backend is used.

**Comment by avv-github** [comment]
Thank you for answering.

You sure are right, I was just wondering for sending from the address book iteslf -) This is not important so far.

The current version is the package for jessie, which sits at 0.9.5.
I know ore recent version are available from git, but stays in the distro.

Cheers

**Comment by mstilkerich** [comment]
Roundcube 0.9 is not supported by the plugin and does not retrieve updates by the roundcube project. Please use at least roundcube 1.2, the latest 1.4 is recommended.
