### ISSUE TITLE
Settings panel unavailable

### ISSUE THREAD

**Issue by alfredbuehler** [blind-coder/rcmcarddav#222]
Roundcube 1.3.6
carddav 3.0.0

I have installed v3.0.0, deleted all the carddav_* tables from the database. After logging in, selecting Settings-CardDAV leads to a infinitely spinning cursor (Loading...). The panel remains empty.

The logfiles are checked, no success. Did I miss something?

**Comment by blind-coder** [comment]
Is there anything in the browser console? On FF, press F12 to open it.

**Comment by alfredbuehler** [comment]
After retrying few days later, it works like a charm. 
I assume, the issue was related to the browsers cache.
