### ISSUE TITLE
required php is higher than in roundcube/roundcubemail-docker

### ISSUE THREAD

**Issue by maja68** [blind-coder/rcmcarddav#223]
Hi there,

the [roundcube/roundcubemail-docker](https://github.com/roundcube/roundcubemail-docker) includes php 5.6.11 but this plugin requires 5.6.18 and therefore can not be installed.

Is there a reason to require 5.6.18 or would be 5.6.11 just good enough?

Cheers.

**Comment by blind-coder** [comment]
5.6.18 was the latest one I have to test. There is an option in confing.inc.php to disable the version check, but those are unsupported.
