### ISSUE TITLE
SQL Error in 0005-changemysqlut8toutf8mb4

### ISSUE THREAD

**Issue by Offerel** [blind-coder/rcmcarddav#224]
There is a SQL error i the MySQL migration script:

`DB Error: [1054] Unknown column 'sortorder' in 'carddav_addressbooks' (SQL Query: ALTER TABLE carddav_addressbooks CHANGE `sortorder` `sortorder` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci)`

There is no such column in the database table. After that, the migration ends successfully but takes a really really long time for only a handful off 2500 contacts on a raspberry pi 3b. The column does not exist in the table after the migration.

**Comment by e-dschungel** [comment]
In my DB there is no sortorder, too.
