### ISSUE TITLE
(update) Updating card on server failed

### ISSUE THREAD

**Issue by Geonov** [blind-coder/rcmcarddav#228]
Hello.

**My config :** Roundcube Webmail 1.3.6 + carddav 3.0.2 + Nextcloud 13.0.4

I can successfully see and use my Nextcloud Contacts (from https://xxxxx.xxx:443/remote.php/dav/addressbooks/users/yyyyyy/contacts/)  but I cant create / update / move a contact.

**carddav.warn logfile :** `(update) Updating card on server failed`

Any ideas to debug this ?

Note : No issue with Thunderbird + CardBook plugin and the same Calendar URL.

**Comment by blind-coder** [comment]
Can you give me an example vcard file?
Also, enable DEBUG and DEBUG_HTTP in carddav_common.php and then check the logfiles again after an operation. It should give a lot more information.

**Comment by Geonov** [comment]
Thanks for the DEBUG tip.

Maybe an Apache misconfiguration ?
[log.txt](https://github.com/blind-coder/rcmcarddav/files/2144348/log.txt)

I tried to disable these lines in Apache config without success :
`#Header unset Pragma`
`#FileETag None`
`#Header unset ETag`

**Comment by blind-coder** [comment]
Can you provide the request as well? Make sure to mask the Authorization header.
The ETags are provided by NextCloud, not apache.

**Comment by Geonov** [comment]
My bad : reload Apache wasn't enough but restart did the trick.

`FileETag None`
`Header unset ETag`

were the problem.
