### ISSUE TITLE
Cannot install via release tarball

### ISSUE THREAD

**Issue by r1web** [blind-coder/rcmcarddav#230]
When I attempt to install via the release tarball, I get the following error:

`[18-Jul-2018 23:50:22 America/Toronto] PHP Fatal error:  Uncaught Error: Class 'Httpful\Bootstrap' not found in /var/www/foobar/mailz/plugins/carddav/carddav_common.php:25
Stack trace:
#0 /var/www/foobar/mailz/plugins/carddav/carddav_backend.php(22): require_once()
#1 /var/www/foobar/mailz/plugins/carddav/carddav.php(122): require_once('/var/www/inarab...')
#2 /var/www/foobar/mailz/program/lib/Roundcube/rcube_plugin_api.php(99): carddav->init()
#3 /var/www/foobar/mailz/program/include/rcmail.php(135): rcube_plugin_api->init(Object(rcmail), 'login')
#4 /var/www/foobar/mailz/program/include/rcmail.php(79): rcmail->startup()
#5 /var/www/foobar/mailz/index.php(43): rcmail::get_instance(0, NULL)
#6 {main}
  thrown in /var/www/foobar/mailz/plugins/carddav/carddav_common.php on line 25`

Any ideas?

**Comment by mstilkerich** [comment]
No response by issue author, closing.
