### ISSUE TITLE
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /[...]/plugins/carddav/carddav_backend.php on line 517

### ISSUE THREAD

**Issue by raoulbhatia** [blind-coder/rcmcarddav#231]
Please let me know how I can add more details here.  This is currently the only thing that I see in my PHP error logs.

Environment:
- Ubuntu 18.04.1 LTS
- PHP 7.2.7-0ubuntu0.18.04.2
- Nginx 1.14.0-0ubuntu1
- Nextcloud 13.0.5.2 (stable) w/ Contacts 2.1.5

Thanks,
Raoul

**Comment by hannob** [comment]
The code in question:
```
        // XXX workaround for a roundcube bug to support roundcube's displayname setting
        // Reported as Roundcube Ticket #1488394
        if(count($cols)>0) {
                if(!in_array('firstname', $cols)) {
                        $cols[] = 'firstname';
                }
                if(!in_array('surname', $cols)) {
                        $cols[] = 'surname';
                }
        }
        // XXX workaround for a roundcube bug to support roundcube's displayname setting
```

So from reading this it looks like this is code trying to handle some ancient roundcube bug. Roundcube Ticket #1488394 is here https://github.com/roundcube/roundcubemail/issues/3721 and it claims to be fixed.

Can this just be removed?

**Comment by raoulbhatia** [comment]
Thanks for pointing this out - i will give it a try.

**Comment by raoulbhatia** [comment]
The error has disappeared but I didn't verify if all my contacts have been imported sanely.

**Comment by blind-coder** [comment]
I have removed the code block in question and it works fine here as well.

Thank you for the report, and the fix!
