### ISSUE TITLE
Account for create_save_data_from_vcard() returning false

### ISSUE THREAD

**Issue by leofeyer** [blind-coder/rcmcarddav#237]
The `carddav_backend::create_save_data_from_vcard()` method returns `false` on failures, however, the code always treats the return value as array. This results in:

```
Invalid argument supplied for foreach() in roundcube/plugins/carddav/carddav_backend.php on line 792
```

The method should either return an empty array in case of a failure or the `$save_data === false` case needs to be handled in all places where `create_save_data_from_vcard()` is called.

**Comment by mstilkerich** [comment]
This is fixed on the v4 branch.
