### ISSUE TITLE
"(from preset" prefix not translated

### ISSUE THREAD

**Issue by madmath03** [blind-coder/rcmcarddav#244]
When using presets, the text "_(from preset <preset_name>)_" is appended after the addressbook name in the configuration screen:
https://github.com/blind-coder/rcmcarddav/blob/443ec4c213db5f2a3c9279b50d476f82d011eb45/carddav.php#L444

Either remove "_from preset_" or translate it.

**Comment by blind-coder** [comment]
Fixed this. Thanks for the report!
