### ISSUE TITLE
Presets URL are always fixed

### ISSUE THREAD

**Issue by madmath03** [blind-coder/rcmcarddav#245]
Unlike what is written in the documentation, the presets URL are always fixed:
https://github.com/blind-coder/rcmcarddav/blob/443ec4c213db5f2a3c9279b50d476f82d011eb45/carddav.php#L317-L318

This is actually quite a problem in some cases : for instance, if you are using NextCloud Contacts App, the URL usually contains the username, but things turn out differently the user is coming from an external system (like a LDAP server). In this case, the URL contains the randomly generated ID of the user, making it impossible to use without editing the username part.

What was the reason to block this feature ?

**Comment by blind-coder** [comment]
That sounds like a badly configured LDAP connection. I'm using ownCloud with an LDAP server as backend. Users log in to ownCloud with email address and ldap password which gets looked up with a filter '(&((mail=%u)(memberOf=cn=owncloud-users,*))' and the users resulting carddav space is:

https://server.name/remote.php/carddav/addressbooks/username%40server.name/default

The idea behind the preset URLs was to give users access to corporate directories where having the user edit this information usually causes helpdesk tickets.

**Comment by madmath03** [comment]
@blind-coder you're not completely wrong when you mention LDAP configuration.

By default, Nextcloud uses the LDAP UUID for its internal username. At first, we did not changed this configuration, but even if we change it now, this will only affect new users: "_old_" users will still have a random internal name.

I get your point about the use case you described, but wouldn't it be enough to just document it and let admins decide ?

**Comment by blind-coder** [comment]
I'm open to giving the option.
Would you agree that negating the behaviour for the URL makes sense? Ie: URL is fixed unless configured not to be, all other's are not fixed unless configured to be?
Something along an option "unfixURL".

**Comment by madmath03** [comment]
Why not.
As long as we have the possibility to edit the default behavior, it's fine by me :wink:

**Comment by blind-coder** [comment]
Implemented in https://github.com/blind-coder/rcmcarddav/commit/7ff95746a007e503354082c24c546d35b52bd11c
