### ISSUE TITLE
carddav groups confusion

### ISSUE THREAD

**Issue by henrythemouse** [blind-coder/rcmcarddav#249]
I've just recently returned to using roundcubemail, upgrading to 1.3.7 and rcmcarddav 3.0.3.
I was a bit confused by the checkbox for using the "modern" group method. I think I have that straightened out now.

"modern group mechanism" = use category field for group names
"old RCMCardDAV groups" = use Apple's group vcards to list members
 
Is that correct?

This initially seemed backwards to me, as I thought I'd read that Apple's method had been adopted as the official method going forward (carddav 4.0).

Thanks for a great carddav client solution.

**Comment by mstilkerich** [comment]
Hello,
you got that right, VCard 4 adopted Apple's extension of handling groups as separate address objects on the VCard server. I also never liked the "modern" in the description of this option.

In v4, RCMCarddav transparently supports both types of groups when retrieved from the server, the configuration setting only determines what type of group is created when new groups are created by rcmcarddav.

**Comment by henrythemouse** [comment]
When you mention "In v4", do you mean to say that there is a v4 or rcmcarddav? Or that there will soon be such a version? Or were you referring to VCard 4?

**Comment by mstilkerich** [comment]
Sorry for the confusion. I'm talking about version 4 of rcmcarddav which I am currently working on:

https://github.com/blind-coder/rcmcarddav/tree/v4
