### ISSUE TITLE
Address books multiplies

### ISSUE THREAD

**Issue by n3storm** [blind-coder/rcmcarddav#252]
Roundcube 1.4-beta, debian 9, php 7.2 apache2.

We create a couple of addressbooks in Nextcloud 14, eg. MyTest1, MyTest2, MyTest3 (all same user)

Then we go to Roundcube RcmCarddav settings and add those addressbooks.
First one is added OK.

But when we add the second one we end up having 3:
MyTest1, MyTest2, MyTest1 (MyTest2)

If we add the third one we get 9.

We can see multiplication both in settings and in Adressbook view.

Deleting works ok and extra addressbooks remains deleted (or disabled), so looks like a adding only issue.

WARNING: next time I add MyTest2 (after deleting MyTest2 and all duplicate) MyTest2 is created correctly WITHOUT DUPLICATES.

POST DATA looks ok to me. Every addressbook value is sent like this 18_cd_url..., and the new addressbook is sent like new_cd_url ...

Logs carddav.log and carddav.warn.log are silent on this.

File carddav/config.inc.php is untouched (everything commented).

Anybody else experienced this?

**Comment by blind-coder** [comment]
That's a feature, not a bug.
Carddav allows for the 'discovery' of addressbooks associated with a 'principal' (user, usually).
For own/nextCloud that means if you enter the URL:
https://f.q.d.n/remote.php/dav/addressbooks/users/username/
then RCMCardDAV will attempt to discover all the addressbooks associated with that username and add each one as "Name entered in form (Name returned by server)".
If you instead enter the full URL to the addressbook collection like this:
https://f.q.d.n/remote.php/dav/addressbooks/users/username/default/
then only this one addressbook will be added with the name you entered in the form.
