### ISSUE TITLE
Does not sync Google contacts.

### ISSUE THREAD

**Issue by Artem2710** [blind-coder/rcmcarddav#255]
@Does not sync Google contacts. The plugin creates records and address books. If you create a contact in the address book created by this plugin on the roundcube side, then these contacts are displayed in Google contacts. If you create contacts in Google contacts, they are not synchronized into the address book created by the plugin. Log files are not created, debug in the carddav_common file is enabled. The server's web log also does not write anything. Tell me what could be the problem?

**Comment by blind-coder** [comment]
I've already answered and closed this in #254 so pleae do not open further issues on this.
