### ISSUE TITLE
Roundcube not working after Carddav installation

### ISSUE THREAD

**Issue by TheBB23** [blind-coder/rcmcarddav#257]
I installed roundcube on my webserver.
Now I want to add the carddav plugin.
I cannot use composer on my webserver.
When I install the plugin,
after installation the website is not available anymore. HTTP Error 500 is shown instead.
This happens exactly after i add carddav to the plugins array.
I get this error in the log files: `[16-Mar-2019 11:43:12 Europe/Berlin] PHP Fatal error:  Class 'Httpful\Bootstrap' not found in /var/www/vhosts/hostingxxxxxxxxxxxx.netcup.net/domain.tld/plugins/carddav/carddav_common.php on line 25`

The carddav_common.php line 25 looks like that in my installation:
`\Httpful\Bootstrap::init();`
What am i missing?
I am completely lost and tried to solve this for couple of days now.
Thank you

**Comment by blind-coder** [comment]
Please follow the installation instructions here: https://github.com/blind-coder/rcmcarddav/blob/master/README.md#installation

**Comment by Sanookmakmak** [comment]
>  Class 'Httpful\Bootstrap' not found

I have it as well and i followed the installation instructions as mentioned above.

But i did not install php5-curl because i use PHP 7.2 (Ubuntu 18.04.2)

**Comment by TheBB23** [comment]
Ok i was not answering to your post blind-coder because I exactly followed these steps. Installing roundhouse without the plugin was no problem but not what I wanted. 
I was not able to get it working. But now I use rainloop.  
I miss the possibility to create groups there in my contacts, but cardDav is working perfectly.
