### ISSUE TITLE
CardDAV plugin receiving 404 errors from Google - related to Roundcube 1.4 RC?

### ISSUE THREAD

**Issue by darren12345** [blind-coder/rcmcarddav#258]
I noticed that my CardDAV plugin - previously working fine with my G Apps account - had stopped syncing. It was about the same time I upgraded my Roundcube installation to the 1.4 release candidate so it might be related.

I've turned debug on in carddav_common.php and I see errors such as this:
```
<d:href>/carddav/v1/principals/my@email/lists/default/7ce3a46c0b9bc640</d:href>
  <d:propstat>
   <d:status>HTTP/1.1 200 OK</d:status>
   <d:prop>
    <d:getetag>"2019-02-28T01:49:18.255-08:00"</d:getetag>
   </d:prop>
  </d:propstat>
  <d:propstat>
   <d:status>HTTP/1.1 404 Not Found</d:status>
   <d:prop>
    <d:getcontenttype/>
   </d:prop>
  </d:propstat>
 </d:response>
 <d:response>
```
I was running CardDAV 3.0.1 and have tried upgrading to 3.0.3 with the same result.

UPDATE: Although the contact list in RC is empty, if I create a contact it does get synced to Google. So the authentication etc is correct, it's just pulling the contacts off Google's servers that is failing.

Further update: Plumbing that URL straight into a web browser allows me to authenticate and download the vcard. If I try it with wget or curl from the same server as RC, I get an "authentication failed" error, not a 404. So why is CardDAV encountering that error?

**Comment by blind-coder** [comment]
I have no experience using CardDAV with Google, and as such do not support it. There is a dedicated google contacts plugin, though, as far as I know.

If you figure it out, please let me know.

**Comment by mstilkerich** [comment]
Google's CardDAV implementation deviates from the RFCs in several aspects. The v4 development branch works with Google Contacts again (as long as they still support Basic auth).
