### ISSUE TITLE
Roundcubemail not working after enabling carddav

### ISSUE THREAD

**Issue by milan-007** [blind-coder/rcmcarddav#260]
I have RCM 1.3.8 on apache 2.4 / php 7.2 ( opensuse leap 15 ).
after installing carddav 3.0.3.tar.gz ( about 700kB), setting up ownership and adding carddav into $plugins .. I get white page if try load roundcube. Firefox's devtool show me 500 internal server error occurs. Server is my own. 

Rouncube log 
PHP Fatal error:  Uncaught Error: Class 'Httpful\Bootstrap' not found in /xxxx/roundcubemail-1.3.8/plugins/carddav/carddav_common.php:25
I search some solution, but nothing helps me. 
'Library' Httpfull is present in oundcubemail-1.3.8/plugins/carddav/vendor/nategood .... 
 
Disabling carddav via $plugins variable RCM works again.

I also try install it via composer, but I'm not familiar with this way ... I not found  ` composer.json` and `composer.phar` ( as you wrote in install instruction ). ... ough ... these files present in carddav tarball ....  Must I use these files ?

**Comment by Sanookmakmak** [comment]
>  I get white page if try load roundcube.

I have it as well.

**Comment by milan-007** [comment]
Hi,
Yesterday -after while - I decide try RCM carddav last time or blow them into bin.
Unpacking archive again, then enabling in RCM ( via $plugins), I forgot anythnig to do  ( user/group change, any config settings up ) and then logout / login into RCM.
Surprisingly, RCM does not show me "white page of death", but first page take a while.  I suspect something ( maybe database creation ? ) take a work  Oh shit, I forgot define ( for all users ) our company vcard source ... what now ? Nothing ... database was created, some errors was in log ( I thing undefined sources of vcard cause them ) bur RCM works! 
In Settings I see  Carddav item... 
Now I define source ... then relog RCM and I see shared non-editable contacts as I want.

I'm not sure if key is NOT CONFIGURE before first run or what ( maybe coder know ) but this way I resuscitate RCM carddav .... Maybe it helps you, folks.
Excuse my English, not my language, no school lessons ...

**Comment by FredMa01** [comment]
I have RCM 1.2.3 on Debian 9. PHP 7.0.33 an Apache 2.4.25
After installing Carddav, I get a white page when I load roundcube and this error in logs :
```
PHP Fatal error:  Uncaught Error: Class 'Httpful\Bootstrap' not found in /usr/share/roundcube/plugins/carddav/carddav_common.php:25
Stack trace:
#0 /usr/share/roundcube/plugins/carddav/carddav_backend.php(22): require_once()
#1 /usr/share/roundcube/plugins/carddav/carddav.php(122): require_once('/usr/share/roun...')
#2 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(99): carddav->init()
#3 /usr/share/roundcube/program/include/rcmail.php(135): rcube_plugin_api->init(Object(rcmail), 'mail')
#4 /usr/share/roundcube/program/include/rcmail.php(79): rcmail->startup()
#5 /usr/share/roundcube/index.php(43): rcmail::get_instance(0, NULL)
#6 {main}
  thrown in /usr/share/roundcube/plugins/carddav/carddav_common.php on line 25

```
 I follow this explanations :
-  Via composer:  Add "roundcube/carddav": "dev-master" to composer.json file 
- Install with php composer.phar install.
- Install the curl php extension  : sudo apt-get install php-curl
- Enable RCMCardDAV in Roundcube:with the file roundcube/config/config.inc.php and add carddav to the array $config['plugins'].
- Create a directory symlink from /var/lib/roundcube/plugins/carddav/ to /usr/share/roundcube/plugins/carddav/

Thanks for your help...
Fred

**Comment by FredMa01** [comment]
No answers ;(
The problem is with the line 25 : \Httpful\Bootstrap::init();
PHP Fatal error:  Uncaught Error: Class 'Httpful\Bootstrap' not found in /usr/share/roundcube/plugins/carddav/carddav_common.php:25

I don't what can I do with my debian 9....

Thanks
FRed

**Comment by FredMa01** [comment]
Hi, to fix my problem, I tried to use the release version of carddav.
cd /usr/share/roundcube/plugins/ :
wget https://github.com/blind-coder/rcmcarddav/releases/download/v3.0.3/carddav-3.0.3.tar.bz2
tar xjf carddav-3.0.3.tar.bz2
I have files : /usr/share/roundcube/plugins/carddav
I copy config file :
cp -p /usr/share/roundcube/plugins/carddav/config.inc.php.dist /etc/roundcube/plugins/carddav/config.inc.php.dist

No white page with roundcube but carddav doesn't accessible...
I have this error :
PHP Error: Failed to load plugin file /var/lib/roundcube/plugins/roundcube/roundcube.php in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 173

An idea to help me ?
Fred

**Comment by blind-coder** [comment]
If you get the "white page of death", then somewhere along the installation instructions, you either missed a step or a step failed, because that hints at a missing dependency.
