### ISSUE TITLE
Configure rcmcarddav get my ldap address-book 

### ISSUE THREAD

**Issue by winnertako** [blind-coder/rcmcarddav#264]
Hi, 

It's not a issue but I didn't find anything about that. 

Its possible configure de rcmcarddav to share my ldap adreessbook?

Thank you all

**Comment by blind-coder** [comment]
Hi,

this plugin only supports CardDAV addressbooks.
Try here: https://lmgtfy.com/?q=roundcube+ldap+addressbook

**Comment by winnertako** [comment]
Hi, 
The plugin cant't expose the address book I've configured on my roundcube?
