### ISSUE TITLE
Different CardDav corporate dependant of domain of mail..

### ISSUE THREAD

**Issue by kprkpr** [blind-coder/rcmcarddav#266]
Hi,
In our roundcube, we can login with two domain different.. I have a Domain carddav that I can see only in one of the two domains because, well, is not a good idea to the other domain to see it.. What can I do??

**Comment by blind-coder** [comment]
If I understand you correctly, you have two different domains hosted on the same roundcube instance. Now you want to have a preset addressbook that is visible only to users of one domain, but not the other.
This fairly easy to achieve: Assuming the domain you want a preset addressbook for is "corporate.local", you add the following in config.inc.php:

```php
if (preg_match('/@corporate.local$/', $_SESSION['username'])){
$prefs['corporate'] = array(
  'name'         =>  'Corporate Addressbook',
  'username'     =>  '%u',
  'password'     =>  '%p',
  'url'          =>  'https://owncloud.coporate.local/',

  // optional attributes
  'active'       =>  true,
  'readonly'     =>  true,
  'refresh_time' => '01:00:00',

  // attributes that are fixed (i.e., not editable by the user) and
  // auto-updated for this preset
  'fixed'        =>  array( 'name','username','url' ),

  // always require these attributes, even for addressbook view
  'require_always' => ['email'],

  // hide this preset from CalDAV preferences section so users can't even
  // see it
  'hide' => false,
);
}
```

**Comment by kprkpr** [comment]
Perfect!
Maybe there has to be in config.inc.php comments by default, works as expected
Thanks
