### ISSUE TITLE
uids in tar

### ISSUE THREAD

**Issue by 532910** [blind-coder/rcmcarddav#271]
tar archives should be created with ```--owner=0 --group=0``` otherwise users need `chown` after extracting under root.

Compare:

```
# tar --numeric-owner -tvf carddav-3.0.3.tar.bz2 | head -1
drwxr-xr-x 1000/1000         0 2018-10-01 10:24 carddav/

# tar -tvf carddav-3.0.3.tar.bz2 | head -1                
drwxr-xr-x blindcoder/blindcoder 0 2018-10-01 10:24 carddav/
```

```
# tar --numeric-owner -tvf linux-5.3.9.tar.xz | head -1
drwxrwxr-x 0/0               0 2019-11-06 15:09 linux-5.3.9/

# tar -tvf linux-5.3.9.tar.xz | head -1                
drwxrwxr-x root/root         0 2019-11-06 15:09 linux-5.3.9/
```

**Comment by mstilkerich** [comment]
Probably a good idea, yes. Or you could use --no-same-owner when extracting.

**Comment by 532910** [comment]
Is this fixed?

**Comment by mstilkerich** [comment]
There is nothing to fix right now. We don't change existing releases. There is no script that builds the tarball. For future releases, it'll be considered if they still are released via tarball.
