### ISSUE TITLE
All settings should be fixed for hidded presets.

### ISSUE THREAD

**Issue by 532910** [blind-coder/rcmcarddav#272]
All settings should be `fixed` in case of `hide => true`.

**Comment by mstilkerich** [comment]
These config settings have two different aspects:

- Inability of the user to change settings - this is achieved for all settings of a preset using hide, whereas fixed can be used for individual settings.
- Automatic update of settings from changes to a preset configuration: This is configured using the fixed setting.

It may be difficult to find a use case where you want to hide the preferences from the user and still apply auto update only to some of the settings. But maybe such uses exists. If you want auto-update for all settings, simply add them as fixed settings.

-> I prefer to keep it as is. What you intend to do is possible by configuration already. Changing the behavior removes a configuration possibility that someone might use.
