### ISSUE TITLE
DB Error "no such table: carddav_migrations" on the first login

### ISSUE THREAD

**Issue by 532910** [blind-coder/rcmcarddav#275]
On the first login I got:

```
DB Error: [1] no such table: carddav_migrations (SQL Query: SELECT * FROM carddav_migrations WHERE filename IN ('0000-dbinit','0000-sample','0001-categories','0002-increasetextfieldlengths','0003-fixtimestampdefaultvalue','0004-fixtimestampdefaultvalue','0005-changemysqlut8toutf8mb4')) in /srv/www/roundcubemail-1.4.0/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=login&_action=login)
```

But all works fine.

**Comment by mstilkerich** [comment]
Hello,

 this is expected. It simplifies the installation of the plugin for the server admin as the plugin will init its tables on user logon, but the very first time a database error will be logged as the plugin discovers its tables have not been created yet. The error is logged by roundcube, we cannot suppress it.
