### ISSUE TITLE
deprecation warning about unparenthesized ? operator

### ISSUE THREAD

**Issue by hannob** [blind-coder/rcmcarddav#277]
I'm getting these warnings in my PHP logs (PHP 7.4):

```
PHP Deprecated:  Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in [path]/plugins/carddav/carddav.php on line 352

**Comment by hannob** [comment]
FWIW:
This patch
https://github.com/blind-coder/rcmcarddav/pull/287/commits/b6679133b0314346bd181c14fc9fffca038b265c
can be applied to the latest release to silence the warning.

It seems this will be fixed with version 4:
https://github.com/blind-coder/rcmcarddav/commit/7d2e2c60630722ec9ec1c936358f3a703eb2e8d9
However v4 is not released yet and the commit on the v4 branch does not apply to the latest release.

**Comment by mstilkerich** [comment]
This is fixed in v4 as already stated above.
