### ISSUE TITLE
No addressbook found and HTTP error code 405 with Nextcloud

### ISSUE THREAD

**Issue by viciousvex** [blind-coder/rcmcarddav#281]
Hey,

when adding new addressbooks to CardDAV I keep getting "no addressbook found" ("Kein Adressbuch gefunden"). CardDAV URLs I try are:

`https://example.com:40443/remote.php/dav/addressbooks/users/USERNAME/contacts/`
and
`https://example.com:40443/.well-known/carddav`

The log states:
```
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (retrieve_addressbooks) SEARCHING https://example.com:40443/.well-known/carddav (Depth: 0)
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (cdfopen) retrieve_addressbooks requesting https://example.com:40443/.well-known/carddav as user USERNAME [RL 5]
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (cdfopen) Code: 301
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (cdfopen) success: array (
  'status' => 301,
  'headers' =>
  Httpful\Response\Headers::__set_state(array(
     'headers' =>
    array (
      'Date' => 'Wed, 15 Jan 2020 16:23:02 GMT',
      'Server' => 'Apache/2.4.29 (Ubuntu)',
      'Strict-Transport-Security' => 'max-age=15552000; includeSubDomains',
      'Referrer-Policy' => 'no-referrer',
      'X-Content-Type-Options' => 'nosniff',
      'X-Download-Options' => 'noopen',
      'X-Frame-Options' => 'SAMEORIGIN',
      'X-Permitted-Cross-Domain-Policies' => 'none',
      'X-Robots-Tag' => 'none',
      'X-XSS-Protection' => '1; mode=block',
      'Location' => 'https://example.com:40443/remote.php/dav/',
      'Content-Length' => '327',
      'Content-Type' => 'text/html; charset=iso-8859-1',
    ),
  )),
  'body' => '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://example.com:40443/remote.php/dav/">here</a>.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at example.com Port 40443</address>
</body></html>
',
)
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (retrieve_addressbooks) SEARCHING https://example.com:40443/.well-known/carddav (Depth: 0)
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (cdfopen) retrieve_addressbooks requesting https://example.com:40443/.well-known/carddav as user USERNAME [RL 5]
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (cdfopen) Code: 301
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (cdfopen) success: array (
  'status' => 301,
  'headers' =>
  Httpful\Response\Headers::__set_state(array(
     'headers' =>
    array (
      'Date' => 'Wed, 15 Jan 2020 16:23:02 GMT',
      'Server' => 'Apache/2.4.29 (Ubuntu)',
      'Strict-Transport-Security' => 'max-age=15552000; includeSubDomains',
      'Referrer-Policy' => 'no-referrer',
      'X-Content-Type-Options' => 'nosniff',
      'X-Download-Options' => 'noopen',
      'X-Frame-Options' => 'SAMEORIGIN',
      'X-Permitted-Cross-Domain-Policies' => 'none',
      'X-Robots-Tag' => 'none',
      'X-XSS-Protection' => '1; mode=block',
      'Location' => 'https://example.com:40443/remote.php/dav/',
      'Content-Length' => '327',
      'Content-Type' => 'text/html; charset=iso-8859-1',
    ),
  )),
  'body' => '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://example.com:40443/remote.php/dav/">here</a>.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at example.com Port 40443</address>
</body></html>
',
)
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (retrieve_addressbooks) SEARCHING https://example.com:40443/ (Depth: 0)
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (cdfopen) retrieve_addressbooks requesting https://example.com:40443/ as user USERNAME [RL 5]
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (cdfopen) Code: 405
[15-Jan-2020 17:23:02 +0100]: <1p9vrbjr> DISCOVERY: (cdfopen) success: array (
  'status' => 405,
  'headers' =>
  Httpful\Response\Headers::__set_state(array(
     'headers' =>
    array (
      'Date' => 'Wed, 15 Jan 2020 16:23:02 GMT',
      'Server' => 'Apache/2.4.29 (Ubuntu)',
      'Strict-Transport-Security' => 'max-age=15552000; includeSubDomains',
      'Referrer-Policy' => 'no-referrer',
      'X-Content-Type-Options' => 'nosniff',
      'X-Download-Options' => 'noopen',
      'X-Frame-Options' => 'SAMEORIGIN',
      'X-Permitted-Cross-Domain-Policies' => 'none',
      'X-Robots-Tag' => 'none',
      'X-XSS-Protection' => '1; mode=block',
      'Set-Cookie' => 'SOME_COOKIE; path=/; secure; HttpOnly,oc_sessionPassphrase=SOME_PASSPHRASE; path=/; secure; HttpOnly,__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax,__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict',
      'Expires' => 'Thu, 19 Nov 1981 08:52:00 GMT',
      'Cache-Control' => 'no-store, no-cache, must-revalidate',
      'Pragma' => 'no-cache',
      'Content-Security-Policy' => 'default-src \'self\'; script-src \'self\' \'nonce-SOME_NONCE\'; style-src \'self\' \'unsafe-inline\'; frame-src *; img-src * data: blob:; font-src \'self\' data:; media-src *; connect-src *; object-src \'none\'; base-uri \'self\';',
      'Content-Length' => '0',
      'Content-Type' => 'text/html; charset=UTF-8',
    ),
  )),
  'body' => '',
)
```

I switched to the current Nextcloud 17.0.2 and Roundcube 1.4.2 the other day. Installed carddav with sudo composer require roundcube/carddav

```
$ sudo composer require roundcube/carddav
[sudo] password for XXX:
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^3.0 for roundcube/carddav
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing sabre/vobject (3.5.3): Downloading (100%)
  - Installing nategood/httpful (0.3.0): Loading from cache
  - Installing roundcube/carddav (3.0.3): Downloading (100%)
Do you want to activate the plugin carddav? [N|y] y
Updated local config at /var/www/example.com/roundcube/config/config.inc.php
Creating plugin config file
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
```

I use custom port 40443 for HTTPS on my server and I don't allow HTTP. I replaced my URLs with example.com and my user with USERNAME.

Does someone have an idea what I could be doing wrong?

Regards

**Comment by patrickbretz** [comment]
Hi,

I have the same problem with the same versions of RC and NC with the same messages. I used the dev-version of carddav meanwhile, but I have still the error.

Regards

**Comment by patrickbretz** [comment]
Hi,

I tested some things and I think I found the problem: I thing it's a problem with the keys in the header array of the responses. I found in the following code

public function checkAndParseXML($reply) {
		if(!is_array($reply))
			return false;

		if(!self::check_contenttype($reply['headers']['content-type'], ';(text|application)/xml;'))
			return false;

		$xml = new SimpleXMLElement($reply['body']);
		$this->registerNamespaces($xml);
		return $xml;
	}

$reply['headers']['content-type'] is used, but in the response I found 'Content-Type', so the correct value is not found and false is returned --> the processing is interrupted. 

I changed the code to $reply['headers']['Content-Type'] and it worked again, but this is not the solution. I think the internal generation of the arrays or the acces to the internal arrays must be modified. Maybe I will find the correct place...

**Comment by mstilkerich** [comment]
Hello,

sorry for the late reply. Is this issue still relevant to you @viciousvex @patrickbretz?

**Comment by cnmicha** [comment]
@mstilkerich I'm facing the same issue and am looking forward to a fix :pray:

**Comment by mstilkerich** [comment]
Please try the v4 branch, it works with nextcloud and has case-insensitive http headers access.

See install instructions here:
https://github.com/blind-coder/rcmcarddav/tree/v4

**Comment by cnmicha** [comment]
It works! Thanks a lot!

**Comment by viciousvex** [comment]
Looks good for me. The module bails at one contact and stops at import number 300 of 484 contacts though. But that seems to be another misbehaviour concerning badly formatted vCards. Thanks for your help, Michael!

`[15-Jul-2020 11:52:53 +0200]: <sngk8bup> Errors occurred during the refresh of addressbook 2: Exception: [1366] Incorrect string value: '\xF0\x9F\x98\x82\x0D\x0A...' for column 'vcard' at row 1 in /var/www/XXX/roundcube/plugins/carddav/src/Database.php:289`

**Comment by mstilkerich** [comment]
Hello,

 would you mind turning on debugging in config.inc.php (both for carddav and http, the config.inc.php.dist file shows how to do it)? With a bad VCard, it should not get to the point where that vcard is stored to the database. Apparently, Sabre DAV already successfully parsed the VCard retrieved from the server.

The logs are in roundcube/logs, carddav.log and carddav_http.log. The carddav.log should not contain confidential data, but the HTTP log will have your addressdata. But if you could share the VCard causing the error from the HTTP log, it might already help. You should see in carddav.log entries like "Changed Individual <URI>". The last of these entries would contain the URI of the vcard causing the exception, which again you can search for in the http log to find the VCard data.

**Comment by mstilkerich** [comment]
Closing because no reply in >14 days. Feel free to reopen if you are still affected an interested in resolution of the issue.
