### ISSUE TITLE
No connection to Nextcloud contacts

### ISSUE THREAD

**Issue by Hariko50** [blind-coder/rcmcarddav#282]
I cannot connect to my Nextcloud contacts. It also does not report address book found or not found. Only in the log file is the following:
 <7193e144> DISCOVERY: (retrieve_addressbooks) SEARCHING https://nextcloud.aaaaaaaa.de:443/remote.php/dav/addressbooks/users/aaaa@bbbbbbbbbbb.de/contacts/ (Depth: 0)
 <7193e144> DISCOVERY: (cdfopen) retrieve_addressbooks requesting https://nextcloud.aaaaaaaa.de:443/remote.php/dav/addressbooks/users/aaaa@bbbbbbbbbbb.de/contacts/ as user aaaa@bbbbbbbbbbb.de [RL 5]

**Comment by mstilkerich** [comment]
Hello, sorry for the late reply. Are you still interested in this?

**Comment by mstilkerich** [comment]
No reply, closing the issue as I cannot reproduce it. If the issue persists, please comment / reopen.
