### ISSUE TITLE
installation on Ubuntu bionic

### ISSUE THREAD

**Issue by hase-berlin** [blind-coder/rcmcarddav#283]
I am a bit lost here.
I am a bit of a noob regarding PHP - it had not really crossed my path so far.
And Yes, Ubuntu is not Debian - and I would switch to Buster in a heartbeat if my server provider had that on tap. But they only serve Ubuntu...

The installation instructions refer to a tarball, but I can not find one for download.
The "download" link on https://www.benjamin-schieder.de/ just points to https://github.com/blind-coder/rcmcarddav
There we find a .zip download, but that is obviously not the tarball with all the dependencies included (see below).

So I tried the "easy" way: installed the composer package with apt-get.
then tried to install carddav with
sudo -u www-data composer require roundcube/carddav
after this, a new directory /var/lib/roundcube/plugins/vendor/roundcube/carddav appears.
(actually: after a bit of a permission struggle, as the Ubuntu roundcube-plugins package installs everythig as root:root).
The line from the instructions (php composer.phar install.) fails with "Could not open input file: composer.phar" and a file by that name is nowhere to be found (find / -name composer.phar -print results in nothing)

Adding the line
'carddav',
to the $config['plugins']  array in /etc/roundcube/config.inc.php results in 

PHP Error: Failed to load plugin file /var/lib/roundcube/plugins/carddav/carddav.php

which makes perfect sense as the install is in 
/var/lib/roundcube/plugins/vendor/roundcube/carddav

Changing the config from 'carddav' to 'vendor/roundcube/carddav' changes the error to
Failed to load plugin file /var/lib/roundcube/plugins/vendor/roundcube/carddav/vendor/roundcube/carddav.php
Hmm. why is the vendor/roundcube part getting duplicated?

So back to 'carddav' in the plugins array and a symlink?
ln -s vendor/roundcube/carddav/ carddav
adds the symlink and now the plugin is found, as the error shows

```
[31-Jan-2020 12:53:45 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Httpful\Bootstrap' not found in /var/lib/roundcube/plugins/vendor/roundcube/carddav/carddav_common.php:25
Stack trace:
#0 /var/lib/roundcube/plugins/vendor/roundcube/carddav/carddav_backend.php(22): require_once()
#1 /var/lib/roundcube/plugins/vendor/roundcube/carddav/carddav.php(122): require_once('/var/lib/roundc...')
#2 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(99): carddav->init()
#3 /usr/share/roundcube/program/include/rcmail.php(135): rcube_plugin_api->init(Object(rcmail), 'mail')
#4 /usr/share/roundcube/program/include/rcmail.php(79): rcmail->startup()
#5 /usr/share/roundcube/index.php(43): rcmail::get_instance(0, NULL)
#6 {main}
  thrown in /var/lib/roundcube/plugins/vendor/roundcube/carddav/carddav_common.php on line 25

```
Aha. or rather Aha?
I am lost, I am guessing, the Httpful\bootstrap class is in vendor/nategood/httpful/bootstrap.php but now the carddav plugin is not aware of the vendor/* directory structure
BTW: the symlink idea stems from the fact that all entries in /var/lib/roundcube/plugins are symlinks to subdirectories of /usr/share/roundcube/plugins/ except for the "vendors" directory

So lets try the "tarball" thingy again with a .zip from github, as that is a closest to atarball I can find.
Download using the clone or download link on the github page results in a master.zip.
Unzip this and rename to carddav inside /var/lib/roundcube/plugins results in the plugin found but again the Httpful\Bootstrap missing.

So this is obviously not the mentioned tarball including all the dependencies?

I need some pointers here:
- where is the all-included tarball to be found? Or
- how would the composer install way work if it did?

Maybe we can work on dome more complrehensive install docs together?
merci
hase

**Comment by hase-berlin** [comment]
rechecked again the composer install
sudo -u www-data composer require roundcube/carddav actually pulls 
nategood/httpful
sabre/vobject
roundcube/carddav.
So it does install the dependencies, just not in a place there roundcube/carddav searches for them?

hase

**Comment by mstilkerich** [comment]
Hello,

  you have to run composer either in the root directory of the roundcube installation. Is this issue still relevant to you?

**Comment by mstilkerich** [comment]
Closing this as it is not an issue with RCMCardDAV but an installation issue.

If you are still interested, please try installing the v4 branch following the instructions on: https://github.com/blind-coder/rcmcarddav/tree/v4

If you still have issues with that, please comment / reopen and I will help.
