### ISSUE TITLE
rcmcarddav not work roundcube 1.4.3

### ISSUE THREAD

**Issue by Michael2222** [blind-coder/rcmcarddav#284]
Hello,
I have upgrade roundcube from 1.4.2 to 1.4.3 and the plugin does not load.

The error.log shows:
`[02-Apr-2020 20:31:24 +0200]: PHP Error: Failed to load plugin file /var/www/html/mail/plugins/caldav_calendar/caldav_calendar.php in /var/www/html/mail/program/lib/Roundcube/rcube_plugin_api.php on line 174 (POST /mail/?_task=mail&_action=refresh)`

Can you help me?
Regards
  Michael

**Comment by helmut72** [comment]
> **caldav**_calendar

rcm**carddav**

?

**Comment by bovender** [comment]
I don't know about that caldav_calendar bit above, but I can confirm that the plugin does not work with Roundcube 1.4.3. I have a dockerized setup.

Unfortunately, the log file is not really very helpful:

```
PHP Error: Failed to load plugin file /var/www/html/plugins/carddav/carddav.php in /var/www/html/program/lib/Roundcube/rcube_plugin_api.php on line 174
```

**Comment by Michael2222** [comment]
> I don't know about that caldav_calendar bit above,

Sorry for the confusion. I have copy the wrong error message from the log file.
But the key message remains. carddav do not work with my 1.4.3 roundcube application.

**Comment by blackm** [comment]
@Michael2222 I am running Roundcube Webmail 1.4.3 with carddav 2.0.4 and it is working for me.

So what is your environment? chmod set correct after the update?

**Comment by blackm** [comment]
....just updated to carddav 3.0.3 and this is also working.

What I had to do, is had to run the commands from point 2 in the INSTALL file...checksum failed :-/ but continue anyway...

**Comment by bovender** [comment]
> had to run the commands from point 2 in the INSTALL file

OK, my bad... My Docker container did not properly install the plugin, so please excuse my hijacking this issue. And thanks for the heads-up.

**Comment by alexanderdd** [comment]
So this issue is fixed?

@Michael2222

**Comment by mstilkerich** [comment]
No reply by issue creator, closing as the issue cannot be reproduced.
