### ISSUE TITLE
rcmcarddav on Synology MailStation (Roundcube) curl_init() undifined?

### ISSUE THREAD

**Issue by METEO64** [blind-coder/rcmcarddav#285]
Hello,

The plugins rcmcarddav is installed on this way:
    **wget** https://github.com/blind-coder/rcmcarddav/releases/download/v3.0.3/carddav-3.0.3.tar.bz2 6
    **tar** xjf carddav-3.0.3.tar.bz2

Here is the configuration:
root@toto:/var/packages/MailStation/target/mail/plugins/carddav# **curl -V**
curl 7.54.0 (x86_64-pc-linux-gnu) libcurl/7.54.0 OpenSSL/1.0.2r zlib/1.2.8 c-ares/1.12.0 libssh2/1.7.0 nghttp2/1.24.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug TrackMemory IPv6 Largefile NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy
root@toto:/var/packages/MailStation/target/mail/plugins/carddav# **php -v**
PHP 5.6.11 (cli) (built: May 10 2019 05:24:58)
Copyright (c) 1997-2015 The PHP Group Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**'carddav'** is added in **config.inc.php**
// List of active plugins (in plugins/ directory)
$config['plugins'] = array('mailstation', 'managesieve', 'advanced_search', 'automatic_addressbook', 'emoticons','newmail_notifier', 'archive', '**carddav**');

The CardDAV option is fine in the parameters section on Roundcube.
Then I set the name, user, password and URL for the CardDAV.
The problem is : when I want to save the carddav url, there is a blanck page and there is this error on the roundcube logs (**vi** errors) : 
**PHP Fatal error:  Call to undefined function Httpful\curl_init()** in /volume1/@appstore/MailStation/mail/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php on line 843

Where am I wrong? 

Thank you for help !

**Comment by mstilkerich** [comment]
It looks like you do not have the php-curl extension installed.

`php -m` gives you a list of all installed php extensions. The list should include curl, otherwise you have to install it.

**Comment by mstilkerich** [comment]
Closing this as it is not an issue with RCMCardDav but lack of installed dependencies (php-curl extension is missing).
