### ISSUE TITLE
Auto update doesnt work

### ISSUE THREAD

**Issue by eranyanay** [blind-coder/rcmcarddav#286]
Im using carddav 3.0.3 with roundcube 1.4.2, it fetched my contacts properly after saving the config, but auto update doesn't work.

What triggers it? Is there an external command using the backend to trigger it?
Perhaps a missing library?
Is there a a proper way to debug it?

**Comment by halacs** [comment]
For me plugin does not work at all. If I set debug log to true I see this in the log file:


```
<d:response>
  <d:href>/carddav/v1/principals/{my email address}/lists/default/{something like a hash}</d:href>
  <d:propstat>
   <d:status>HTTP/1.1 200 OK</d:status>
   <d:prop>
    <d:getetag>"2020-03-16T22:22:06.371-07:00"</d:getetag>
   </d:prop>
  </d:propstat>
  <d:propstat>
   <d:status>HTTP/1.1 404 Not Found</d:status>
   <d:prop>
    <d:getcontenttype/>
   </d:prop>
  </d:propstat>
 </d:response>
```

**Comment by mstilkerich** [comment]
@eranyanay: You configure a refresh time interval in the settings of the addressbook. A synchronization of the addressbook will be performed whenever this time has passed since the last synchronization and an action in the addressbook is invoked. So there is no synchronization in the background, and nothing special for you to setup except setting the synchronization time .

**Comment by halacs** [comment]
@mstilkerich do you have any idea what can be wrong in my case?

I have set the update interval to 00:10:00. In the logs I see this error:

`[04-May-2020 21:27:49 +0200]: <rejhjdch> An error (status 400) occured while retrieving vcards for addressbook 2. Synchronization aborted.`

**Comment by mstilkerich** [comment]
@halacs Are you using the master version of the plugin? Which CardDAV server? (Have you tried adding the addressbook as a new one in case some URLs changed on the server?)

Can you provide a log of the full HTTP traffic? For that you'd have to install the master version of MY branch and turn on DEBUG_HTTP in carddav_common.php. It will then write a log file logs/carddav_http that contains the full HTTP data exchange. Before posting, please redact (but do not remove) the Authorization headers in the log file, e.g. to
Authorization: Basic REDACTED

**Comment by halacs** [comment]
hi,

I use Google as carddav server. It was working earlier.
I use master branch from this url: https://github.com/blind-coder/rcmcarddav.git
Below you can found logs with debug information.
I'm not sure which branch do you mean so I hope this will help for you.

[carddav.warn.log](https://github.com/blind-coder/rcmcarddav/files/4579149/carddav.warn.log)
[carddav.log](https://github.com/blind-coder/rcmcarddav/files/4579150/carddav.log)

**Comment by mstilkerich** [comment]
According to the Google docs, the CardDAV API requires authentication with OAuth2, which is unfortunately currently not supported by the plugin. I guess this is why it’s not working anymore.

**Comment by halacs** [comment]
Oh, that seems to be a good reason :( Thank you for your efforts!

Do you plan maybe to implement it in the near future? :)

**Comment by mstilkerich** [comment]
@halacs It turns out Google has not disabled basic auth yet and postponed disabling without a new date because of COVID19. If you want to serve as beta tester, you can try the v4 development branch, where Google Contacts should work. If you find issues, I would appreciate feedback.

See installation instructions here: https://github.com/blind-coder/rcmcarddav/tree/v4

**Comment by halacs** [comment]
Hi @mstilkerich ,

Thanks for the heads up! Sure! I'm happy to do it together!
What has been changed? Did you add OAuth login maybe?

I switched to the v4 branch then when I opened roundcube I got empty page and this error in the log (empty page should be fine if error, but fyi):


```
25-Jun-2020 21:20:53 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function nocacheing_headers() on null in /xx/yy/zz/public_html/mail/index.php:46
Stack trace:
#0 {main}
  thrown in /xx/yy/zz/public_html/mail/index.php on line 46
[25-Jun-2020 21:22:39 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'MStilkerich\CardDavAddressbook4Roundcube\RoundcubeLogger' not found in /xx/yy/zz/public_html/mail/plugins/carddav/carddav.php:124
Stack trace:
#0 /xx/yy/zz/public_html/mail/program/lib/Roundcube/rcube_plugin_api.php(100): carddav->init()
#1 /xx/yy/zz/public_html/mail/program/include/rcmail.php(137): rcube_plugin_api->init(Object(rcmail), 'login')
#2 /xx/yy/zz/public_html/mail/program/include/rcmail.php(78): rcmail->startup()
#3 /xx/yy/zz/public_html/mail/index.php(43): rcmail::get_instance(0, NULL)
#4 {main}
  thrown in /xx/yy/zz/public_html/mail/plugins/carddav/carddav.php on line 124
```

(sorry for the slow response, I have a baby)

**Comment by mstilkerich** [comment]
Hi,

 I did not add OAuth2, but Google has not disabled HTTP basic auth yet (https://gsuiteupdates.googleblog.com/2020/03/less-secure-app-turn-off-suspended.html). But I did rewrite basically all of the code that interacts with the CardDAV server. Unfortunately, Google has a buggy CardDAV implementation, it does not adhere to the RFCs in several aspects. There is also a blog post by the sabre/dav author (https://evertpot.com/google-carddav-issues/), and it seems that these issues still persist.

Concerning the error: It doesn't find the class RoundcubeLogger, which is part of that branch. It should be loaded by composer's autoloader. Did you install the plugin using composer in the roundcube root directory?

Assuming your roundcube installation is at /xx/yy/zz/public_html/mail, it would look something like

```
cd /xx/yy/zz/public_html/mail
vim composer.json # -> change the version number for the plugin so that it looks like: "roundcube/carddav": "v4.x-dev"
composer.phar update --no-dev
ls plugins/carddav/src/RoundcubeLogger.php # should output the filename
```

**Comment by halacs** [comment]
Yes, most probably running of composer.phar is the problem. I just checked it is a dependency manager for PHP. It installs dependencies into the vendor folder, right?


I guess my composer.json should looks like this in the public_html/mail folder:
```
{
    "name": "roundcube/roundcubemail",
    "description": "The Roundcube Webmail suite",
    "license": "GPL-3.0+",
    "repositories": [
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net"
        }
    ],
    "require": {
        "php": ">=5.4.0",
        "pear/pear-core-minimal": "~1.10.1",
        "pear/auth_sasl": "~1.1.0",
        "pear/net_idna2": "~0.2.0",
        "pear/mail_mime": "~1.10.0",
        "pear/net_smtp": "~1.8.1",
        "pear/crypt_gpg": "~1.6.3",
        "pear/net_sieve": "~1.4.3",
        "roundcube/plugin-installer": "~0.1.6",
        "masterminds/html5": "~2.5.0",
        "endroid/qr-code": "~1.6.5",
        "kolab/net_ldap3": "~1.1.1",
        "roundcube/carddav": "v4.x-dev"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8.36 || ^5.7.21"
    },
    "suggest": {
        "mkopinsky/zxcvbn-php": "^4.4.2 required for Zxcvbn password strength driver"
    }
}
```

And here is the output of composer.phar:
```
public_html/mail$ sudo plugins/carddav/composer.phar update --no-dev                                                                                                              
Do not run Composer as root/super user! See https://getcomposer.org/root for details                                                                                                                               
Loading composer repositories with package information                                                                                                                                                             
Updating dependencies                                                                                                                                                                                              
Your requirements could not be resolved to an installable set of packages.                                                                                                                                         
                                                                                                                                                                                                                   
  Problem 1                                                                                                                                                                                                        
    - Installation request for roundcube/carddav v4.x-dev -> satisfiable by roundcube/carddav[v4.x-dev].
    - roundcube/carddav v4.x-dev requires mstilkerich/carddavclient dev-master -> satisfiable by mstilkerich/carddavclient[dev-master] but these conflict with your requirements or minimum-stability.
  Problem 2
    - kolab/net_ldap3 v1.1.3 requires pear/net_ldap2 >=2.0.12 -> satisfiable by pear/net_ldap2[v2.2.0].
    - kolab/net_ldap3 v1.1.1 requires pear/net_ldap2 >=2.0.12 -> satisfiable by pear/net_ldap2[v2.2.0].
    - kolab/net_ldap3 v1.1.3 requires pear/net_ldap2 >=2.0.12 -> satisfiable by pear/net_ldap2[v2.2.0].
    - pear/net_ldap2 v2.2.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - pear/net_ldap2 v2.2.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - Installation request for kolab/net_ldap3 ~1.1.1 -> satisfiable by kolab/net_ldap3[v1.1.1, v1.1.3].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/15-xml.ini
    - /etc/php/7.2/cli/conf.d/20-apcu.ini
    - /etc/php/7.2/cli/conf.d/20-apcu_bc.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-curl.ini
    - /etc/php/7.2/cli/conf.d/20-dom.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gd.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-intl.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-mbstring.ini
    - /etc/php/7.2/cli/conf.d/20-mysqli.ini
    - /etc/php/7.2/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-simplexml.ini
...
...
...
```

**Comment by mstilkerich** [comment]
For issue 1:
Since the plugin and the depended on lib is not released as stable, it is not installed because of the minimum-stability defaults to stable. Add the following lines to composer.json:
```
        "minimum-stability": "dev",
        "prefer-stable": true
```
This allows composer to install development packages, but will still prefer stable versions of packages if available.
I wasn't aware of that and will also update the install instruction.

For issue 2: as you obviously don't use LDAP, you can simply remove "kolab/net_ldap3": "~1.1.1" from the required packages in composer.json. Alternatively you could install the needed php extensions.

Another note: You need to use an application-specific password for Google, not your main account password. The main account password will not work. You can create an application-specific password  in your Google Account settings -> Security -> Signing in to Google -> App passwords

**Comment by halacs** [comment]
So far so good :) Thanks a lot!

After I changed the composer.json in the root (public_html/mail directory) as you suggested composer.pear could run. I opened roundcube on web, went to carddav settings page. Settings I made for the earlier version (months ago) were still there. I opened the contacts which was a bit slow (several seconds, maybe even ~30sec, were needed) but it seems all of my contacts are there as expected. I have waited a few minutes, reopened contacts page and this time sync was fast as I expected.

**Comment by mstilkerich** [comment]
Glad to hear it works :-)

The initial sync will take longer as the entire addressbook is downloaded. 30 seconds is pretty long, but I guess you either have a lot of photos stored with your contacts, or a huge number of contacts, or both :-)

I'm aware of more issues with the sync with Google contacts - the diff-based sync-collection report that should ensure fast follow-up syncs always returns an empty result in my experiments, even if I made changes either from rcmcarddav or through the Google contacts Web-Interface. That means with the current state, you will not get updates. I'll see how to workaround this, unfortunately, the answer to the sync-collection report looks like a valid answer for the case that no changes occurred, so I'll likely have to add some special handling of Google... It will then still be fast than the initial sync, as the fallback methods means to query the version identifier ("ETag") of all the cards in the addressbook, but then only those that have a different version identifier than the locally cached ones will need to be downloaded.

Of course, if you observe any more issues, please let me know.

**Comment by halacs** [comment]
Okay, I wont expect updates for now. Thanks for the heads-up! I highly appreciate your efforts! If I see any more issue I will let you know!

**Comment by mstilkerich** [comment]
I've now figured out the issue with Google and just added a workaround (composer.phar update --no-dev). When updating, check in the composer output that it installs version 0.1.0 of mstilkerich/carddavclient.

I've also reported the issues with their sync-collection implementation to Google: https://issuetracker.google.com/issues/160190530

**Comment by mstilkerich** [comment]
@eranyanay: Maybe this fixes your issue, too.

**Comment by halacs** [comment]
I have updated from dev-master 4513448 to v0.1.0 successfully.
Here is the output for reference.

```
www-data@hn:~$ ./composer.phar update --no-dev
Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 4 updates, 0 removals
  - Updating pear/mail_mime (1.10.8 => 1.10.9): Downloading (100%)         
  - Updating psr/http-client (1.0.0 => 1.0.1): Downloading (100%)         
  - Downgrading mstilkerich/carddavclient (dev-master 4513448 => v0.1.0):  Checking out 1b9bf66964
  - Updating roundcube/carddav v4.x-dev (e4a9310 => f6d3d44):  Checking out f6d3d44bdf
Writing lock file
Generating autoload files
3 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

```

**Comment by eranyanay** [comment]
Thanks @mstilkerich 
Rebased to `v4.x-dev` release and it appears to be behaving well
Every time I go to the addressbok it takes a few seconds and it loads a refreshed list.
I did notice this error, preventing it from refreshing the update time, as a result every usage of the contacts list is delayed due to an attempt to refresh it:
```
[13-Jul-2020 12:42:22 +0000]: <b6dfc246> DB Error: [1292] Incorrect datetime value: 'now()' for column `mailcow`.`mailcow_rc1carddav_addressbooks`.`last_updated` at row 1 (SQL Query: UPDATE mailcow_rc1carddav_addressbooks SET last_updated='now()' WHERE `id` = '2') in /web/rc/program/lib/Roundcube/rcube_db.php on line 543 (GET /rc/?_task=addressbook&_action=list&_source=carddav_2&_remote=1&_unlock=loading1594644048400&_=1594644046501)
```

**Comment by mstilkerich** [comment]
Uh, thanks, that I broke very recently. If you run composer update you should get a fix.

**Comment by eranyanay** [comment]
Ah, ok.
Do you suggest doing `composer update` within the plugin directory (`roundcube/plugins/carddav`) or in the main roundcube folder?

I reinstalled everything today, and to best of my knowledge I'm updated.
Can you clarify in what way to update more specifically?

**Comment by eranyanay** [comment]
Ah, It was literally two hours ago.
I git pulled to the latest commit.
Thanks!

**Comment by mstilkerich** [comment]
Yes, I fixed it after you reported it :-)

Please run composer in the root directory of roundcube, it is a specific type of composer package (roundcube plugin) that will be installed to the proper place.
