### ISSUE TITLE
Password field too short

### ISSUE THREAD

**Issue by tborychowski** [blind-coder/rcmcarddav#296]
Would you consider changing the password field from `varchar(255)` to `text`?
I tried to integrate https://github.com/monicahq/monica with my roundcube instance to get the contacts but they authenticate with username & API tokens, which are ~1000 chars.

I hacked it - manually changed the password field type in mysql database from `varchar(255)` to `text` and was able to successfully add my carddav addressbook from monicahq.
But it would be good to not have to do that :-)

**Comment by mstilkerich** [comment]
Hello,

  I see no problem with  the change. On postgres there seems to be no difference concerning storage between varchar and text anyway. In MySQL InnoDB the text values seem to be stored out-of-row in separate records, thus performance of queries querying the password field may decrease. However, the most critical addressbook query that is basically executed with every roundcube request, the password field is not selected.

-> Will consider to change this.
