### ISSUE TITLE
cURL certificate issue when trying to use iCloud with v.4

### ISSUE THREAD

**Issue by Cardo1** [blind-coder/rcmcarddav#298]
I’ve tried using the v.4 plugin, however unfortunately it’s failing to sync with iCloud.  When trying to add the address book, I’m getting these errors:

--------
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
[16-Aug-2020 17:31:24 +0100]: <q3ri034q> "PROPFIND /.well-known/carddav HTTP/1.1" NULL
>>>>>>>>
PROPFIND /.well-known/carddav HTTP/1.1
Content-Length: 215
User-Agent: GuzzleHttp/7
Host: contacts.icloud.com
Depth: 0
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <DAV:current-user-principal/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<

--------
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
[16-Aug-2020 17:31:24 +0100]: <q3ri034q> "PROPFIND / HTTP/1.1" NULL
>>>>>>>>
PROPFIND / HTTP/1.1
Content-Length: 215
User-Agent: GuzzleHttp/7
Host: contacts.icloud.com
Depth: 0
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <DAV:current-user-principal/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<

--------
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
[16-Aug-2020 17:31:24 +0100]: <q3ri034q> "PROPFIND /co HTTP/1.1" NULL
>>>>>>>>
PROPFIND /co HTTP/1.1
Content-Length: 215
User-Agent: GuzzleHttp/7
Host: contacts.icloud.com
Depth: 0
Prefer: return=minimal

<?xml version="1.0"?>
<DAV:propfind xmlns:DAV="DAV:" xmlns:CARDDAV="urn:ietf:params:xml:ns:carddav" xmlns:CS="http://calendarserver.org/ns/">
 <DAV:prop>
  <DAV:current-user-principal/>
 </DAV:prop>
</DAV:propfind>

<<<<<<<<

--------
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

I appreciate it’s a cURL error, but I don’t have any issues with any other apps that use cURL.

**Comment by mstilkerich** [comment]
Hmm, I'm guessing here: Do you have the certification authority certificate in your CA path? (GeoTrust Global CA)
On debian / ubuntu, you can get it by installing the ca-certificates package.

iCloud works fine for me on Ubuntu 20.04.

**Comment by Cardo1** [comment]
Ca-certificates is installed. I don’t have this issue with version 3.x with the iCloud fix.
This is on Debian 10.

**Comment by mstilkerich** [comment]
v3 uses a different HTTP client library (Httpful, v4 uses Guzzle), but both in the end use curl. Neither v3 nor v4 specify any CA path, so both should use the system default path => I have no idea why v4 shows this issue when v3 does not.

What does `curl -v https://contacts.icloud.com` output for you? It should show the used CA path and whether verification of the server certificate succeeded. If it did, it should look like this:

```
*   Trying 2a01:b740:a41:205::d:443...
* TCP_NODELAY set
* Connected to contacts.icloud.com (2a01:b740:a41:205::d) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=contacts.icloud.com; O=Apple Inc.; ST=California; C=US
*  start date: Dec  9 19:51:25 2019 GMT
*  expire date: Jan  7 20:01:00 2021 GMT
*  subjectAltName: host "contacts.icloud.com" matched cert's "contacts.icloud.com"
*  issuer: CN=Apple IST CA 2 - G1; OU=Certification Authority; O=Apple Inc.; C=US
*  SSL certificate verify ok.
```

**Comment by mstilkerich** [comment]
I did a debian install to a VM and have the same issue.

It's a Debian issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596

Workaround from that ticket until they fix it:
```
wget --no-check-certificate -c https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem   \
    && mkdir /usr/local/share/ca-certificates/extra                                                                       \
    && mv GeoTrust_Global_CA.pem /usr/local/share/ca-certificates/extra/GeoTrust_Global_CA.crt                            \
    && update-ca-certificates
```

I tried, worked for me.

**Comment by Cardo1** [comment]
> I did a debian install to a VM and have the same issue.
> 
> It's a Debian issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596
> 
> Workaround from that ticket until they fix it:
> 
> ```
> wget --no-check-certificate -c https://www.geotrust.com/resources/root_certificates/certificates/GeoTrust_Global_CA.pem   \
>     && mkdir /usr/local/share/ca-certificates/extra                                                                       \
>     && mv GeoTrust_Global_CA.pem /usr/local/share/ca-certificates/extra/GeoTrust_Global_CA.crt                            \
>     && update-ca-certificates
> ```
> 
> I tried, worked for me.

Thanks, this has sorted it.  Apologies, my google skills let me down!

**Comment by mstilkerich** [comment]
Glad to hear it works :-)
