### ISSUE TITLE
Encrypted Password not getting updated

### ISSUE THREAD

**Issue by silvereye** [blind-coder/rcmcarddav#301]
I am using the latest code available and facing some strange issue, once I change the password for my Roundcube account contacts sync and creation stopped working. I have checked the database and found an encrypted password not getting updated which is causing this issue. deleted entry from the carddav_addreddbook table fixes the issue.

**Comment by mstilkerich** [comment]
It's a known caveat of the encrypted passwords. Please see 
doc/ADMIN-SETTINGS.md on a description of the issue ans your alternative options concerning password storage.

**Comment by mstilkerich** [comment]
Btw just reinserting the password and saving the addressbook in the settings is enough, you don't have to delete the entire addressbook.

**Comment by silvereye** [comment]
> Btw just reinserting the password and saving the address book in the settings is enough, you don't have to delete the entire addressbook.

I am not allowing users to create their own address book hence this doesn't apply in my case.

**Comment by silvereye** [comment]
> Btw just reinserting the password and saving the addressbook in the settings is enough, you don't have to delete the entire addressbook.

Thanks, It resolved my issue.
