### ISSUE TITLE
Preset adressbook not created, RC + rmcarddav v4 + sqlite3

### ISSUE THREAD

**Issue by pgnd** [blind-coder/rcmcarddav#304]
( referred from https://github.com/blind-coder/rcmcarddav/issues/239 )

I've setup Roundcube +
```
composer show | grep carddav
 mstilkerich/carddavclient            v0.1.6             CardDAV client library to discover and synchronize with CardDAV...
 roundcube/carddav                    v4.0.0             CardDAV adapter for connecting to CardDAV-enabled addressbooks
```

my RC db is sqlite3

my CardDAV backend is Radicale3

carddav with manually added addressbooks works as expected

addressbook presets are ignored; no preset-referenced existing addressbooks are seen/added in RC.

with

```
roundcubemail/plugins/carddav/config.inc.php
	<?php

		$prefs['_GLOBAL']['fixed'] = false;
		$prefs['_GLOBAL']['hide_preferences'] = false;
		$prefs['_GLOBAL']['pwstore_scheme'] = 'encrypted';

		$prefs['_GLOBAL']['loglevel']      = \Psr\Log\LogLevel::DEBUG;
		$prefs['_GLOBAL']['loglevel_http'] = \Psr\Log\LogLevel::DEBUG;

		$prefs['Contacts.Shared'] = [
			'name'         =>  'Contacts.Shared',
			'url'          =>  'https://frontend.example.com:11111/dav/shared%40example.net/11111111-1111-1111-1111-111111111111/',
			'username'     =>  'shared@example.net',
			'password'     =>  'changemedavpass',
			'active'       =>  true,
			'readonly'     =>  false,
			'refresh_time' => '00:01:00',
			'fixed'        =>  array( 'username', 'password', 'refresh_time', 'url'),
			'hide' => false
		];
```

credentials _are_ double-checked/valid.

on server restart + successful login, there's no 'Contact.Shared' addressbook presented/offered.

debug logs from start/login,
```
/var/log/roundcubemail]$ tail -f carddav*
	==> carddav_http.log <==

	==> carddav.log <==
	[23-Sep-2020 07:08:56]: <b0ece56e> carddav::getAddressbook(carddav_2)
	[23-Sep-2020 07:08:56]: <b0ece56e> list_groups(null, 0)
	[23-Sep-2020 07:08:56]: <b0ece56e> carddav::init
	[23-Sep-2020 07:09:00]: <b0ece56e> carddav::init
	[23-Sep-2020 07:09:00]: <b0ece56e> carddav::addPreferencesSection
	[23-Sep-2020 07:09:00]: <b0ece56e> carddav::buildPreferencesPage
	[23-Sep-2020 07:09:01]: <61eaf4aa> carddav::init
	[23-Sep-2020 07:09:01]: <b0ece56e> carddav::init
	[23-Sep-2020 07:09:01]: <b0ece56e> carddav::addPreferencesSection
	[23-Sep-2020 07:09:01]: <b0ece56e> carddav::buildPreferencesPage
```

tho, this^^ doesn't seem particularly verbose ...

**Comment by mstilkerich** [comment]
The login_after hooks are not executed, which includes the initPresets function. What other plugins do you have enabled? There is a known issue concerning the Google 2FA plugin (#175).

**Comment by pgnd** [comment]
ah.

atm, i've
```
$config['plugins'] = array(
    'archive',
    'managesieve',
    'password',
    'zipdownload',
    'twofactor_gauthenticator',
    'carddav',
);
```

**Comment by mstilkerich** [comment]
Maybe it helps if you put twofactor_gauthenticator last in the list.

**Comment by pgnd** [comment]
I'll give that a try ...

iiuc #175, though, it fails to login at all ... whether manual add, or preset?

the case here, atm, is that login to manually added addressbooks is working fine, with 2FA ...

**Comment by mstilkerich** [comment]
The database initialization and migration in case of DB schema changes is also executed in a login_after hook and has more fatal consequences if not carried out. In your case, it seems you added the 2fa plugin after the carddav tables had been created already. The other issue was about that effect.

**Comment by pgnd** [comment]
> Maybe it helps if you put twofactor_gauthenticator last in the list.

with
```
	$config['plugins'] = array(
		'archive',
		'managesieve',
		'password',
		'zipdownload',
-		'twofactor_gauthenticator',
		'carddav',
+		'twofactor_gauthenticator',
	);
```

the preset DOES now appear!

is that _simply_ an issue of plugin-array order?

or an _install_ order dependency?

seems like the former ...

> In your case, it seems you added the 2fa plugin after the carddav tables had been created already

according to my _notes_, 2FA was added 1st.
but, I've been monkeying around ... so I'd need to start clean to verify.

**Comment by mstilkerich** [comment]
Each plugin can register hooks with roundcube that are executed on certain events, such as after login. I assume that roundcube calls the hook functions in the order registered, and initializes the plugin in the order listed in the configuration. That means that with the new ordering, the 2FA's login_after hooks are called after all the other plugins' ones.

The problem with the 2FA plugin is that it captures that hook, i.e. the login_after hook of that plugin does not return and thus no more login_after hooks that may follow in the list would be invoked. I consider this a bug in that plugin, but if this workaround works -> fine. Otherwise, there is also a 2FA plugin by the roundcube creators that does not have this behavior. (I never tried any of these plugins myself).

**Comment by pgnd** [comment]
thx for the explanation

> I consider this a bug in that plugin

I can take it up there

> there is also a 2FA plugin by the roundcube creators that does not have this behavior. 

there _is_ ?  missed that, too!

**Comment by mstilkerich** [comment]
There is the [roundcube-plugin-kolab-2fa](https://github.com/thomascube/roundcube-plugin-kolab-2fa) plugin. But as I said, I never tried any of those, I just saw that that plugin does not use a login_after hook.

I guess this issue can be closed?

**Comment by pgnd** [comment]
> There is the roundcube-plugin-kolab-2fa plugin.

thx. didn't realize that's an 'official' offering.  less active/maintained, at 1st glance.

in any case

>  I never tried any of those

noted.

> I guess this issue can be closed?

as carddav + 2FA isn't an _uncommon_ usecase, and typically _I_ would find myself adding login protections -- i.e. 2FA -- _before_ external addressbooks,

i'd at least suggest documentation in carddav of the requirement.

ideally, an active configuration check ... to ensure that 'carddav' plugin gets added/activated _before_ the 2FA plugin.

if no to either -- then sure, feel free to close.

**Comment by mstilkerich** [comment]
It's the twofactor_gauthenticator plugin that breaks the login_after hooks for other plugins using that hook (not just this one in particular), therefore this configuration constraint should be documented with that plugin. Even then there can still be one plugin behaving in this way, therefore it would be even better to redesign to not contain non-returning hook functions. The kolab plugin seems to demonstrate it's possible.

**Comment by mstilkerich** [comment]
Reference #130
