### ISSUE TITLE
version v4.0.0 seems not to work with my setup, v3.0.3 does

### ISSUE THREAD

**Issue by marcoavnet** [blind-coder/rcmcarddav#307]
Hello,
I use this version:
https://github.com/blind-coder/rcmcarddav/releases/download/v4.0.0/carddav-v4.0.0.tgz

Together with roundcube 1.4.9.

This is the log:

[php7:error] [pid 152] [client ip:49928] PHP Fatal error:  Uncaught Error: Class 'MStilkerich\\CardDavAddressbook4Roundcube\\RoundcubeLogger' not found in /var/www/html/plugins/carddav/carddav.php:81\nStack trace:\n#0 /var/www/html/program/lib/Roundcube/rcube_plugin_api.php(100): carddav->init()\n#1 /var/www/html/program/include/rcmail.php(137): rcube_plugin_api->init(Object(rcmail), 'login')\n#2 /var/www/html/program/include/rcmail.php(78): rcmail->startup()\n#3 /var/www/html/index.php(43): rcmail::get_instance(0, NULL)\n#4 {main}\n  thrown in /var/www/html/plugins/carddav/carddav.php on line 81
ip - - [22/Oct/2020:10:42:10 +0200] "GET / HTTP/1.1" 500 321 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"

**Comment by mstilkerich** [comment]
Hello,

  you need to install the dependencies using composer. Please see the instructions in https://github.com/blind-coder/rcmcarddav/blob/master/doc/INSTALL.md#installation-from-release-tarball

**Comment by marcoavnet** [comment]
Hello,
thanks for the super fast reply.
It works now.
BR
Marco
