### ISSUE TITLE
New account not synced with remote carddav

### ISSUE THREAD

**Issue by kearva** [blind-coder/rcmcarddav#308]
**RCMCardDAV Version:** v4.0.0
**RCM Version:** Docker Image roundcube/roundcubemail:1.4.x-apache

In function checkResyncDue (in src/Addressbook.php), there is a check if it is a long time since last sync.

When a new addressbook is created in the database, last_updated is set to 0. This results in checkResyncDue always beeing larger than zero (in fact it will return current timestamp pluss the value set for refresh_time), which again results that the first sync isn't done before the user adds a contact to the address book.

I suggest to change line [2095](https://github.com/blind-coder/rcmcarddav/blob/fc2b6c97b12782983d64aba7fffb38f3745ff81e/src/Addressbook.php#L2095) from:
```PHP
$ts_lastupd = Database::sqlDateTimeToSeconds($this->config["last_updated"], $ts_now);
```

to:
```PHP
$ts_lastupd = $this->config["last_updated"]?Database::sqlDateTimeToSeconds($this->config["last_updated"], $ts_now):0;
```

This way one can be sure that first access will result in a sync of the addressbook.

**Comment by mstilkerich** [comment]
Thanks for reporting this issue, I can see how this problem occurs with the default value we use in SQLite for the last_updated column.

**Comment by mstilkerich** [comment]
This should be fixed with the commit listed above. I will do some testing and then merge this to master.

**Comment by kearva** [comment]
I have tested your solution and it seems to be working as expected. Thank you for the quick fix.
