### ISSUE TITLE
calendarserver: No connect to addressbook

### ISSUE THREAD

**Issue by controlcde** [blind-coder/rcmcarddav#31]
I´m just using calendarserver and with MacOS, iOS and Android and everything works but if I want to setup RCM with latest (git) version von carddav plugin I couldn´t set up my account.

The URL is: *https://SERVERNAME:8443/addressbooks/__uids__/862350ad-2480-52a9-bd38-80a56ccef907/addressbook/* and if I connect to this URL via browser I get an authentification web site and after login I could see a list of all .vcf. But after setting up in RCM I could see in *carddav.warn*

> DISCOVERY: (cdfopen) Could not read reply header: authentication error: 400 Bad Request

and in my calendarserver logfile I could see

> "PROPFIND /addressbooks/__uids__/862350ad-2480-52a9-bd38-80a56ccef907/addressbook/ HTTP/1.1" 401 141 "-" "RCM CardDAV plugin/1.0.0" i=1 t=12.0 or=8
> "PROPFIND /.well-known/carddav HTTP/1.1" 301 157 "-" "RCM CardDAV plugin/1.0.0" i=0 t=5.3 or=8
> "PROPFIND / HTTP/1.1" 207 630 "-" "RCM CardDAV plugin/1.0.0" i=1 t=2.3 or=8
> "PROPFIND /.well-known/carddav HTTP/1.1" 301 157 "-" "RCM CardDAV plugin/1.0.0" i=0 t=4.2 or=8
> "PROPFIND / HTTP/1.1" 207 1171 "-" "RCM CardDAV plugin/1.0.0" i=1 t=5.9 or=8
> "PROPFIND / HTTP/1.1" 207 630 "-" "RCM CardDAV plugin/1.0.0" i=0 t=2.3 or=8
> "PROPFIND / HTTP/1.1" 207 1171 "-" "RCM CardDAV plugin/1.0.0" i=1 t=5.8 or=8

:cold_sweat:

**Comment by blind-coder** [comment]
I'll close this issue now, the issue_51 branch has been merged into master.
