### ISSUE TITLE
Deleted contact on the server is not deleted locally

### ISSUE THREAD

**Issue by haziegler** [blind-coder/rcmcarddav#313]
If you delete a contact on the server, it's not deleted in the RoundCube database.

Steps to reproduce:
1. Configure NextCloud as source for rcmcarddav. Use the following config in rcmcarddav config.inc.php:
`$prefs['NextCloud'] = array(
        'name'         =>  'NextCloud',
        'username'     =>  '%u',
        'password'     =>  '%p',
        'url'          =>  'https://example.com/remote.php/dav/addressbooks/users/%u/contacts/',
        'active'       =>  true,
        'readonly'     =>  true,
        'refresh_time' => '00:01:00',
        'require_always' => ['email'],
        'hide' => false,
);`
2. Make sure that you are not logged in to RoundCube
3. Create a new contact in NextCloud
4. Log in to RoundCube
5. Check if the new contact has been syncronized (yes, it has)
6. Log out of RoundCube
7. Delete the contact in NextCloud
8. Log into RoundCube
9. Check if the deleted contact still exists (yes, but it shouldn't)

Actual result:
The contact still exists in RoundCube address book (even if refresh_time has already been expired)

Expected result:
If a contact has been deleted from the address book, this change should be syncronized to RoundCube.

Environment:
RoundCube 1.4.9
rcmcarddav: 4.0.1 (updated from 3.0.3 to 4.0.0 to 4.0.1), Note: I haven't checked it this issue also existed in earlier version.
CardDav back end: NextCloud 20.0.1
OS: RHEL 8.2
Webserver: Apache 2.4.37
PHP: 7.3.20
Database: sqlite

carddav log (with loglevel and loglevel_http set to DEBUG):
[2020-11-01 15:16:08]: <nvitr0f0> carddav::init 
[2020-11-01 15:16:08]: <b8m6k4r0> carddav::checkMigrations 
[2020-11-01 15:16:08]: <b8m6k4r0> carddav::initPresets 
[2020-11-01 15:16:08]: <b8m6k4r0> carddav::init 
[2020-11-01 15:16:09]: <b8m6k4r0> carddav::init 
[2020-11-01 15:16:09]: <b8m6k4r0> carddav::init

**Comment by mstilkerich** [comment]
I just tried this (also with nextcloud 20.0.1 and rcmcarddav 4.0.1), it works just fine for me.

Your log looks like no synchronization is carried out, so either you omitted that part or maybe the refresh time was not expired after all. Please check the log again. You can also force a resync in the carddav settings by checking the corresponding checkbox and save.

Your log must show an entry like this if a sync was done (plus you will get up a notification in roundcube as well):
```
[01-Nov-2020 15:32:39 +0100]: <t1q60s78> sync of addressbook 23 (Nextcloud (default)) took 0 seconds 
```

You can also see the time of the last sync in the carddav settings.

**Comment by haziegler** [comment]
The log is complete. There wasn't anything else.

I gave it another try: I wasn't logged in at all today and the sync interval is still set to 1 minute as shown above. After I logged in, I have the same log entries (nothing more, nothing less) - just with the latest time stamp. No sync was done.

Then I checked the CardDAV settings menu: Last sync: 2020-11-01 14:48:48, which was yesterday after I added the new contact. 

I enforced a manual sync, and the entry was removed. However, the automatic sync after the interval has expired seem to work as it should.

**Comment by mstilkerich** [comment]
Hmm ok. There was a change in 4.0.1 concerning the timestamp handling. Note you cannot go back to 4.0.0 without deleting the plugin's tables from the database first because the DB schema changed.

- Does the last updated time and refresh time show correctly in carddav setting web interface?
- Which Database are you using?
- Could you provide the content of the refresh_time and last_updated columns of the carddav_addressbooks table, and the content of the carddav_migrations table?
- Does the issue still occur after the manual refresh?
- Does the problem also occur for a newly created addressbook?

**Comment by haziegler** [comment]
>     * Does the last updated time and refresh time show correctly in carddav setting web interface?

The time stamp in the web interface was correct when I enforced the manual sync. So I assume that the previous one (2020-11-01) was also correct.

>     * Which Database are you using?
sqlite (see bug description above)


>     * Could you provide the content of the refresh_time and last_updated columns of the carddav_addressbooks table, and the content of the carddav_migrations table?

3600|1604333878

1|0000-dbinit|2019-06-12 19:20:19
2|0000-sample|2019-06-12 19:20:19
3|0001-categories|2019-06-12 19:20:19
4|0002-increasetextfieldlengths|2019-06-12 19:20:19
5|0003-fixtimestampdefaultvalue|2019-06-12 19:20:19
6|0004-fixtimestampdefaultvalue|2019-06-12 19:20:19
7|0005-changemysqlut8toutf8mb4|2019-06-12 19:20:19
8|0006-rmgroupsnotnull|2020-09-23 07:46:21
9|0007-replaceurlplaceholders|2020-09-23 07:46:21
10|0008-unifyindexes|2020-09-23 07:46:21
11|0009-dropauthschemefield|2020-09-23 07:46:21
12|0010-increasetextfieldlengths|2020-09-23 07:46:21
13|0011-unifymigrationsidcolumn|2020-09-23 07:46:21
14|0012-fixmysqlconstraints|2020-09-23 07:46:21
15|0013-changemysqlcollationscasesensitive|2020-11-01 13:47:44
16|0014-unifytimestampdefaultvalue|2020-11-01 13:47:44


>     * Does the issue still occur after the manual refresh?

Yes. I created another new contact in NextCloud, logged into RoundCube, and the new contact was automatically right there. I logged out, deleted the contact in NextCloud, waited one more minute to be sure that the refresh time is over, logged into RoundCube again, and the contact is still there.


>     * Does the problem also occur for a newly created addressbook?

Sorry, I don't know. I created a new addressbook in NC and chanced the URL in the plug-in's config.inc.php. After I logged in to RC, the CardDAV settings still show the old URL. Not even an enforced sync changed the URL. It seems the URL was just pulled from config.inc.php at the first time and then stored in the database for the user, and is not checked again.

**Comment by mstilkerich** [comment]
Most of your answers look fine.
Your excerpt from the database shows a refresh_time of 3600 (= 1 hour), although your config.inc.php indeed specifies 1 minute. I guess you also will see '01:00:00' as the update interval value in the web interface, not '00:01:00', right?

So I now tried exactly your configuration, including using sqlite and a preset with exactly the settings you use, but still everything works fine for me. My database also shows 60 for the refresh_time, so I cannot reproduce why yours contains 1 hour, but it sure explains why the sync is not triggered.

By the way, you don't have to log out to resync, any access to the carddav addressbook will trigger a resync when the time has expired. For example, you can go to the addressbooks tab and just click on the nextcloud addressbook to trigger a sync. You also don't have to change anything on the nextcloud side, you will see
1. a log entry that a sync was performed
2. the last updated time in the settings will be updated
3. you will see a popup notification in roundcube that tells you that the addressbook has been synced and how long it took

I am a bit clueless on how to help here.

Maybe you can add the following line to the function checkResyncDue at the very end of `plugins/carddav/src/Addressbook.php`

```php
carddav::$logger->notice("checkResyncDue: due in: $ts_diff, now: $ts_now, last {$this->config['last_updated']}, rt {$this->config['refresh_time']}");
```

So it looks like this:

```php
    private function checkResyncDue(): int                                                                               
    {                                                                                                                    
        $ts_now = time();                                                                                                
        $ts_nextupd = $this->config["last_updated"] + $this->config["refresh_time"];                                     
        $ts_diff = ($ts_nextupd - $ts_now);                                                                              
                                                                                                                         
        carddav::$logger->notice("checkResyncDue: due in: $ts_diff, now: $ts_now, last {$this->config['last_updated']}, rt {$this->config['refresh_time']}");
        return $ts_diff;                                                                                                 
    } 
```

Then you will get log entries that show the data used for each check that determines whether to perform a sync or not.

```
[02-Nov-2020 19:53:39 +0100]: <117018uh> checkResyncDue: due in: -328, now: 1604343219, last 1604342831, rt 60 
[02-Nov-2020 19:53:40 +0100]: <117018uh> sync of addressbook 1 (Nextcloud (default)) took 1 seconds 
[02-Nov-2020 19:53:46 +0100]: <117018uh> checkResyncDue: due in: 54, now: 1604343226, last 1604343220, rt 60 
```

The above shows that for the first entry, the sync is 328 seconds over due, so a sync is performed. The third line then shows that the next sync is due in 54 seconds, so no sync is performed.

**Comment by haziegler** [comment]
> Most of your answers look fine.
> Your excerpt from the database shows a refresh_time of 3600 (= 1 hour), although your config.inc.php indeed specifies 1 minute. I guess you also will see '01:00:00' as the update interval value in the web interface, not '00:01:00', right?

That's interesting. I checked config.inc.php and it really contains refresh_time' => '00:01:00', but the database shows 3600 and the web interface also shows 1h.

This sounds related to the problem I described when I added a new addressbook in NC, changed the link in config.inc.php, but the changes were not visible in RC.

Is it possible that the database entry isn't updated if the config file has been changed (user was logged out during the change)?

Maybe that's the real cause. For testing I changed the interval in the config from 1h to 1m, but if this change was never used because it uses the not-up-to-date database setting, this could explain why the entry wasn't deleted.


> 
> So I now tried exactly your configuration, including using sqlite and a preset with exactly the settings you use, but still everything works fine for me. My database also shows 60 for the refresh_time, so I cannot reproduce why yours contains 1 hour, but it sure explains why the sync is not triggered.
> 
> By the way, you don't have to log out to resync, any access to the carddav addressbook will trigger a resync when the time has expired. For example, you can go to the addressbooks tab and just click on the nextcloud addressbook to trigger a sync. You also don't have to change anything on the nextcloud side, you will see
> 
>     1. a log entry that a sync was performed
> 
>     2. the last updated time in the settings will be updated
> 
>     3. you will see a popup notification in roundcube that tells you that the addressbook has been synced and how long it took
> 
> 
> I am a bit clueless on how to help here.
> 
> Maybe you can add the following line to the function checkResyncDue at the very end of `plugins/carddav/src/Addressbook.php`
> 
> ```
> carddav::$logger->notice("checkResyncDue: due in: $ts_diff, now: $ts_now, last {$this->config['last_updated']}, rt {$this->config['refresh_time']}");
> ```
> 
> So it looks like this:
> 
> ```
>     private function checkResyncDue(): int                                                                               
>     {                                                                                                                    
>         $ts_now = time();                                                                                                
>         $ts_nextupd = $this->config["last_updated"] + $this->config["refresh_time"];                                     
>         $ts_diff = ($ts_nextupd - $ts_now);                                                                              
>                                                                                                                          
>         carddav::$logger->notice("checkResyncDue: due in: $ts_diff, now: $ts_now, last {$this->config['last_updated']}, rt {$this->config['refresh_time']}");
>         return $ts_diff;                                                                                                 
>     } 
> ```
> 
> Then you will get log entries that show the data used for each check that determines whether to perform a sync or not.
> 
> ```
> [02-Nov-2020 19:53:39 +0100]: <117018uh> checkResyncDue: due in: -328, now: 1604343219, last 1604342831, rt 60 
> [02-Nov-2020 19:53:40 +0100]: <117018uh> sync of addressbook 1 (Nextcloud (default)) took 1 seconds 
> [02-Nov-2020 19:53:46 +0100]: <117018uh> checkResyncDue: due in: 54, now: 1604343226, last 1604343220, rt 60 
> ```
> 
> The above shows that for the first entry, the sync is 328 seconds over due, so a sync is performed. The third line then shows that the next sync is due in 54 seconds, so no sync is performed.

**Comment by mstilkerich** [comment]
Hello,

  only fields marked as fixed are automatically updated for a preset, as the value of non-fixed settings may be changed by the user and thus the admin setting only defines the initial value. Url is currently never changed because it may imply problems that the plugin does not currently address. 

You can checkout (ADMIN-SETTINGS.md)[doc/ADMIN-SETTINGS.md] which contains a description on how the admin presets work.

Does this mean your issue is resolved?

**Comment by haziegler** [comment]
Yes, this solves this request.

Thanks for your help and work on this plug-in.
