### ISSUE TITLE
[RCMCardDAV v4.0.1] Migration failed

### ISSUE THREAD

**Issue by Offerel** [blind-coder/rcmcarddav#314]
Hi there,

i have migrated from RCMCardDAV v4.0.0 to RCMCardDAV v4.0.1. After logout, i cant login again to roundcube. In /car/log/roundcube/carddav.log, i get the following error:

```
 [09-Nov-2020 07:32:30 +0100]: <dg0l4o0q> Migration query (
UPDATE carddav_addressbooks2 SET last_updated=strftime('%s', last_updated);) failed: [19] NOT NULL constraint failed: carddav_addressbooks2.last_updated
```
The step `php composer.phar update --no-dev` was executed before. Database is sqlite.

**Comment by mstilkerich** [comment]
Hello,

  can you show the contents of your last_updated (and also refresh_times) columns in your carddav_addressbooks table?

**Comment by Offerel** [comment]
Sure. 
![image](https://user-images.githubusercontent.com/14041522/98509520-a3c99000-2261-11eb-9b2d-e329989796d9.png)

**Comment by mstilkerich** [comment]
Hello,

  the two addressbooks are assigned to two different roundcube users, see the user_id column.

For the first addressbook (id=1), it already contains a timestamp value in seconds - this is the new format. The timestamp is from Friday. My best guess is you updated the code and where still logged in, a refresh was triggered and the timestamp was written in the new format to the database.

To fix it:
  - log out of roundcube
  - adapt last_updated in the first addressbook to a time string as you see in the second one (you can simply copy the string from the 2nd addressbook)
  - update to 4.0.1
  - log into roundcube - now the migration should work
  - afterwards, both the last_updated and the refresh_time should contain values in seconds, e. g. last_updated will have a value similar to what you see in the first one and refresh_time in your case will show 7200.

**Comment by Offerel** [comment]
Hi Micha. Many thx for the fast response. Was a little bit complicated, only with smartphone access to the server, but your description helped to solve the issue. I should remember to logout and wait some time, when i update the next time. Anyway, it works now. Have a nice day and stay save.
