### ISSUE TITLE
Data truncated for column 'refresh_time' at row 1

### ISSUE THREAD

**Issue by meaz** [blind-coder/rcmcarddav#322]
I've set a Preset with `'refresh_time' => '01:00:00',` which is the default parameter.

But that creates issues in my logs:

```
Database::insert (INSERT INTO carddav_addressbooks(name,username,password,url,user_id,active,presetname,refresh_time) VALUES (?,?,?,?,?,?,?,?)) ERROR: [1265] Data truncated for column 'refresh_time' at row 1 
Error adding addressbook from preset Personal: [1265] Data truncated for column 'refresh_time' at row 1 
```

**Comment by mstilkerich** [comment]
Hello,

 thank you for reporting this issue. It should be fixed in the current master branch. Could you please try if it fixes the issue for you?

**Comment by meaz** [comment]
yep it does. Thanks a lot
