### ISSUE TITLE
Recently contacted address book added.

### ISSUE THREAD

**Issue by meaz** [blind-coder/rcmcarddav#323]
I've set a Preset for Nextcloud contact address book.
It works well, but it creates two address books:
- The one I set, `Nextcloud (Contacts)`
- And another one, named: `Nextcloud (Recently contacted)`, that I didn't set myself.

Is that mandatory to have this "recently contacted" book automatically added along with my address book?

**Comment by mstilkerich** [comment]
Hello,

  this works as intended. RCMCardDAV discovers all addressbooks of the user at the server and adds them to the list. Nextcloud serves the recently contacts addressbook like any other addressbook, there is nothing special about it from what RCMCardDAV can see.

However, you can simply deactivate the addressbook in the carddav settings, then it will not show in the addressbooks view and also not be searched / synced.
