### ISSUE TITLE
Please implement support of IM fields

### ISSUE THREAD

**Issue by bitbybit** [blind-coder/rcmcarddav#46]
Hi
Currently carddav plugin does not show IM data (Jabber, ICQ, ...) in "Contact properties" for contacts that already have such fields. And there is no "IM" option under "Add field..." menu in "Add new contact" while in default adressbook "Personal Addresses" we can add IM fields.

**Comment by mstilkerich** [comment]
Implemented on v4.1.

It's difficult to achieve interoperability with other clients, but I tried to make it as good as possible. See doc/devdoc/IMPP.md for some details.
