### ISSUE TITLE
Roundcube 1.0.2 - CardDAV - Baikal 0.2.7: No connect to Adressbook

### ISSUE THREAD

**Issue by HassanMullah** [blind-coder/rcmcarddav#51]
Hello,

i need urgend help for my connection problem. What is exactly the URL, which i have to write in the backup of CardDAV for Roundcube, that CardDAV will find my adressbooks ?

here my logfile:

[06-Aug-2014 22:50:17 +0800](DISCOVERY:): DISCOVERY: (cdfopen) retrieve_addressbooks requesting https://www.fqdn.tld:443/mybaikal/card.php/addressbooks/holger/default/ [RL 5](DISCOVERY:): DISCOVERY: (cdfopen) SendRequest: http_class::__set_state(array(
   'host_name' => 'www.fqdn.tld',
   'host_port' => 443,
   'proxy_host_name' => '',
   'proxy_host_port' => 80,
   'socks_host_name' => '',
   'socks_host_port' => 1080,
   'socks_version' => '5',
   'protocol' => 'https',
   'request_method' => 'PROPFIND',
   'user_agent' => 'RCM CardDAV plugin/1.0.0',
   'accept' => '',
   'authentication_mechanism' => '',
   'user' => NULL,
   'password' => NULL,
   'realm' => NULL,
   'workstation' => NULL,
   'proxy_authentication_mechanism' => '',
   'proxy_user' => NULL,
   'proxy_password' => NULL,
   'proxy_realm' => NULL,
   'proxy_workstation' => NULL,
   'request_uri' => '/mybaikal/card.php/addressbooks/holger/default/',
   'request' => 'PROPFIND /mybaikal/card.php/addressbooks/holger/default/ HTTP/1.1',
   'request_headers' => 
  array (
    'Host' => 'www.fqdn.tld:443',
    'User-Agent' => 'RCM CardDAV plugin/1.0.0',
    'Depth' => '0',
    'Content-Type' => 'application/xml; charset="utf-8"',
    'Authorization' => 'Basic aG9sZ2VyOjE0dWExNG0=',
    'Connection' => 'Keep-Alive',
    'Content-Length' => 241,
  ),
   'request_user' => 'holger',
   'request_password' => 'mysecretpassword',
   'request_realm' => NULL,
   'request_workstation' => NULL,
   'proxy_request_user' => NULL,
   'proxy_request_password' => NULL,
   'proxy_request_realm' => NULL,
   'proxy_request_workstation' => NULL,
   'request_body' => '<?xml version="1.0" encoding="utf-8"?>
<D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:carddav"><D:prop>
    <D:current-user-principal/>
    <D:resourcetype />
    <D:displayname />
    <C:addressbook-home-set/>
/D:prop/D:propfind
',
   'request_arguments' => 
  array (
    'Protocol' => 'https',
    'HostName' => 'www.fqdn.tld',
    'Headers' => 
    array (
      'Host' => 'www.fqdn.tld:443',
      'User-Agent' => 'RCM CardDAV plugin/1.0.0',
      'Depth' => '0',
      'Content-Type' => 'application/xml; charset="utf-8"',
      'Authorization' => 'Basic aG9sZ2VyOjE0dWExNG0=',
      'Connection' => 'Keep-Alive',
    ),
    'AuthUser' => 'holger',
    'AuthPassword' => 'mysecretpassword',
    'HostPort' => 443,
    'RequestURI' => '/mybaikal/card.php/addressbooks/holger/default/',
    'RequestMethod' => 'PROPFIND',
    'Body' => '<?xml version="1.0" encoding="utf-8"?>
<D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:carddav"><D:prop>
    <D:current-user-principal/>
    <D:resourcetype />
    <D:displayname />
    <C:addressbook-home-set/>
/D:prop/D:propfind
',
  ),
   'protocol_version' => '1.1',
   'timeout' => 120,
   'data_timeout' => 0,
   'debug' => 0,
   'log_debug' => 0,
   'debug_response_body' => 1,
   'html_debug' => 0,
   'support_cookies' => 1,
   'cookies' => 
  array (
  ),
   'error' => '',
   'error_code' => 0,
   'exclude_address' => '',
   'follow_redirect' => 0,
   'redirection_limit' => 5,
   'response_status' => '',
   'response_message' => '',
   'file_buffer_length' => 8000,
   'force_multipart_form_post' => 0,
   'prefer_curl' => 1,
   'keep_alive' => 1,
   'sasl_authenticate' => 1,
   'state' => 'RequestSent',
   'use_curl' => true,
   'connection' => NULL,
   'content_length' => 0,
   'response' => 'HTTP/1.1 401 Unauthorized
Date: Wed, 06 Aug 2014 14:50:17 GMT
Server: Apache
X-Powered-By: PHP/5.3.28
Set-Cookie: PHPSESSID=e2178f3c67a9038954eb30a3935ce76b; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
WWW-Authenticate: Digest realm="BaikalDAV",qop="auth",nonce="53e240a95e47f",opaque="df58bdff8cf60599c939187d0b5c54de"
Content-Length: 292
Keep-Alive: timeout=15, max=100
Connection: Keep-Alive
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated/s:exception
  <s:message>No digest authentication headers were found/s:message
  <s:sabredav-version>1.8.7/s:sabredav-version
/d:error
',
   'read_response' => 0,
   'read_length' => 0,
   'request_host' => 'www.fqdn.tld:443',
   'next_token' => '',
   'redirection_level' => 0,
   'chunked' => 0,
   'remaining_chunk' => 0,
   'last_chunk_read' => 0,
   'months' => 
  array (
    'Jan' => '01',
    'Feb' => '02',
    'Mar' => '03',
    'Apr' => '04',
    'May' => '05',
    'Jun' => '06',
    'Jul' => '07',
    'Aug' => '08',
    'Sep' => '09',
    'Oct' => '10',
    'Nov' => '11',
    'Dec' => '12',
  ),
   'session' => 'f1bd21e592a93708b71cf83cfd2f2920',
   'connection_close' => 0,
   'force_close' => 0,
   'connected_host' => 'www.fqdn.tld',
   'connected_port' => 443,
   'connected_ssl' => 1,
))
[06-Aug-2014 22:50:17 +0800](DISCOVERY:): DISCOVERY: (cdfopen) Code: 200
[06-Aug-2014 22:50:17 +0800](DISCOVERY:): DISCOVERY: (cdfopen) success: array (
  'status' => '200',
  'headers' => 
  array (
    'http/1.1 200 ok' => '',
    'date' => 'Wed, 06 Aug 2014 14:50:17 GMT',
    'server' => 'Apache',
    'x-powered-by' => 'PHP/5.3.28',
    'vary' => 'Accept-Encoding',
    'content-length' => '326',
    'content-type' => 'text/html',
  ),
  'body' => '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
<meta http-equiv="expires" content="0">

<script type=\'text/javascript\'>
    location.href = \'http://www.fqdn.tld:1807/\';
</script>

```
</head>
```

</html>',
)

[06-Aug-2014 22:50:17 +0800](DISCOVERY:): DISCOVERY: (cdfopen) retrieve_addressbooks requesting https://www.fqdn.tld:443/.well-known/carddav [RL 5](DISCOVERY:): DISCOVERY: (cdfopen) SendRequest: http_class::__set_state(array(
   'host_name' => 'www.fqdn.tld',
   'host_port' => 443,
   'proxy_host_name' => '',
   'proxy_host_port' => 80,
   'socks_host_name' => '',
   'socks_host_port' => 1080,
   'socks_version' => '5',
   'protocol' => 'https',
   'request_method' => 'PROPFIND',
   'user_agent' => 'RCM CardDAV plugin/1.0.0',
   'accept' => '',
   'authentication_mechanism' => '',
   'user' => NULL,
   'password' => NULL,
   'realm' => NULL,
   'workstation' => NULL,
   'proxy_authentication_mechanism' => '',
   'proxy_user' => NULL,
   'proxy_password' => NULL,
   'proxy_realm' => NULL,
   'proxy_workstation' => NULL,
   'request_uri' => '/.well-known/carddav',
   'request' => 'PROPFIND /.well-known/carddav HTTP/1.1',
   'request_headers' => 
  array (
    'Host' => 'www.fqdn.tld:443',
    'User-Agent' => 'RCM CardDAV plugin/1.0.0',
    'Depth' => '0',
    'Content-Type' => 'application/xml; charset="utf-8"',
    'Authorization' => 'Basic aG9sZ2VyOjE0dWExNG0=',
    'Connection' => 'Keep-Alive',
    'Content-Length' => 241,
  ),
   'request_user' => 'holger',
   'request_password' => 'mysecretpassword',
   'request_realm' => NULL,
   'request_workstation' => NULL,
   'proxy_request_user' => NULL,
   'proxy_request_password' => NULL,
   'proxy_request_realm' => NULL,
   'proxy_request_workstation' => NULL,
   'request_body' => '<?xml version="1.0" encoding="utf-8"?>
<D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:carddav"><D:prop>
    <D:current-user-principal/>
    <D:resourcetype />
    <D:displayname />
    <C:addressbook-home-set/>
/D:prop/D:propfind
',
   'request_arguments' => 
  array (
    'Protocol' => 'https',
    'HostName' => 'www.fqdn.tld',
    'Headers' => 
    array (
      'Host' => 'www.fqdn.tld:443',
      'User-Agent' => 'RCM CardDAV plugin/1.0.0',
      'Depth' => '0',
      'Content-Type' => 'application/xml; charset="utf-8"',
      'Authorization' => 'Basic aG9sZ2VyOjE0dWExNG0=',
      'Connection' => 'Keep-Alive',
    ),
    'AuthUser' => 'holger',
    'AuthPassword' => 'mysecretpassword',
    'HostPort' => 443,
    'RequestURI' => '/.well-known/carddav',
    'RequestMethod' => 'PROPFIND',
    'Body' => '<?xml version="1.0" encoding="utf-8"?>
<D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:carddav"><D:prop>
    <D:current-user-principal/>
    <D:resourcetype />
    <D:displayname />
    <C:addressbook-home-set/>
/D:prop/D:propfind
',
  ),
   'protocol_version' => '1.1',
   'timeout' => 120,
   'data_timeout' => 0,
   'debug' => 0,
   'log_debug' => 0,
   'debug_response_body' => 1,
   'html_debug' => 0,
   'support_cookies' => 1,
   'cookies' => 
  array (
  ),
   'error' => '',
   'error_code' => 0,
   'exclude_address' => '',
   'follow_redirect' => 0,
   'redirection_limit' => 5,
   'response_status' => '',
   'response_message' => '',
   'file_buffer_length' => 8000,
   'force_multipart_form_post' => 0,
   'prefer_curl' => 1,
   'keep_alive' => 1,
   'sasl_authenticate' => 1,
   'state' => 'RequestSent',
   'use_curl' => true,
   'connection' => NULL,
   'content_length' => 0,
   'response' => 'HTTP/1.1 405 Method Not Allowed
Date: Wed, 06 Aug 2014 14:50:17 GMT
Server: Apache
Allow: GET,HEAD,POST,OPTIONS
Vary: Accept-Encoding
Content-Length: 316
Keep-Alive: timeout=15, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>

<h1>Method Not Allowed</h1>

<p>The requested method PROPFIND is not allowed for the URL /.well-known/carddav.</p>

<hr>

<address>Apache Server at www.fqdn.tld Port 443</address>
</body></html>
',
   'read_response' => 0,
   'read_length' => 0,
   'request_host' => 'www.fqdn.tld:443',
   'next_token' => '',
   'redirection_level' => 0,
   'chunked' => 0,
   'remaining_chunk' => 0,
   'last_chunk_read' => 0,
   'months' => 
  array (
    'Jan' => '01',
    'Feb' => '02',
    'Mar' => '03',
    'Apr' => '04',
    'May' => '05',
    'Jun' => '06',
    'Jul' => '07',
    'Aug' => '08',
    'Sep' => '09',
    'Oct' => '10',
    'Nov' => '11',
    'Dec' => '12',
  ),
   'session' => '67093b585c83b81f9ac8cf5cb598be64',
   'connection_close' => 0,
   'force_close' => 0,
   'connected_host' => 'www.fqdn.tld',
   'connected_port' => 443,
   'connected_ssl' => 1,
))
[06-Aug-2014 22:50:17 +0800](DISCOVERY:): DISCOVERY: (cdfopen) Code: 405
[06-Aug-2014 22:50:17 +0800](DISCOVERY:): DISCOVERY: (cdfopen) success: array (
  'status' => '405',
  'headers' => 
  array (
    'http/1.1 405 method not allowed' => '',
    'date' => 'Wed, 06 Aug 2014 14:50:17 GMT',
    'server' => 'Apache',
    'allow' => 'GET,HEAD,POST,OPTIONS',
    'vary' => 'Accept-Encoding',
    'content-length' => '316',
    'keep-alive' => 'timeout=15, max=100',
    'connection' => 'Keep-Alive',
    'content-type' => 'text/html; charset=iso-8859-1',
  ),
  'body' => '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>

<h1>Method Not Allowed</h1>

<p>The requested method PROPFIND is not allowed for the URL /.well-known/carddav.</p>

<hr>

<address>Apache Server at www.fqdn.tld Port 443</address>
</body></html>
',
)

[06-Aug-2014 22:50:17 +0800](DISCOVERY:): DISCOVERY: (cdfopen) retrieve_addressbooks requesting https://www.fqdn.tld:443/ [RL 5]
[06-Aug-2014 22:50:18 +0800]: DISCOVERY: (cdfopen) SendRequest: http_class::__set_state(array(
   'host_name' => 'www.fqdn.tld',
   'host_port' => 443,
   'proxy_host_name' => '',
   'proxy_host_port' => 80,
   'socks_host_name' => '',
   'socks_host_port' => 1080,
   'socks_version' => '5',
   'protocol' => 'https',
   'request_method' => 'PROPFIND',
   'user_agent' => 'RCM CardDAV plugin/1.0.0',
   'accept' => '',
   'authentication_mechanism' => '',
   'user' => NULL,
   'password' => NULL,
   'realm' => NULL,
   'workstation' => NULL,
   'proxy_authentication_mechanism' => '',
   'proxy_user' => NULL,
   'proxy_password' => NULL,
   'proxy_realm' => NULL,
   'proxy_workstation' => NULL,
   'request_uri' => '/',
   'request' => 'PROPFIND / HTTP/1.1',
   'request_headers' => 
  array (
    'Host' => 'www.fqdn.tld:443',
    'User-Agent' => 'RCM CardDAV plugin/1.0.0',
    'Depth' => '0',
    'Content-Type' => 'application/xml; charset="utf-8"',
    'Authorization' => 'Basic aG9sZ2VyOjE0dWExNG0=',
    'Connection' => 'Keep-Alive',
    'Content-Length' => 241,
  ),
   'request_user' => 'holger',
   'request_password' => 'mysecretpassword',
   'request_realm' => NULL,
   'request_workstation' => NULL,
   'proxy_request_user' => NULL,
   'proxy_request_password' => NULL,
   'proxy_request_realm' => NULL,
   'proxy_request_workstation' => NULL,
   'request_body' => '<?xml version="1.0" encoding="utf-8"?>
<D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:carddav"><D:prop>
    <D:current-user-principal/>
    <D:resourcetype />
    <D:displayname />
    <C:addressbook-home-set/>
/D:prop/D:propfind
',
   'request_arguments' => 
  array (
    'Protocol' => 'https',
    'HostName' => 'www.fqdn.tld',
    'Headers' => 
    array (
      'Host' => 'www.fqdn.tld:443',
      'User-Agent' => 'RCM CardDAV plugin/1.0.0',
      'Depth' => '0',
      'Content-Type' => 'application/xml; charset="utf-8"',
      'Authorization' => 'Basic aG9sZ2VyOjE0dWExNG0=',
      'Connection' => 'Keep-Alive',
    ),
    'AuthUser' => 'holger',
    'AuthPassword' => 'mysecretpassword',
    'HostPort' => 443,
    'RequestURI' => '/',
    'RequestMethod' => 'PROPFIND',
    'Body' => '<?xml version="1.0" encoding="utf-8"?>
<D:propfind xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:carddav"><D:prop>
    <D:current-user-principal/>
    <D:resourcetype />
    <D:displayname />
    <C:addressbook-home-set/>
/D:prop/D:propfind
',
  ),
   'protocol_version' => '1.1',
   'timeout' => 120,
   'data_timeout' => 0,
   'debug' => 0,
   'log_debug' => 0,
   'debug_response_body' => 1,
   'html_debug' => 0,
   'support_cookies' => 1,
   'cookies' => 
  array (
  ),
   'error' => '',
   'error_code' => 0,
   'exclude_address' => '',
   'follow_redirect' => 0,
   'redirection_limit' => 5,
   'response_status' => '',
   'response_message' => '',
   'file_buffer_length' => 8000,
   'force_multipart_form_post' => 0,
   'prefer_curl' => 1,
   'keep_alive' => 1,
   'sasl_authenticate' => 1,
   'state' => 'RequestSent',
   'use_curl' => true,
   'connection' => NULL,
   'content_length' => 0,
   'response' => 'HTTP/1.1 200 OK
Date: Wed, 06 Aug 2014 14:50:17 GMT
Server: Apache
X-Powered-By: PHP/5.3.28
Vary: Accept-Encoding
Content-Length: 326
Keep-Alive: timeout=15, max=100
Connection: Keep-Alive
Content-Type: text/html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
<meta http-equiv="expires" content="0">

<script type=\'text/javascript\'>
    location.href = \'http://www.fqdn.tld:1807/\';
</script>

```
</head>
```

</html>',
   'read_response' => 0,
   'read_length' => 0,
   'request_host' => 'www.fqdn.tld:443',
   'next_token' => '',
   'redirection_level' => 0,
   'chunked' => 0,
   'remaining_chunk' => 0,
   'last_chunk_read' => 0,
   'months' => 
  array (
    'Jan' => '01',
    'Feb' => '02',
    'Mar' => '03',
    'Apr' => '04',
    'May' => '05',
    'Jun' => '06',
    'Jul' => '07',
    'Aug' => '08',
    'Sep' => '09',
    'Oct' => '10',
    'Nov' => '11',
    'Dec' => '12',
  ),
   'session' => '673e8125f3219c2273182f0d0c189ccf',
   'connection_close' => 0,
   'force_close' => 0,
   'connected_host' => 'www.fqdn.tld',
   'connected_port' => 443,
   'connected_ssl' => 1,
))
[06-Aug-2014 22:50:18 +0800]: DISCOVERY: (cdfopen) Code: 200
[06-Aug-2014 22:50:18 +0800]: DISCOVERY: (cdfopen) success: array (
  'status' => '200',
  'headers' => 
  array (
    'http/1.1 200 ok' => '',
    'date' => 'Wed, 06 Aug 2014 14:50:17 GMT',
    'server' => 'Apache',
    'x-powered-by' => 'PHP/5.3.28',
    'vary' => 'Accept-Encoding',
    'content-length' => '326',
    'keep-alive' => 'timeout=15, max=100',
    'connection' => 'Keep-Alive',
    'content-type' => 'text/html',
  ),
  'body' => '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
<meta http-equiv="expires" content="0">

<script type=\'text/javascript\'>
    location.href = \'http://www.fqdn.tld:1807/\';
</script>

```
</head>
```

</html>',
)

Kind regards
Hassan

**Comment by blind-coder** [comment]
The issue_51 branch is merged now. I guess this issue can be closed?

**Comment by ErikBasalt** [comment]
Clsing this issue is fine with me.
Thanks for solving this issue :-D

**Comment by mstilkerich** [comment]
Issue resolved, closing.
