### ISSUE TITLE
display name of company contacts ignored and overruled by organisation name

### ISSUE THREAD

**Issue by muggenhor** [blind-coder/rcmcarddav#53]
The title says it all, but as an example a vcard to demonstrate:

``` vcard
BEGIN:VCARD
VERSION:3.0
UID:73c22b18-226a-11e4-85f9-00247e6a9a6c
ORG:IAK;Zorgverzekeringen
FN:IAK Zorgverzekeringen
TEL;TYPE=work:+31402611888
X-ABSHOWAS:COMPANY
END:VCARD
```

I'd expect to see the FN (display-name) being used as display name ("IAK Zorgverzekeringen"), this however gets overruled by the first component of the organisation name ("IAK"). This would probably be correct behaviour if no display name is present, it isn't however when one _is_ present.

**Comment by mstilkerich** [comment]
This is fixed on the v4.1 branch. It does not overrule FN anymore, and in the other direction it also does not overrule a displayname set by the user in roundcube or by roundcube itself (cannot distinguish the two cases). A displayname is now only composed if FN is not available/empty or if we receive no displayname from roundcube (when a contact is edited/created in the addressbook interface).
