### ISSUE TITLE
Problems loading existing contacts from OwnCloud

### ISSUE THREAD

**Issue by pludi** [blind-coder/rcmcarddav#56]
Environment:
- Debian 7.5
- PHP 5.4.4-14+deb7u14
- php5-fpm 5.4.4-14+deb7u14
- PostgreSQL 9.1.13-0wheezy1
- RoundCube 0.7.2-9+deb7u1
- OwnCloud 7.0.2-1

Problem description:
After configuring the remote addressbook the first sync didn't pull in all of the existing contacts, but instead one at a time at each sync. The following messages appear in Roundcubes error log:

```
[08-Sep-2014 15:23:48 UTC] MDB2 Error: unknown error (-1): _doQuery: [Error message: Could not execute statement]
[Last executed query: SELECT currval('carddav_contacts')]
[Native message: ERROR:  "carddav_contacts" is not a sequence]
```

Expected behaviour:
Syncing all contacts in one go.

**Comment by mstilkerich** [comment]
Issue seems to be fixed, postgres also works for me with current v4 branch.

**Comment by oskapt** [comment]
One would hope that after five and a half years it had been fixed.

**Comment by mstilkerich** [comment]
To my understanding of the last post in this issue it was fixed 6 years ago, just not closed.
