### ISSUE TITLE
practical experience Roundcube 1.0.3 - CardDAV (Branch 51) ?

### ISSUE THREAD

**Issue by HassanMullah** [blind-coder/rcmcarddav#57]
Hi there,

today i read, that there is an update for Roundcube to version 1.0.3. 
Because i use version 1.0.2 with CardDAV Branch 51, and everything works fine, my question is about practical experience with the teamwork Roundcube 1.0.3 an CardDAV Branch 51.

Have someone made an update and is everything running well ?

**Comment by mstilkerich** [comment]
Closing as there seems to be no actual issue here.
