### ISSUE TITLE
Logon based "ADDRESSBOOK PRESETS" possible ?

### ISSUE THREAD

**Issue by HassanMullah** [blind-coder/rcmcarddav#59]
Hi,
i want define 2 adressbook presets, one is read-only mode, the other is for writing the adressbook.
now i'm searching a solution, where my "normal" users will only get the "read-only" addressbook preset and i "as admin" will get both addressbook presets.

because the config.inc.php is a "PHP" file, i think there could by a "if  .... then" loop possible :-)
also if "user = admin@domain.de" then preset 1 +2, else preset 1"
If that could be possible, could anyone give my a little sample code, because i can not PHP

Thank you

**Comment by mstilkerich** [comment]
Closing this as there hasn't been an update in a long time. If there still is an issue, please comment / reopen.
