### ISSUE TITLE
SQL patch files

### ISSUE THREAD

**Issue by ErikBasalt** [blind-coder/rcmcarddav#65]
Would it be possible to start adding SQL patch scripts to dbinit folder, and record the applied patches in a database table? MyRoundcube has a nice solution for that:
- original database SQL file is named: pgsql.initial.sql
- patch files are named: pgsql.YYYYMMDD.sql
- apart from the patch itself (ALTER TABLE....), the files contain something like: UPDATE "system" SET value='initial|20130903' WHERE name='myrc_carddav';
- patch files must be applied in date order

Obviously, we don't want any "myrc" references, and the choice for the table name "system" is a little strange, but actually their solution is quite handy.

This way we even could apply the new SQL patches automatically when installing a plugin update (look which patch files are there now, which ones are already applied, do the new ones). I am already working on a shell script for that.

Best regards,
Erik

**Comment by blind-coder** [comment]
I think I have something usable now.
The dbinit has been copied to dbmigrations/0000-dbinit and uses IF NOT EXISTS (as before) and should also correctly handle configured table prefixes now.
It should also not destroy existing installations :-)

**Comment by ErikBasalt** [comment]
Hi Benjamin,
Sorry for the late reply, I have been away & quite busy.
This new version is not working for me, I don't understand how TABLE_PREFIX should work, removed it manually from dbmigrations\0000-dbinit\postgres.sql but still it cannot create the database automatically. 

I see in logs/errors:
[23-Jan-2015 21:06:21 +0100]: DB Error: [7] ERROR:  relation "carddav_addressbooks" does not exist
LINE 1: SELECT id,password FROM carddav_addressbooks WHERE user_id='...
                                ^ (SQL Query: SELECT id,password FROM carddav_addressbooks WHERE user_id='2') in /volume1/@appstore/MailStation/roundcubemail/program/lib/Roundcube/rcube_db.php on line 467 (POST /mail/?_task=login?_task=login&_action=login)
[23-Jan-2015 21:06:21 +0100]: DB Error: [7] ERROR:  relation "carddav_addressbooks" does not exist
LINE 1: SELECT * FROM carddav_addressbooks WHERE user_id='2' AND pre...
                      ^ (SQL Query: SELECT * FROM carddav_addressbooks WHERE user_id='2' AND presetname is not null) in /volume1/@appstore/MailStation/roundcubemail/program/lib/Roundcube/rcube_db.php on line 467 (POST /mail/?_task=login?_task=login&_action=login)
[23-Jan-2015 21:06:23 +0100]: DB Error: [7] ERROR:  relation "carddav_addressbooks" does not exist
LINE 1: UPDATE carddav_addressbooks SET authentication_scheme='diges...
               ^ (SQL Query: UPDATE carddav_addressbooks SET authentication_scheme='digest' WHERE id=NULL) in /volume1/@appstore/MailStation/roundcubemail/program/lib/Roundcube/rcube_db.php on line 467 (POST /mail/?_task=login?_task=login&_action=login)
[23-Jan-2015 21:06:23 Europe/Amsterdam] PHP Fatal error:  Using $this when not in object context in /volume1/@appstore/MailStation/roundcubemail/plugins/carddav/carddav_backend.php on line 2057

And in carddav.warn:
[23-Jan-2015 21:06:23 +0100]: BACKEND: (update_addressbook) [7] ERROR:  relation "carddav_addressbooks" does not exist
LINE 1: UPDATE carddav_addressbooks SET authentication_scheme='diges...
               ^

On;y when I create the tables manually first, it works fine: the plugin will create the 2 rows in carddav_migrations and I get the contacts in Roundcube.

Best regards,
Erik

**Comment by hcderaad** [comment]
I have the same issue as Erik in the previous comment, running dbinit manually (first removing the table prefix placeholders) fixes the problem. There are unfortunately no helpful messages in the log.

Versions RC 1.1.4 and rmccarddav 1.0

**Comment by blind-coder** [comment]
I should realliy unpublish the 1.0 tag...

Can you please try the procedure with the dev-master branch using composer?

**Comment by hcderaad** [comment]
Thanks for following up @blind-coder but by now I have a working installation (also see #153 ). If I have another opportunity I will test. Once installed (by going through some hoops), the 1.0 seems to work ok btw.

**Comment by mstilkerich** [comment]
Closing this, the dbmigrations mechanism is included in the master branch.
