### ISSUE TITLE
No addressbook found

### ISSUE THREAD

**Issue by rekahsoft** [blind-coder/rcmcarddav#66]
Hi all, I'm using owncloud 7.0.3, and the latest version of rcmcarddav (cloned from master). I followed the instructions in INSTALL and seems to have the plugin working. But when I enter my credentials, the name of the addressbook (in this case just "contacts"), supply the carddav url https://mycloud.com/remote.php/carddav/addressbooks/ausername/contacts and tick the box "Preemptively authenticate against server. Use for ownCloud!" I revieve an error popup saying "An error occured. Contacts, no addressbook found." Does this plugin require carddav_plus?

**Comment by rekahsoft** [comment]
I gave up on it for now :( I'm so sorry for the slow response. When I have some time I will hopefully come back to this.

**Comment by blind-coder** [comment]
Okay. I'll close this issue for now. Feel free to open a new one then.
