### ISSUE TITLE
INSTALL documentation needs updating

### ISSUE THREAD

**Issue by tenbob** [blind-coder/rcmcarddav#71]
I had trouble following step number 6 in the INSTALL file. The file roundcubemail/config/main.inc.php does not exist any more since June 2013. I think the correct file is roundcubemail/config/config.inc.php. And the name of the array has changed. It should be $config['plugins']. HTH.

**Comment by devurandom** [comment]
I also have an issue with the installation: I set `$prefs['foo'] = array(…)` as described in the file, but the configured addressbook does not appear in my account. Also, after adding it manually, it will stay empty. Something important seems to be missing.

**Comment by mstilkerich** [comment]
Documentation has been updated in the v4 branch. Composer is now the only supported way to install the plugin.
https://github.com/blind-coder/rcmcarddav/tree/v4
