### ISSUE TITLE
Error creating new tables @ install

### ISSUE THREAD

**Issue by GitMarq** [blind-coder/rcmcarddav#72]
following the guideline in the INSTALL text file, the database tables need to be created, by executing the mysql command: <QUOTE> mysql -h [db-server-name] -u [user] -p -D roundcubemail <./mysql.sql </QUOTE>
when executing the command, there is an error reported: 
ERROR 1005 (HY000) at line 2: Can't create table '<dbcarddav.carddav_addressbooks' (errno: 150) 
After many attempts, including attempts to create the tables myself, the error seems to come from this statement: 
FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
because if this line is omitted from the script, the error disappears (but the table is probably incorrect, and plugin won't work)

**Comment by blind-coder** [comment]
Do you have a table prefix configured in your roundcube installation?

**Comment by GitMarq** [comment]
@blind-coder: i'm not sure if this will answer your question, but these databases/tabels were generated automatic when installing MariaDb and phpMyAdmin on my Synology NAS (with DSM 5.1), which also runs Roundcube:

Database 'information_schema'; Tables: 
CHARACTER_SETS; CLIENT_STATISTICS; COLLATIONS; COLLATION_CHARACTER_SET_APPL; COLUMNS; COLUMN_PRIVILEGES; ENGINES; EVENTS; FILES; GLOBAL_STATUS; GLOBAL_VARIABLES; INDEX_STATISTICS; INNODB_BUFFER_PAGE; INNODB_BUFFER_PAGE_LRU; INNODB_BUFFER_POOL_PAGES; INNODB_BUFFER_POOL_PAGES_BLI; INNODB_BUFFER_POOL_PAGES_INE; INNODB_BUFFER_POOL_STATS; INNODB_CHANGED_PAGES; INNODB_CMP; INNODB_CMPMEM; INNODB_CMPMEM_RESET; INNODB_CMP_RESET; INNODB_INDEX_STATS; INNODB_LOCKS; INNODB_LOCK; WAITS; INNODB_RSEG; INNODB_SYS_COLUMNS; INNODB_SYS_FIELDS; INNODB_SYS_FOREIGN; INNODB_SYS_FOREIGN_COLS; INNODB_SYS_INDEXES; INNODB_SYS_STATS; INNODB_SYS_TABLES; INNODB_SYS_TABLESTATS; INNODB_TABLE_STATS; INNODB_TRX; INNODB_UNDO_LOGS; KEY_CACHES; KEY_COLUMN_USAGE; PARAMETERS; PARTITIONS; PLUGINS; PROCESSLIST; PROFILING; QUERY_CACHE_INFO; REFERENTIAL_CONSTRAINTS; ROUTINES; SCHEMATA; SCHEMA_PRIVILEGES 

Database 'mysql'; Tables: 
columns_priv; db; event; func; general_log; help_category; help_keyword; help_relation; help_topic; host; ndb_binlog_index; plugin; proc; procs_priv; proxies_priv; servers; slow_log; tables_priv; time_zone; time_zone_leap_second; time_zone_name; time_zone_transition; fime_zone_transition_type; user 

Database 'performance_schema'; Tables: 
cond_instances; events_waits_current; events_waits_history; events_waits_history_long; events_waits_summary_by_instance; events_waits_summary_by_thread_by; events_waits_summary_global_by_ev; file_instances; file_summary_by_event_name; file_summary_by_instance; mutex_instances; performance_timers; rwlock_instances; setup_consumers; setup_instruments; setup_timers; threads

**Comment by blind-coder** [comment]
No, not quite. what'd be interesting is the names of the roundcube tables.

**Comment by GitMarq** [comment]
@blind-coder: there seems to be an install package for the Synology Mail Station:  
http://sourceforge.net/projects/carddavforsynologymailstation/  
I have installed it, and it works.   
Thank you for your support blind-coder 
Ticket can be closed

**Comment by blind-coder** [comment]
Cool thing! Never knew that existed! I'll bookmark and add it to the docs soon.
