### ISSUE TITLE
Password not in sync

### ISSUE THREAD

**Issue by ErikBasalt** [blind-coder/rcmcarddav#75]
I tried this multiple times, really puzzled what is going on.
(using branch auto_db_migrate, either 18dec14 or 06jan15 version).

1) Remove rcmcarddav installation completely, including all related database tables.
2) Install rcmcarddav from scratch, with predefined addressbook in config.inc.php using %u and %p.
3) Start Roundcube with User/Password => predefined CardDAV addressbook is visible.
So far so good. 

But now the same, but before installing rcmmarddav I change password of the Roundcube user.
1) Remove rcmcarddav installation completely, including all related database tables.
2) Change User's password to NewPassword on my Synology NAS, using standard DSM web interface.
3) Start Roundcube with User/NewPassword => Works fine
4) Install rcmcarddav from scratch, with predefined addressbook in config.inc.php using %u and %p.
5) Start Roundcube with User/NewPassword => Works as before, but no CardDAV addressbook :-(
6a) Test 1:
    - Manually add CardDAV addressbook in Roundcube with fixed User and NewPassword => Error, cannot add addressbook
    - Manually add CardDAV addressbook in Roundcube with fixed User and OldPassword(!!) => CardDAV addressbook is visible
6b) ==OR== Test 2:
    - Change User's password back to OldPassword (using Synology DSM web interface again) 
    - Start Roundcube with User/NewPassword => predefined CardDAV addressbook is visible right away
7) Change User's password to AnotherNewPassword on my Synology NAS, using standard DSM web interface
8) Start Roundcube with User/AnotherNewPassword => CardDAV addressbook remains visible

It seems to me that rcmcarddav initially uses the old password (wherever that may be stored!).

Note:
I tried closing the browser in between each action, and I tried removing cookies, same problem.

**Comment by mstilkerich** [comment]
Hello, this is a caveat of the encrypted storage of the user passwords. When the encryption scheme "encrypted" is selected, the carddav password is stored encrypted in the database. As encryption key, the user's imap (roundcube) password is used. Consequently, if you change that password, it cannot decrypt the stored carddav password anymore -> you have to enter the carddav password in the settings again.

If that bothers you, you can choose a different password storing scheme in config.inc.php of the plugin. The drawback is in that case that all user passwords are easily visible to the admin.
