### ISSUE TITLE
Error with Google Contacts

### ISSUE THREAD

**Issue by ElectronicFur** [blind-coder/rcmcarddav#76]
Does this plugin still work with Google Contacts?

I get the following error in the carddav logfile:

`
<errors xmlns="http://schemas.google.com/g/2005">
 <error>
  <domain>GData</domain>
  <code>required</code>
  <location type="header">Authorization</location>
  <internalReason>Login Required</internalReason>
 </error>
</errors>`

**Comment by cotman** [comment]
It works for me, but not with the current HEAD.

I've just been upgrading/moving my Roundcube install and pulled the latest version of rcmcarddav to find Google Contact sync not working.  However, nothing in the logs in my case (they aren't even generated) just a "no address book" dialogue.

Looking at my old install, I had f3e39fd checked-out (which must have been the HEAD at the time).  Checking this commit out and all is working again.  Not dug any deeper to see what it is in the following commits that broke stuff for my install.

**Comment by blind-coder** [comment]
Google has made OAuth 2.0 mandatory for CardDAV access which is not trivially implemented in RCMCardDAV. I don't think this will ever work again.

**Comment by blind-coder** [comment]
Ah, I just found something. Go here:
https://www.google.com/settings/security/lesssecureapps
And enable access for "less secure apps". This will disable mandatory OAuth for Carddav.

**Comment by ElectronicFur** [comment]
Great find. With the setting for less secure apps enabled, the code on the master branch works fine now.

**Comment by blind-coder** [comment]
Wiki is a good idea, I should probably start it.
I've enabled it here on github: https://github.com/blind-coder/rcmcarddav/wiki

**Comment by cotman** [comment]
That's setting doesn't seem to be available on Google Apps accounts:

"This setting is not available for Google Apps accounts."

...unless it's squirrelled away elsewhere.
