### ISSUE TITLE
plugin only syncs contacts starting with letter "A" from owncloud

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [blind-coder/rcmcarddav#78]
Hi there,
I managed to install your plugin and it seams to work. But somehow it only syncs the first 19 contacts from my owncloud adressbook that start with the letter "A".
How can I provide you with a log file?

**Comment by Killer1337** [comment]
Seems like it was coincidence that it stopped after A. The logfile outputs a lot of elements with this error:

	[02-Feb-2015 20:56:34 +0100]: BACKEND: (create_save_data_from_vcard) Couldn't parse vcard: BEGIN:VCARD
	VERSION:3.0
	N:Doe;Jon
	BDAY:1987-04-13
	;="Mobile Phone: +000000":
	EMAIL:xyz@volny.cz
	TEL;TYPE=CELL;TYPE=CELL:+49100000000
	X-UNKNOWN-ELEMENT;TYPE=Home Address:312\n26381 Musterstadt\nDeutschland
	ADR;TYPE=HOME;TYPE=HOME;TYPE=HOME;TYPE=HOME;TYPE=HOME:;;312;Musterstadt;;46803;?e
	 skÃ¡ republika
	X-UNKNOWN-ELEMENT;TYPE=Priority:Normal
	CATEGORIES:Meine Kontakte
	FN:Jon Doe
	UID:5xfghk062-3rrd-43da-bzz3-664bf06xxxxx9@yyyyy.com
	REV:2014-10-13T13:38:33+00:00
	PRODID:-//ownCloud//NONSGML Contacts 0.3.0.17//EN
	END:VCARD

	[02-Feb-2015 20:56:34 +0100]: BACKEND: (dbstore_base) [1048] Column 'name' cannot be null
be null

When I go ahead and add something to the "additional Name" field in owncloud, it syncs fine after that. But strangely, other elements that have an empty "additional Name" field sync just fine.

Do you need more Info to look into this?

**Comment by blind-coder** [comment]
This doesn't seem to be a problem with the "additional Name" field, but rather with a bad vcard and following incorrect error handling.
If you look at the vcard you can see that it's badly formatted. The line:
;="Mobile Phone: +000000":
is not valid syntax. I will look into this, but if you manage to fix that vcard, the import will work fine.

**Comment by mstilkerich** [comment]
This is fixed in the v4 branch, which does not abort the entire sync because a vcard cannot be parsed.
https://github.com/blind-coder/rcmcarddav/tree/v4
