### ISSUE TITLE
Contacts are not displayed even though they are in the database

### ISSUE THREAD

**Issue by bdombrow** [blind-coder/rcmcarddav#79]
Roundcube 1.0.5 running on OS X Server 10.10 with PHP 5.5.14 and PostgerSQL 9.4

I successfully installed the plugin and it imported my contacts as well. However, none of the contacts would show up in the address book. Examining the database shows they are in there.

The problem is in the num_rows() function. Replacing all calls to num_rows() with count($result->fetchAll()) and using that value fixes the problem. I'm not sure what is going on with the num_rows() function in rcube_db.php, but it doesn't appear to be used in the roundcube code.

**Comment by blind-coder** [comment]
I'm not using num_rows anywhere:
```bash
[git:master][A:0][D:0][M:1][?:0]
[10:05:04][blindcoder@pallas:/home/www/anderdonau.de/mail/htdocs/plugins/carddav]$ grep num_rows . -R
[git:master][A:0][D:0][M:1][?:0]
[10:05:09][ret:1][blindcoder@pallas:/home/www/anderdonau.de/mail/htdocs/plugins/carddav]$
```
Are you sure this is a bug in rcmcarddav?

**Comment by bdombrow** [comment]
You are correct. My apologies, I wasn't using rcmcarddav.
