### ISSUE TITLE
Job title should map to vcard 'ROLE' not 'TITLE'

### ISSUE THREAD

**Issue by gregkster** [blind-coder/rcmcarddav#81]
When I add Job title in Roundcube it saves as "TITLE", but iphone and Andoid do not show it. 

BEGIN:VCARD
VERSION:3.0
PRODID:Z-Push
FN:Bob Simpson
N:Simpson;Bob;;;
UID:C7015181-7526-4BF8-AB0E-5F016EA81232
REV:2015-02-03T00:28:50-05:00
X-ABSHOWAS:INDIVIDUAL
**TITLE:CFO**
EMAIL;TYPE=home:tex2bob@simpson.com
EMAIL;TYPE=work:foo@bar.com
TEL;TYPE=home:555
END:VCARD

Then I added a Job Title "Cook" on the iphone, and it saved it as "ROLE":

BEGIN:VCARD
VERSION:3.0
PRODID:Z-Push
FN:Bob Simpson
N:Simpson;Bob;;;
EMAIL;PREF=1:tex2bob@simpson.com
EMAIL;PREF=2:foo@bar.com
TEL;TYPE=HOME,VOICE:555
**ROLE:Cook**
UID:C7015181-7526-4BF8-AB0E-5F016EA81232
END:VCARD

**Comment by blind-coder** [comment]
TITLE and ROLE are similiar, but different nonetheless. From RFC 2426:
```text
3.5.1 TITLE Type Definition

   To: ietf-mime-directory@imc.org

   Subject: Registration of text/directory MIME type TITLE

   Type name: TITLE

   Type purpose: To specify the job title, functional position or
   function of the object the vCard represents.

   Type encoding: 8bit

   Type value: A single text value.



Dawson & Howes              Standards Track                    [Page 17]

RFC 2426              vCard MIME Directory Profile        September 1998


   Type special notes: This type is based on the X.520 Title attribute.

   Type example:

        TITLE:Director\, Research and Development

3.5.2 ROLE Type Definition

   To: ietf-mime-directory@imc.org

   Subject: Registration of text/directory MIME type ROLE

   Type name: ROLE

   Type purpose: To specify information concerning the role, occupation,
   or business category of the object the vCard represents.

   Type encoding: 8bit

   Type value: A single text value.

   Type special notes: This type is based on the X.520 Business Category
   explanatory attribute. This property is included as an organizational
   type to avoid confusion with the semantics of the TITLE type and
   incorrect usage of that type when the semantics of this type is
   intended.

   Type example:
        ROLE:Programmer
```

Roundcube explicitly identifies the field "Jobtitle" with the TITLE attribute:
```php
./program/lib/Roundcube/rcube_vcard.php:        'jobtitle' => 'TITLE',
```

Which Android setup are you using (ROM, Addressbook editor, sync-client)?

**Comment by gregkster** [comment]
I am using: 
Android 4.1.2 built-in address book (no third party apps) on Nexus S
IOS 8.1.1 on iphone 5

Both use ROLE and ignore TITLE

**Comment by blind-coder** [comment]
Android with built-in addressbook doesn't sync to CardDAV. Don't know about iOS. I'll try to make some sense out of this after the next release (wich will happen when composer works).

**Comment by mstilkerich** [comment]
I tried this with iOS 14 addressbook, Nextcloud 18, mac OS Addressbook and iCloud Web Addressbook. All map the job title to the TITLE attribute. Maybe there was a change in the last few years.

Therefore I am closing this issue.
