### ISSUE TITLE
Some kind of url encoding is missing in dbstore_contact

### ISSUE THREAD

**Issue by gregkster** [blind-coder/rcmcarddav#82]
I use Baikal and email addresses for usernames, so urls contain "@" symbol.  I had to replace @ with %40 to get things to work.

So I replaced this in carddav_backend.php in function insert:
        $url = carddav_common::concaturl($this->config['url'], $uri);
        $url = preg_replace(';https?://[^/]+;', '', $url); 
        $dbid = $this->dbstore_contact($etag,$url,$vcfstr,$save_data);

with this:
        $url = carddav_common::concaturl($this->config['url'], $uri);
        $url = preg_replace(';https?://[^/]+;', '', $url);
        $url = str_replace('@', '%40', $url);
        $dbid = $this->dbstore_contact($etag,$url,$vcfstr,$save_data);

Obviously, this is not a proper fix

**Comment by blind-coder** [comment]
That is a very strange place where you have to add it.
dbstore_contact is the function saving the contact to the LOCAL database, not the Baikal DB. At this point, the contact is already created in Baikal.
Can you maybe look into this a bit more as I don't have a Baikal server I can test against?

**Comment by mstilkerich** [comment]
There issue here is that the server-returned URIs are compared to URIs created by the plugin in some places. It may occur that we have a local URI containing non-URL-encoded characters like @, when we receive URIs from the server that are properly URL-encoded. So the comparisons would fail even though the URIs are the same.

The v4 branch should fix this, it normalizes the URIs before comparison.
https://github.com/blind-coder/rcmcarddav/tree/v4
