### ISSUE TITLE
XML parsing errors with Baikal

### ISSUE THREAD

**Issue by gregkster** [blind-coder/rcmcarddav#83]
I am using Baikal 0.2.5.  It seems Baikal adds some space and a newline character to its XML responses.  The causes the following error:

[08-Feb-2015 08:05:55 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to parse response as XML' in /home/gregk/git_repos/rcmcarddav/inc/Httpful/Handlers/XmlHandler.php:44
Stack trace:
#0 /home/gregk/git_repos/rcmcarddav/inc/Httpful/Response.php(103): Httpful\Handlers\XmlHandler->parse('   ?<?xml versi...')
#1 /home/gregk/git_repos/rcmcarddav/inc/Httpful/Response.php(42): Httpful\Response->_parse('   ?<?xml versi...')
#2 /home/gregk/git_repos/rcmcarddav/inc/Httpful/Request.php(229): Httpful\Response->__construct('   ?<?xml versi...', 'HTTP/1.1 401 Un...', Object(Httpful\Request))
#3 /home/gregk/git_repos/rcmcarddav/carddav_common.php(182): Httpful\Request->send()
#4 /home/gregk/git_repos/rcmcarddav/carddav_discovery.php(123): carddav_common->cdfopen('https://localho...', Array, Array)
#5 /home/gregk/git_repos/rcmcarddav/carddav_discovery.php(93): carddav_discovery->retrieve_addressbooks('/card.php/addre...', Array)
#6 /home/gregk/git_repos/rcmcarddav/carddav.php(144): carddav_discovery->find_addressbooks('https://localho...', ' in /home/gregk/git_repos/rcmcarddav/inc/Httpful/Handlers/XmlHandler.php on line 44

I fixed it by adding trim() in two places.
--- a/carddav_common.php
+++ b/carddav_common.php
@@ -112,7 +112,7 @@ class carddav_common
                if(!self::check_contenttype($reply['headers']['content-type'], ';(text|application)/xml;'))
                        return false;
-               $xml = new SimpleXMLElement($reply['body']);
-               $xml = new SimpleXMLElement(trim($reply['body']));
              $this->registerNamespaces($xml);
              return $xml;
      }

--- a/inc/Httpful/Request.php
+++ b/inc/Httpful/Request.php
@@ -226,7 +226,8 @@ class Request

```
     curl_close($this->_ch);
```
-        return new Response($body, $headers, $this);
-        return new Response(trim($body), $headers, $this);
   }
   public function sendIt()
   {

**Comment by blind-coder** [comment]
Is the trim in inc/Httpful/Request.php necessary or is the first trim enough?

**Comment by hcderaad** [comment]
Using rcmcard 1.0 with Baikal 0.4.4, no such issues.

**Comment by mstilkerich** [comment]
Closing this issue because of its age. The current development branch v4 uses Sabre/Xml to parse XML objects, so I believe such issues are fixed in the meantime.
https://github.com/blind-coder/rcmcarddav/tree/v4

Nevertheless, if the issue still persists, please leave a comment / reopen the issue for proper investigation.
