### ISSUE TITLE
iCloud Support

### ISSUE THREAD

**Issue by rabbittsoup** [blind-coder/rcmcarddav#85]
https://contacts.icloud.com responds with the following WWW-Authenticate header (at least for me):

WWW-Authenticate: X-MobileMe-AuthToken realm="Newcastle", Basic realm="Newcastle"

CardDAV only looks at the first authentication scheme.  In this case, Apple's scheme is not recognized and no authentication is attempted.  CardDAV fails with a no addressbooks found error message.

Once I changed carddav_common.php to search the entire header, using https://contacts.icloud.com worked and CardDAV automatically found my iCloud specific address book.  It works for me, though the rudimentary method of tokenizing the header may not be the most robust.

```
$ diff carddav_common.php carddav_common.php.orig
186,197c186,192
<                 foreach (explode(" ", strtolower($error->headers["www-authenticate"])) as $value) {
<                     if ($value == "digest") { $scheme = $value; break; }
<                     else if ($value == "basic") { $scheme = $value; }
<                 }
<                 switch ($scheme) {
<                 case "digest":
<                     $httpful->digestAuth($username, $password);
<                     break;
<                 case "basic":
<                     $httpful->basicAuth($username, $password);
<                     break;
<                 }
---
>                 if (strtolower(substr($error->headers["www-authenticate"],0,6)) == "digest"){
>                     $httpful->digestAuth($username, $password);
>                     $scheme = "digest";
>                 } else if (strtolower(substr($error->headers["www-authenticate"],0,5)) == "basic"){
>                     $httpful->basicAuth($username, $password);
>                     $scheme = "basic";
>                 }
```

**Comment by blind-coder** [comment]
You are right, this case must be handled, though I'll handle it differently.
The problem is that there might not be a whitespace prefixing the "Basic" string, so I'll go with - less efficient, but less error-prone - preg_match("/\bBasic\b/i"):
```php
<?php
preg_match_all("/\bBasic\b/i", "basic BASIC,BaSiC", $matches);
print_r($matches);
?>
Array
(
    [0] => Array
        (
            [0] => basic
            [1] => BASIC
            [2] => BaSiC
        )

)
```

**Comment by blind-coder** [comment]
Can you please check latest master branch (commit de79572..a1455f7)?
It contains code to better parse the WWW-Authenticate header as described above and also checks for Basic first before Digest (because Digest is probably less popular)

**Comment by rabbittsoup** [comment]
Very good.  However, checking for basic first will cause the code to use basic, even if digest is also available.  I would think one would prefer the strongest scheme available, among multiple.

**Comment by blind-coder** [comment]
Good idea, I'll swap it back.

**Comment by rabbittsoup** [comment]
Excellent.  This works for my case.
