### ISSUE TITLE
Password stored in clear text (base 64)

### ISSUE THREAD

**Issue by GO3LIN** [blind-coder/rcmcarddav#89]
Hello,

I installed rcmcarddav plugin and just noticed that passwords are stored in db with base64 encryption without any other security. I think that it isn't very safe to keep thoses informations in db like this, correct me if I am wrong. Or there's something that i skipped in my configuration ?

Thanks for you help

**Comment by blind-coder** [comment]
You are right, they are stored as base64 by default. This is because of differing password-change mechanisms across different services.
You can change this in config.inc.php, though. From config.inc.php.dist:

```php
// Scheme for storing the CardDAV passwords.
// Options:
// plain: store as plaintext
// base64: store encoded with base64 (default)
// encrypted: store encrypted with IMAP password of the user
//            NOTE: if the IMAP password of the user changes, the stored
//             CardDAV passwords cannot be decrypted anymore and the user
//             needs to reenter them.
// $prefs['_GLOBAL']['pwstore_scheme'] = 'base64';

```

**Comment by GO3LIN** [comment]
Thank you I used the encrypted parameter, now passwords are encrypted with md5, It's a little more secured thanks.
