### ISSUE TITLE
undefined function Httpful\curl_init with rc 1.1.0

### ISSUE THREAD

**Issue by ltsavar** [blind-coder/rcmcarddav#90]
Hi,

I can't use rcmcarddav with roundcube 1.1.0

When saving a new addressbook I get:
Fatal error: Call to undefined function Httpful\curl_init() in /var/www/roundcube/plugins/carddav/inc/Httpful/Request.php on line 826

I also tried rcmcarddav-composer from #87 but got an different error there.

**Comment by evert** [comment]
This means your PHP doesn't have the curl extension installed.

**Comment by ltsavar** [comment]
Thanks. You are right.
Should also be mentioned in the install file. Cause its not required for a normal roundcube installation http://trac.roundcube.net/wiki/Howto_Requirements
