### ISSUE TITLE
Cannot Open Email anymore

### ISSUE THREAD

**Issue by tonyvier** [blind-coder/rcmcarddav#92]
Hi,

Installed everything, all works fine with SabreDav, can import contacts, create email with contacts from rcmcarddav etc.

But, when I want to open a received email, the ajax loader gif keeps on spinning, nothing happens...

Have no idea where to look..

RC 1.1.0 

edit(1): Looking at logs I see that the server generates a 500 error upon opening the iframe with the preview of the email.

Disabling the plugin makes things work again...

p.s.

Roundcube directory is not located in www directory, but included with "Alias". Rights are all set to Apache user.

edit(2):

The RC error actually shows:

[22-Mar-2015 13:13:21 Europe/Berlin] PHP Fatal error:  Class vobject_location_property contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Sabre\VObject\Property::getValueType, Sabre\VObject\Property::setRawMimeDirValue, Sabre\VObject\Property::getRawMimeDirValue) in /usr/share/roundcube/plugins/libcalendaring/libvcalendar.php on line 0

So, after enabling the rcmcarddav plugin, the calendar plugin generates fatal errors....

Disabling the calendar plugin makes rcmcarddav work...

**Comment by akrah** [comment]
I have the same comportment with Roundcube located at www directory.

**Comment by blind-coder** [comment]
That's a problem with the different vobject implementations.
There's been a fix in #54 which has been merged into master. Can you try with latest master?

**Comment by akrah** [comment]
I was already using the latest master.
I tried to reinstall but I have the same problem.
List of my plugins:
$config['plugins'] = array( zipdownload, attachment_reminder, markasjunk, archive, jqueryui, calendar, contextmenu, carddav, message_highlight );

I executed composer for rcmcarddav and libcalendaring.
I dont't why Sabre versions of each plugins interfere.

**Comment by blind-coder** [comment]
In that case it's probably an issue with order of plugins being loaded.
Seriously, the proper is is getting the calendar plugin to update their version of sabredav. carddav already checks if another sabredav version is loaded and uses that one then.
Try rearranging the plugins so that carddav gets loaded after calendar.

**Comment by mstilkerich** [comment]
The proper way to detect such incompatibilities is to use composer on the entire roundcube installation, i.e. have a single vendor directory in roundcube/vendor, not with every plugin. That way, composer will detect incompatible version constraints of different plugins and at least point out these conflicts. I'm closing this as there is nothing we can do about it (except installation instructions for the above, which are contained with v4).
https://github.com/blind-coder/rcmcarddav/tree/v4
