### ISSUE TITLE
Blank page after configuration

### ISSUE THREAD

**Issue by disanvparean** [blind-coder/rcmcarddav#93]
Hello,
Using Roundcube 1.1.1, I have a blank page once I put my parameters in carddav options. Nothing in logs.
Don't know what to do, I tried to change permissions of carddav's dir but no change.
Thank you

**Comment by petrkutalek** [comment]
I noticed the same after login. When username/password is submitted, I have to manually reload the page.

**Comment by 2can-** [comment]
I'm seeing a similar issue. Login to Roundcube and all I get is a blank screen. If I reload the page I can get to my mail as usual. I've tried removing the plugin and the problem goes away. Nothing in the error log.

Roundcube 0.9.5
carddav 1.0.0
Ubuntu Server 14.10

**Comment by blind-coder** [comment]
Can you please try roundcube 1.0? I just today realized that the plugin relies on a function introduced in 1.0.

**Comment by petrkutalek** [comment]
I am afraid there have to be another issue; I have installed Roundcube 
Webmail 1.1.1. :-/

**Comment by blind-coder** [comment]
@petrkutalek Can you send over some more details of your installation?
What's the backend database?
What other plugins do you have installed?

**Comment by petrkutalek** [comment]
RC 1.1.1
PHP 5.5.9
MySQL 5.5.43
nginx 1.4.6

![screen shot 2015-06-02 at 23 31 17](https://cloud.githubusercontent.com/assets/7659931/7947882/39bc427a-0980-11e5-9aba-6f02aca3b682.png)

**Comment by blind-coder** [comment]
Can you try setting DEBUG and DEBUG_HTTP to true in carddav_common.php and try again?
After that, you will find lots of output in the file roundcube/logs/carddav. Can you then prune that of passwords and URLs and upload it to gist or pastebin?

**Comment by petrkutalek** [comment]
@blind-coder OK, I will try that during weekend and provide you with logs.

**Comment by petrkutalek** [comment]
I'm sorry @blind-coder, I wanted to help you, nevertheless you have added some "composer" stuff since I tried your addon last time. I have absolutely no idea what the composer is, how to install it etc. I am not able to generate required 'vendor/autoload.php'. I am unable to assist you anymore.

**Comment by blind-coder** [comment]
@petrkutalek To get composer, run these commands (from https://getcomposer.org/doc/00-intro.md#locally):
```
curl -sS https://getcomposer.org/installer | php
php composer.phar
```

**Comment by vsandre** [comment]
The Problem if installed via composer all dependancies will be saved in the "roundcube-folder/vendor". Carddav-plugin will search instead in "roundcube-folder/plugins/carddav/vendor" and will not find anything. (composer update in the carddav folder will help for the moment)

BTW: The calender plugin using sabre dav 2.2. Update to 3.3 is in git https://git.kolab.org/rRPKd99b8f8fee1d8260e450bb06ce06f2428a78b55e

**Comment by webernetz** [comment]
Hi there. I tried to install the plugin, but it doesn't work. After enabling 'carddav' in the plugins config, my roundcube webmailer shows only a blank screen.
The error log lists the following:

[16-Jul-2015 14:22:16 Europe/Berlin] PHP Warning:  require_once(/var/www/roundcube/plugins/carddav/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/roundcube/plugins/carddav/carddav_common.php on line 22

(Same as vsandre already said: carddav is looking in the wrong path for the vendor/autoload.php file.)
What can I do?

**Comment by blind-coder** [comment]
@webernetz
did you install rcmcarddavs depencies? or just the roundcube ones?

**Comment by webernetz** [comment]
Ah shit. I made a mistake in step 2 of the INSTALL sequence. Now it's working. SORRY for that!

**Comment by tagru** [comment]
@vsandre This problem still occurs with installing the latest version through composer from roundcube. I have run composer.phar from the carddav directory and now it works. But shouldn't it work with installation from the main directory as well?

**Comment by blind-coder** [comment]
@tagru that would be great, but unfortunately composer doesn't handle dependencies of subdirectories.

**Comment by mstilkerich** [comment]
Please use composer in the root directory of roundcube, which will check version constraints across all plugins and roundcube itself if managed by composer. This way of installation is described in v4:
https://github.com/blind-coder/rcmcarddav/tree/v4
