### ISSUE TITLE
Blank page after plugin install

### ISSUE THREAD

**Issue by realriot** [blind-coder/rcmcarddav#95]
- Added "roundcube/carddav": "dev-issue_54" to composer.json
- Installed plugin with php composer.phar install
- Plugin activated in config/config.inc.php

After calling the roundcube http://mail.mydomain.de the site remains empty
Within logs/errors I find:

[14-Apr-2015 19:19:23 Europe/Berlin] PHP Fatal error:  require_once(): Failed opening required '/Library/Server/Web/Data/Sites/mail.mydomain.de/plugins/carddav/vendor/autoload.php' (include_path='/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear/pear_exception:/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear/mail_mime:/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear/net_smtp:/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear-pear.php.net/Auth_SASL:/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear-pear.php.net/Net_IDNA2:/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear/mail_mime-decode:/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear-pear.php.net/Console_Getopt:/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear-pear.php.net/Structures_Graph:/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear-pear.php.net/XML_Util:/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear-pear.php.net/PEAR:/Library/Server/Web/Data/Sites/mail.mydomain.de/vendor/pear-pear.php.net/Net_Socket:/Library/Server/ in /Library/Server/Web/Data/Sites/mail.mydomain.de/plugins/carddav/carddav_common.php on line 22

**Comment by blind-coder** [comment]
It seems that the PHP script is not allowed to include the file. Do you have any PHP restrictions configured (open_basedir and such)?
Is the HTTP process allowed to actually read the vendor/ directory?

**Comment by realriot** [comment]
After adding a symbolic link to the plugin directory I could access and configure CardDAV... The symbolic link called "vendor" is linked to the vendor directory located in the roundcube root. So there shouldn't be an right problem since this access works.

The include seems to have problems... Wrong path?

**Comment by blind-coder** [comment]
I don't quite understand the setup of symlinks you have.
Can you show me some ls -l outputs of the relevant directories?

**Comment by realriot** [comment]
- Fresh install of roundcube 1.1.1
- Install of composer
- added carddav to composer.json
- Plugin installation via composer

Afterwards I'll get a blank page accessing my roundcube installing. The error log shows me that the autoload.php cannot be found.

Within my roundcube root directory I'll create the symlink this way:
cd plugins/carddav
ln -s ../../vendor/ vendor

lrwxr-xr-x   1 sascha  admin     13 Apr 15 14:42 vendor -> ../../vendor/

Within the root directory of the roundcube installation a vendor directory exists (created by composer?)

**Comment by blind-coder** [comment]
Aaah, now I get it. You installed rcmcarddav via composer, not installed rcmcarddav's dependencies via composer.
I gotta admit, I don't know that much about composer. Maybe @phsc can say something about that.

In the meantime, what you want to do is go to plugins/carddav and do a composer install there.

**Comment by realriot** [comment]
Ok this works. A vendor directory is created and no blank page appears.

Installing the way told on the official plugin site does not work...

**Comment by phsc** [comment]
Maybe it helps to insert the following code into the rcmcarddav composer.json after "repositories":
        {
            "type": "composer",
            "url": "http://plugins.roundcube.net"
        }

Could you try this please? I would try it myseelf, but unfortunately I'm quite limited at the moment, because I got my right shoulder dislocated...

**Comment by phsc** [comment]
Damn, it seems, that composer is not able to resolve dependencies of subirectories (as rcmcarddav in fact is). See also this issue: https://github.com/composer/composer/issues/183

To resolve such problems, I see the following options:
1) Include all dependencies in rcmcarddav's git repository (not the perfect solution, as already discussed in #87)
2) Add a note about this in rcmcarddav's INSTALL instructions (not the perfect solution as well...)

**Comment by phsc** [comment]
https://github.com/composer/composer/issues/2480

**Comment by evert** [comment]
If I understand this issue correctly, the problem is not that 'dependencies of subdirectories aren't resolved'. Dependencies _of_ dependencies are correctly included.

So if this package is added to `require` by another package, it will just work. I think the problem is that this package wants to include an autoloader at a specific location when it shouldn't.

There's no great way to fix this, but the way I always fix this is by including `autoload.php` like this:

https://github.com/fruux/sabre-vobject/blob/3.4/bin/vobject#L8

To fix this, add something similar to carddav.common.php to make this work.

But that's only the correct solution if rcmcarddav's php files are called directly, if they are not called directly but included by roundcube then that's not needed, as the autoloader is already active.

**Comment by blind-coder** [comment]
@evert Yes, that seems to be the best possible solution. I'll put in something like that and issue a warning if none can be found.

**Comment by robpanzer** [comment]
Thanks realriot for bringing this up.  It's been bothering me for months.  
@evert You don't happen to have a working copy of this workaround through the editing of carddave.common.php?  I'm trying to find a place to insert the similar code but my coding skills are a bit lacking.

**Comment by Feanwulf** [comment]
I upgraded from roundcubemail 1.0.1 to 1.1.1 and installed the plugin the first time. Got a white page when manually installing. I then downloaded the composer to the carddav plugin directory and installed the reuirements using the "php composer.phar install" command - resulting in no white page :)
