### ISSUE TITLE
Cannot register action plugin.autocomplete-get-mails-x; already taken by another plugin

### ISSUE THREAD

**Issue by robpanzer** [blind-coder/rcmcarddav#98]
Ran into an issue after installing Carddav.  Did a fresh install of RC; then installed the plugins I usually use and no issues came up.  I ran the install for Carddav and once I configured everything and tried to get back into RC.  Everything looked fine until I tried to actually open an e-mail.  The preview pane went to a: "File not found" and the following was spit out in my log file.

[24-Apr-2015 22:39:09 -0500]: <57f2nos0> PHP Error: Cannot register action plugin.autocomplete-get-mails-x; already taken by another plugin in /srv/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 444 (GET /mail/?_task=mail&_mbox=INBOX)

[24-Apr-2015 22:39:10 -0500]: <57f2nos0> PHP Error: Cannot register action plugin.autocomplete-get-mails-x; already taken by another plugin in /srv/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 444 (GET /mail/?_task=mail&_refresh=1&_mbox=INBOX&_remote=1&_unlock=loading1429933130812&_action=list&_=1429933130617)

[24-Apr-2015 22:39:10 -0500]: <57f2nos0> PHP Error: Cannot register action plugin.autocomplete-get-mails-x; already taken by another plugin in /srv/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 444 (GET /mail/?_task=mail&_remote=1&_unlock=0&_action=getunread&_=1429933130618)

Has anyone come across this error? Everything related to Carddav works like a charm.  I am able to connect to my OC Carddav and pull contacts with no issues.  I can't see a reason why Carddav would effect the preview pane.  Once the preview pane goes to the 404 page RC is no longer responsive unless I reload the actual page.

In hopes of ruling out human error I did another fresh install with the same results.

**Comment by blind-coder** [comment]
carddav is not calling the register_action method, and there's also nothing about autocomplete-get-mails-x  in there.
Does this also happen without the carddav plugin enabled?

**Comment by robpanzer** [comment]
The issue does persist(in part) after removing Carddav, but it does not start until I install Carddav.  After removing Carddav the preview pane goes back to functioning properly but the logs are still aggregating those errors.  I'm not sure how the errors in the log are related to Carddav.  I'm wondering if it's a dependency that is causing the log errors.  The errors in the log are not crippling to RC that I can tell but the preview pane being broken after installing Carddav is the real issue.  
This weekend I spent a bit of time reinstalling RC then mixing and matching plugins to see if I could get carddav installed w/o running to any issues.  No dice yet.  Every time I install RC and then Carddav it cripples the preview pane and then those errors start showing up in the log.  

I will report back with any headway I make.

**Comment by blind-coder** [comment]
That's really, really strange.
If you could make out which minimal combination of plugins causes that problem, that would really help in addressing the issue.

**Comment by robpanzer** [comment]
Okay, here goes. Carddav works by itself.  Calendar/Tasklist/libcalendaring works by themselves.  Carddav installed with Calendar and/or Tasklist will cause the preview pane to break with the following error:  

[28-Apr-2015 08:05:54 America/Chicago] PHP Fatal error:  Class vobject_location_property contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Sabre\VObject\Property::getValueType, Sabre\VObject\Property::setRawMimeDirValue, Sabre\VObject\Property::getRawMimeDirValue) in /srv/roundcube/plugins/libcalendaring/libvcalendar.php on line 1322

It appears that somehow Sabre and libcalendaring are not interacting correctly.  Carddav's Sabre dependency is the culprit?  I don't know enough about the system to say for sure how the error arises.  With kolab/libcalendaring and Carddav installed by themselves I do NOT run into any issues.  It is not until I install either Tasklist or Calendar that the preview pane breaks.  Carddav itself works perfectly in either situation.  It is just whenever I try to access the preview pane RC breaks.

I'll see if I can find a fix but my coding skills are lacking.  Let me know if I can be of any more help or annoyance.  Also let me know if you think I should report this error to Kolab instead.  

---
The log errors in my first post were because of flanpy/autocomplete being broken(not Carddav).  The errors for some reason happen only after Carddav is installed.  It does not cause any critical errors.  When running flanpy/autocomplete by itself I do not get that error.  Just an odd error that does not cause any harm.

**Comment by blind-coder** [comment]
It should certainly _also_ be communicated to kolab. Can you try re-ordering the list of plugins so that carddav is loaded _after_ kolabs calendar plugin? It _should_ work around this issue properly.

**Comment by evert** [comment]
Isn't this another case where Kolab uses sabre/vobject 2.0 and rcmcarddav 3.0?

**Comment by blind-coder** [comment]
@evert That's what I believe, too. Maybe loading carddav after kolab fixes this. It should...

**Comment by robpanzer** [comment]
Unfortunatly re-ordering them does not resolve the issue.  That was the first thing I tried after solving the Carddav/Kolab link.  I tried all sorts of reordering with no dice.  I'll keep on it and let you know if I find the right solution.

**Comment by robpanzer** [comment]
Without the use of Composer, I was able to get spotsh/roundcube-calendar-caldav 's fork on github to actually kinda work with Carddav installed.  Using his calendar/libcalendaring plugins I am able to run the preview pane with no issues now.  The only thing is still a couple errors on the calendar portion when it tries to load from the database.

**Comment by chris42** [comment]
I am just having the same problem. So having a few questions:
- What is the difference between the spotsh caldav one and the awesome-it.de caldav implementation? It is forked, but I can't see the reason?!
- Did you read https://gitlab.awesome-it.de/kolab/roundcube-plugins/issues/13 ? Is it an option for carddav to downgrade?

**Comment by blind-coder** [comment]
Hrrm, that's exactly what I was afraid it would be.
There's actually code in place to prevent CardDAV from loading VObject if there's already a VObject loaded.

You can try adjusting the require for sabre/vobject in composer.json to the version shipped with kolab and re-running composer. Though I'm not sure if that'll actually work.

**Comment by mstilkerich** [comment]
Closing this at it seems two plugins with incompatible dependencies are used. Please use composer in the root directory of roundcube so it can check dependencies across all roundcube plugins.
